### ISSUE TITLE
Missing @Path annotation causes odd NPE in 0.8.1

### ISSUE THREAD

**Issue by baank** [dropwizard/dropwizard#1066]
Referring to: https://github.com/federecio/dropwizard-swagger/issues/52

If the @Path annotation is missing from a Resource a NPE is thrown in this class:
io.dropwizard.jersey.DropwizardResourceConfig$EndpointLogger.normalizePath

Instead of throwing random, odd NPE it should clean show an ERROR log message stating that a path is missing from a resource ideally indicating which one.

**Comment by thiagomoretto** [comment]
@baank AFAIK `@Path` annotation on class level is not necessarily required, so you can add `@Path` just on method level. Instead of a better message, we could fix this.

So, I've just send a pull request (https://github.com/dropwizard/dropwizard/pull/1067) with a possible fix, maybe we could discuss there if this issue was really fixed or we should do something yet.
