### ISSUE TITLE
Testing async request using ResourceTestRule

### ISSUE THREAD

**Issue by mattuuh7** [dropwizard/dropwizard#1099]
Hello,
I am setting up testing my rest endpoints with `ResourceTestRule`. With jersey api I am able to get the `Future<Response>` object from the `async().post(Entity)` call, but then got the below warning:

```
WARN  [2015-06-04 10:46:47,508] org.glassfish.jersey.test.inmemory.InMemoryConnector: Asynchronous server side invocations are not supported by InMemoryContainer.
```
and the test keep hanging. This Warning seems to be coming from jersey `org.glassfish.jersey.test.inmemory.InMemoryConnector` is there any plan for tackling this so async request could work with `InMemoryConnector`? Or any resource we can look at while this is not available yet.

Thanks,

**Comment by nickbabcock** [comment]
Looks like `InMemoryConnector` doesn't support endpoints that can be suspended and are async, so a new testing container is needed. You may need to try out the Grizzly test web server. I was able to swap it out and have my test cases pass.

First you'll need to look up how to import the Grizzly test web server in your pom (see the Dropwizard documentation on [testing resources](http://www.dropwizard.io/manual/testing.html#testing-resources)

Here's the code for swapping:

```java
@Rule
public final ResourceTestRule resources = ResourceTestRule.builder()
        .addResource(new HelloWorldResource())
        .setTestContainerFactory(new GrizzlyWebTestContainerFactory())
        .build();
```

and instead of calling `resources.client().target(/*...*/)`, you want `resources.getJerseyTest().target(/*...*/)`

Let me know if this works.

**Comment by mattuuh7** [comment]
@nickbabcock thanks this works! I have tried to work around by overloading the suspend method in `InMemoryConnector` but seems Grizzly test factory did the work already. Thanks again

**Comment by halfwind22** [comment]
For the convenience of anybody else facing weird issues after injecting an instance of GrizzlyWebTestContainerFactory:  We  must ensure that the version of "jersey-test-framework-provider-grizzly2" must match with the version of Jersey used.
