### ISSUE TITLE
No injection source found for a parameter

### ISSUE THREAD

**Issue by almy** [dropwizard/dropwizard#1115]
Hello,

I am having troubles adding Basic Authentication to my Dropwizard application. I am using DW 0.8.1 
I have followed this artciles http://java.dzone.com/articles/getting-started-dropwizard-0 but I keep getting the following

``` java
WARN  [2015-06-17 08:55:10,030] /: unavailable
! org.glassfish.jersey.server.model.ModelValidationException: Validation of the application resource model has failed during application initialization.
! [[FATAL] No injection source found for a parameter of type
```

Initially I thought that the issue was related to https://github.com/dropwizard/dropwizard/issues/783 but my configuration follows the ones in the doc:

``` java
   @PATCH
   @Path("/books/{id}")
   @Consumes("application/json")
   public void updateTitle(
           @Auth User user,
           @PathParam("id") String bookId, BookBean bookBean) {

   }
```

the application configuration

``` java
 environment.jersey().register(AuthFactory.binder(
              new BasicAuthFactory<>(
                      new UserBasicAuthenticator(configuration.getAuthenticationConfiguration().getUser(),
                              configuration.getAuthenticationConfiguration().getPassword()),
                      "SECURITY REALM",
                      User.class)));

```

and UserBasicAuthenticator is

``` java

...
 public Optional<User> authenticate(BasicCredentials credentials)
            throws AuthenticationException {
        if (password.equals(credentials.getPassword())
                && user.equals(credentials.getUsername())) {
            return Optional.of(new User(credentials.getUsername()));
        } else {
            return Optional.absent();
        }
    }
...

```

**Comment by akhaidem** [comment]
I am having the exact same issue.Initially I thought, it must be due to some registration but I have checked, and it looks okay to me. Any body who can give any pointer will be great! Thanks!

**Comment by mnrasul** [comment]
I am working off the master branch. I have the following two additional lines. Could you possibly be missing the second line? I am not sure if `RolesAllowedDynamicFeature` is present in 0.8 or not, so included it, as I am using it. 

```      
environment.jersey().register(RolesAllowedDynamicFeature.class);
environment.jersey().register(new AuthValueFactoryProvider.Binder(User.class));
```

**Comment by jplock** [comment]
What happens when you put a `@Valid` in front of `BookBean bookBean` in your resource method, like:

```java
@PATCH
@Path("/books/{id}")
@Consumes("application/json")
public void updateTitle(@Auth User user, @PathParam("id") String bookId, @Valid BookBean bookBean) {
}
```

**Comment by arteam** [comment]
Could you try against Dropwizard 0.8.5? Dropwizard 0.9.1 drastically changed auth staff, so this issue
is probably not relevant.

**Comment by ivanjeukens** [comment]
I am using 0.9.1 and have the exact same problem. 

`@POST
public Response addOrcamento(@Auth User user, OrcamentoRepresentation orc) {
...
}`

and on run

`environment.jersey().register(
				new AuthDynamicFeature(new BasicCredentialAuthFilter.Builder<User>()
						.setAuthenticator(new DefaultAuthenticator())
						.setRealm("SEC REALM")
						.buildAuthFilter()));		
		
		environment.jersey().register(new AuthValueFactoryProvider.Binder<>(User.class));`

**Comment by psamsotha** [comment]
For any future readers, here is the reason for the error.

When Jersey starts up, it builds a model of all the resources. In the model includes all the parameters. The Jersey validates the model. It does this to benefit us, by making sure that the all the models can be processed correctly during a request. Part of the validation process consists of validating the parameters. There are some rules that guide what parameters we can have. For instance we can only have one entity body parameters (excluding things like @FormParam and @FormDataParam). The entity parameter is generally the parameter with no annotation.

The way the validation works for parameters is that it for each parameter, Jersey traverses all the `ValueFactoryProvider`s and it passes the `Parameter` (which is a model of the actual parameter) to the `ValueFactoryProvider`, and expects a `Factory` to be returned. If a `Factory` is not returned from one `ValueFactoryProvider`, then it goes on to the next until either a `Factory` is returned, or all the `ValueFactoryProvider`s have been checked and no `Factory` has been returned by any of them. In which case Jersey throws a `ModelValidationException`, as there is no `ValueFactoryProvider` to handle that parameter.

That being said when traversing the parameters, Jersey give one pass for a single entity parameter. So for the error to occur in an example such as

```java
@POST
public Response addOrcamento(@Auth User user, OrcamentoRepresentation orc) {
...
}
```

one of those parameter passes are failing. The `OrcamentoRepresentation` parameter will be given the entity parameter pass, but the `User` fails as there is no `ValueFactoryProvider` that returns a `Factory` for that parameter.

But the thing is, the `AuthValueFactoryProvider` is the component that provides the value for the `@Auth User` parameter. You can see [here in the source](https://github.com/dropwizard/dropwizard/blob/v0.9.2/dropwizard-auth/src/main/java/io/dropwizard/auth/AuthValueFactoryProvider.java#L55), where it actually returns the `Factory`. The only thing that could cause it to fail is if the following condition were to fail

```java
!principalClass.equals(parameter.getRawType())
```
But it _shouldn't fail_, as the `principalClass` is obtained through our [passing the class to the `AuthValueFactoryProvider.Binder<>(User.class);`](https://github.com/dropwizard/dropwizard/blob/v0.9.2/dropwizard-auth/src/main/java/io/dropwizard/auth/AuthValueFactoryProvider.java#L104). As long as the `principalClass` and the actual parameter class are the same, the condition should pass.

@ivanjeukens I've tested with your exact configuration with 0.9.2, and it works fine. Maybe a clean and build. Or maybe the problem is somewhere else. I don't know. But I hope I gave you some idea of what the problem is.

**Comment by earzur** [comment]
thank you @psamsotha, very helpful !

**Comment by nishantshobhit** [comment]
@earzur @ivanjeukens did you guys manage to solve this problem?

**Comment by roblittle** [comment]
I had a similar issue, when updating an DW API from 0.7.1 to 0.9.2 (with oauth2 auth, and almost 300 unit tests, about 1/2 of which tested various resource endpoint POST/PUTs, which - revealed this same issue described above.

My Application.java had the environment.jersey().register() ofr the new AuthValueFactoryProvider and the newDynamicFeature hooks, both with the proper token object.  

However - because my API worked when compiled with -DskipTest=true, and my issue was just in programatic execution of unit tests... i dug deeper into my ClassRule annotation in my resouce tests. 

That was where i was only registering the AuthDynamicFeature and NOT the AuthValueFactoryProvider.  

I added the registeration to the ClassRule for each unit test, and i was back to all tests passing.

**Comment by mdeanda** [comment]
I ran into a similar issue simply importing the wrong annotation:

import javax.websocket.server.PathParam;
import javax.ws.rs.PathParam;

It may not be the case for you but I lost a few days on it.

**Comment by bhavneet91** [comment]
@mdeanda Thanks your comment helped!
