### ISSUE TITLE
Unable to log after RULE.getApplication().run("db", "migrate", CONFIG_PATH);

### ISSUE THREAD

**Issue by joaocenoura** [dropwizard/dropwizard#1119]
I'm unable see any logs after calling `RULE.getApplication().run("db", "migrate", CONFIG_PATH);`. Take the following example:  
If I add some loggers to `com.example.helloworld.IntegrationTest.migrateDb()`:

```
    @BeforeClass
    public static void migrateDb() throws Exception {
        LoggerFactory.getLogger(IntegrationTest.class).warn("now you see me");
        RULE.getApplication().run("db", "migrate", CONFIG_PATH);
        LoggerFactory.getLogger(IntegrationTest.class).warn("now you don't");
        System.out.println("+++++++++ just a control line +++++++++");
    }
```

I'll get the following output:

```
WARN  [2015-06-19 09:31:53,676] com.example.helloworld.IntegrationTest: now you see me
INFO  [2015-06-19 09:31:54,767] liquibase: Successfully acquired change log lock
INFO  [2015-06-19 09:31:55,964] liquibase: Creating database history table with name: PUBLIC.DATABASECHANGELOG
INFO  [2015-06-19 09:31:55,969] liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO  [2015-06-19 09:31:55,983] liquibase: migrations.xml: 1::codahale: Table people created
INFO  [2015-06-19 09:31:55,983] liquibase: migrations.xml: 1::codahale: ChangeSet migrations.xml::1::codahale ran successfully in 6ms
INFO  [2015-06-19 09:31:56,114] liquibase: Successfully released change log lock
+++++++++ just a control line +++++++++
```

After that I can't see any logs from slf4j (from the test class, applications class etc). I've tried to change logging settings in `test-example.yml` but without success.  
I'm using maven 3.0.5 and openjdk 1.7.0_79.

**Comment by joaocenoura** [comment]
Sorry, just had the opportunity to dig deeper just now.  
The problem seems to be in `io.dropwizard.logging.DefaultLoggingFactory`, particularly in:
```
private Logger configureLevels() {
        final Logger root = loggerContext.getLogger(org.slf4j.Logger.ROOT_LOGGER_NAME);
        loggerContext.reset();
        ...
}
```
and also in `io.dropwizard.cli.ConfiguredCommand`
```
protected void cleanup() {
    if (configuration != null) {
        configuration.getLoggingFactory().stop();
    }
}
```
If I comment `loggerContext.reset();` and `configuration.getLoggingFactory().stop();` `RULE.getApplication()` loggers will be merged with IntegrationTest loggers and works as supposed.

Would be really nice to add a feature that would keep logger settings, something like passing a flag in `RULE.getApplication().run(...)` or providing a variable in the `test-example.yml` to preserve loggers.

**Comment by amdw** [comment]
I hit this problem also, and lost quite a bit of time trying to work out why logging wasn't working as expected.

One way to work around it is to call the configure() method on the LoggingFactory again immediately after the run("db", "migrate", ...) call. This puts the appenders back so logging starts working again:

```
    @BeforeClass
    public static void migrateDb() throws Exception {
        RULE.getApplication().run("db", "migrate", CONFIG_PATH);
        RULE.getConfiguration().getLoggingFactory().configure(RULE.getEnvironment().metrics(), RULE.getApplication().getName());
        LoggerFactory.getLogger(IntegrationTest.class).info("Try it now! *****");
    }
```

When I do indeed see that message in the output:

```
INFO  [2016-10-20 14:19:17,896] com.example.helloworld.IntegrationTest: Try it now! *****
```

One thing we could do is add this configure() line to the IntegrationTest in dropwizard-example, so that at least people who use that test as a model for their own don't also lose time puzzling over this. However this is obviously not an ideal fix.

The root cause of the problem is that there seems to be an assumption in the command run() methods that once they exit, the process will also exit. (Otherwise, what could justify stop()ping the LoggingFactory in ConfiguredCommand.cleanup() as @joaocenoura pointed out?)

Either:

1. This assumption is valid, in which case the example IntegrationTest should not call run("db", "migrate", ...) to set up the database schema before the test, and should do it some other way instead (perhaps just adding a run() flag as @joaocenoura suggested), or
2. The assumption is invalid, in which case ConfiguredCommand should not stop() the LoggingFactory in the way it does now.

I'm fairly inexperienced with DropWizard, so it would be great if someone in a position to do so could say what sort of PR is likely to be accepted to address this, if any.

**Comment by nickbabcock** [comment]
So I can reproduce this in an app I have, but I can't seem to reduce to a minimal test case that we can include in our integration test module (`dropwizard-e2e`). I've [attempted it here](https://gist.github.com/nickbabcock/b932eae49d7e45b42fb872cc6c13cca8), but I can't get the tests to fail 😭 

If anyone has a minimal app that uses `ConfiguredCommand` and sees this problem, I'd appreciate it if I could see it!

**Comment by amdw** [comment]
@nickbabcock - thanks very much for looking at this.

Unfortunately it's not at all easy to test DropWizard logging, because the DefaultLoggingFactory wraps all configured appenders in async appenders, so my initial attempts suffered from nondeterministic interleaving of the test assertions and the async appender flushing. (I don't know whether that was the problem with your attempt.)

I did put together the following:

https://github.com/amdw/dropwizard/commit/8452c2f787e7e70e7dd021b5026be44c46d41670

This relies on a Thread.sleep() to try to make sure the async appender gets flushed before the assertions run, so it is not really committable as-is, but it does reproduce the behaviour reliably for me.

To do this properly, I think it would be necessary for the test app configuration to specify some alternative to DefaultLoggingFactory which makes the appenders synchronous so that the logging behaviour can be tested deterministically.

I hope this helps.
