### ISSUE TITLE
Update docs & release notes to support v0.9.0

### ISSUE THREAD

**Issue by carlo-rtr** [dropwizard/dropwizard#1120]

**Comment by Rsgm** [comment]
I noticed on http://dropwizard.github.io/dropwizard/0.9.0-SNAPSHOT/docs/manual/auth.html, that the oauth2 configuration sets prefix `SUPER SECRET STUFF`. The previous configuration for basic auth sets the realm to `SUPER SECRET STUFF`.

The oauth2 prefix configuration should be included, and set to `Bearer`.  
Prefix defaults to `Basic`, but it would be a good idea to set the prefix on basic auth documentation. At the very least this would help understand it is being set and used for basic auth as well.

It is also worth noting that `@RolesAllowed` may be set on types, but Dropwizard auth only looks for `@RolesAllowed` on methods.

**Comment by carlo-rtr** [comment]
Thanks for the heads up. I have a PR updating the prefix to "Bearer" on OAuth. Line 177 states that @RolesAllowed needs to be applied to the Resource Method. Btw, I don't see any documentation not setting the prefix explicitly.

https://github.com/dropwizard/dropwizard/blame/5fae06923065c10fc923714000f1404e61251a30/docs/source/manual/auth.rst

**Comment by carlo-rtr** [comment]
after c6ff096924866fc02eba7797a9090ec59fdfae0f is merged, what remains is updating https://github.com/dropwizard/dropwizard/tree/gh-pages with v0.9.0

**Comment by joschi** [comment]
@dropwizard/committers I'd like to remove the Dropwizard docs in the root directory of the `gh-pages` branch and create an `index.html` file which redirects to the latest release instead.

This way people see the latest documentation in a versioned way (e. g. http://www.dropwizard.io/0.9.0/docs/index.html instead of http://www.dropwizard.io/docs/index.html) and won't accidentally see the documentation of a more recent release. The downside is, that some old URLs won't work anymore.

Any opinions?

**Comment by jplock** [comment]
Whoops, didn't mean to close this out yet.  That may break all of our google links and whatnot, but generally seems like a good path forward.

**Comment by arteam** [comment]
Looks good for me. Many software vendors do it so (Spring, PostgreSQL, InfluxDB, etc...)
