### ISSUE TITLE
Upgrade to Jersey 2.18

### ISSUE THREAD

**Issue by krutsko** [dropwizard/dropwizard#1138]
Hello

We are using dropwizard 0.8.1 which rely in Jersey 2.17 (org.glassfish.jersey.core:jersey-client:jar:2.17).
Jersey 2.17 has a known major issue https://java.net/jira/browse/JERSEY-2786 fixed in 2.18, 
but we can't update this dependency directly, cause it's a breaking change and migration is needed. https://jersey.java.net/documentation/latest/migration.html

Please consider the upgrade to jersey 2.18
Thanks

**Comment by arteam** [comment]
Current master is already updated to 2.18. See #1109. 
We plan to release 0.9.0 in first weeks of July.

**Comment by pparth** [comment]
@arteam I do not think the release plan for this, is acceptable. This is a memory leak issue in one of the most core components of Dropwizard, Jersey, whose maintainers categorised it as Critical. Waiting for months until 0.9.X version with the fix is out, shows that you do not handle Dropwizard latest version as a production-worthy framework. We are trying to switch from 0.6.2 to 0.8.x for many months now, waiting for major fixes to be applied and now we need to wait for 0.9.x, with whatever that means in terms of backward compatibility etc!

**Comment by arteam** [comment]
@pparth, you have a point. But it's worth to mention that if some issues are critical for your organization, you can always make a fork, apply needed changes by hand, and maintain the fork independently from the main repository. Our primary goal is development of the latest version and we don't really have a plan for porting updates for older versions. However, we are happy to make maintenance releases for critical bugs or security updates, if it's needed. The best option to let it happen is to drop a message to the _dropwizard-dev_ mailing list with a proposal of the changes you want to see backported.

**Comment by arteam** [comment]
@dropwizard/committers What do you think about making 0.8.2 release with backported #1109 and #1137?

**Comment by pparth** [comment]
@arteam I do not understand the notion of "our goal is just to develop" without trying to offer even a very small number of versions that are production-worthy. We are using version 0.6.2 in hundreds of micro-services of a large company and i can assure you it is production-worthy. We do not care about using latest versions of Jetty, Jersey etc., obviously, by staying at this version, as it is rather old. But it is *stable*. Since then, there is no other production-worthy versions. The ship has sailed for 0.7.x long ago (i do not even get why you do not mention this in its documentation...) and now you are telling me that 0.8.x is going to have the same fate too! 
I get that we can fork and everything but i am really confused: don't you have the need to say to people that you actually maintain a version X that IS battle-tested and they can use it without any major issues until version Z is prepared?

**Comment by jplock** [comment]
@arteam I'm fine with releasing 0.8.2 with those two fixes (and any other bugs we want to address), and save everything else for 0.9.0

**Comment by ryankennedy** [comment]
@arteam I'm also fine with an 0.8.2 release with those fixes.

@pparth "Waiting for months until 0.9.X version with the fix is out, shows that you do not handle Dropwizard latest version as a production-worthy framework. We are trying to switch from 0.6.2 to 0.8.x for many months now, waiting for major fixes to be applied and now we need to wait for 0.9.x, with whatever that means in terms of backward compatibility etc!"

First, please mind your tone (implied by the exclamation points).

Second, I think your date math is a bit off. You posted this on June 27th, mere days away from July. @arteam already indicated that 0.9.0 was coming in the early weeks of July, which is hardly months away.

Lastly, understand that Dropwizard is maintained by volunteers. There are no companies explicitly making money or time available to this project with the possible exception of Rent the Runway, which is (I believe) paying some of our hosting fees. For the employee of a company making $1B+ in revenue per year to make angry demands of volunteer staff seems ridiculous. Please try having a bit more respect and understanding for the people you're talking to.

**Comment by b** [comment]
@pparth I've not had problems in production with 0.8, but if I did I would either produce fixes myself or file issues for them and say kind and encouraging things to the DW team. I for one would welcome pull requests from you fixing the many problems you have with 0.8.x so that the entire community might benefit. Open source should not be a one way street.

**Comment by cowtowncoder** [comment]
FWIW, 0.9.0-rc1 seems to contain upgraded Jersey 2.18, and being available via Maven Central should be possible to use before official final 0.9.0, and appears to be solid enough for actual usage.

**Comment by pparth** [comment]
@ryankennedy @b I have the outmost respect for the work you are doing regarding Dropwizard and if i gave you a different impression then this is my fault and i am truly sorry. I know that you perform work for free, trying to maintain an excellent framework and no-one should be disrespectful to you. My *tone* had to do with *confusion* though and not with *anger* that you do not do your work properly. 
I am confused because version 0.6.2 is a perfect example of what you describe in Overview: *Its goal is to provide performant, reliable implementations of everything a production-ready web application needs. Because this functionality is extracted into a reusable library, your application remains lean and focused, reducing both time-to-market and maintenance burdens.* but later versions seem to miss the point, in my opinion. @codahale was really focused on this initial description about Dropwizard and he was very adamant about Dropwizard being heavily opinionated in order to be a lean, mean, well-oiled machine used in really demanding, high traffic, production systems of companies like Yammer (and Upwork for that matter). The statement in "The Next Steps" section saying that *You’ve got a Hello World application ready for production that’s capable of doing 30,000-50,000 requests per second* is actually from this era and denotes exactly that: you do not expect this kind of traffic for a web service operating in a simple enterprise application. 
Now, i assume that this, initial focus for the project, stays true. If the focus is switched to Dropwizard being a theoretical, academic work that it should not be judged by anyone, that the maintainers do not care in what environments it is used and big companies are especially banned, just let me know so that we can decide what route to follow from now on. Obviously, this has nothing to do with maintaining our own fork, producing fixes with PRs etc. It is about where this thing is headed to.
So, based on my assumptions, 0.7.x is unusable. I really do not understand why it is still documented and mentioned as a release that someone can actually choose to use it. ). 0.8.0 is surely much better but it has a lot of missing functionality, especially regarding Jersey, in compare to 0.6.2. Jersey Client was riddled with configuration issues. Jersey in general was still very unstable with lots of critical bugs. 0.8.1 seems to do the trick and be a strong base to strengthen the product and build on it. 
But if you handle https://java.net/jira/browse/JERSEY-2786 which is a Critical memory leak bug, as something that can wait for months to find its way to Dropwizard (the issue was resolved last March and even if you do not want to fork Jersey on your own (???), 2.18 was out on the 5th of June. Assuming that you are going for a 0.9.0 RC in a few weeks, IT IS going to be months until the fix is present in a stable 0.9.x version and i am pretty sure that you are not going to continue maintaining the 0.8.x line), my assumptions are wrong.

**Comment by ryankennedy** [comment]
I'm going to give you the benefit of the doubt and assume that there may be a language barrier that's preventing me from reading your tone/intent correctly. If English isn't your first language, then understand that your English isn't conveying the "respect" you refer to.

"So, based on my assumptions, 0.7.x is unusable. I really do not understand why it is still documented and mentioned as a release that someone can actually choose to use it."

Companies are using 0.7.x in production today. I believe this is the first time JERSEY-2786 has been brought up within the Dropwizard community (I could be wrong, however). It probably has to do with the fact that it appears to be an issue in Jersey Client, which not everyone is using. If you're only using dropwizard-core but not dropwizard-client then your chances of running into this leak appear to be roughly zero.

"If the focus is switched to Dropwizard being a theoretical, academic work that it should not be judged by anyone, that the maintainers do not care in what environments it is used and big companies are especially banned, just let me know so that we can decide what route to follow from now on."

You seem to be inferring quite a lot, especially with regard to the degree to which maintainers "care". Several maintainers (sadly, this doesn't include me at the moment) are putting in many of their own personal hours on this project. That's a pretty high degree of "care".

On the flip side, many companies (including Yammer, where Dropwizard originated) are using Dropwizard to power their multi-[million|billion] dollar companies without contributing much of anything back. If anyone should be judged, it's them. Especially when they show up in our community indignant over our state of library upgrades.

Yes, the documentation says "production ready out of the box." Yes, we appear to have an unfortunate memory leak in the dependencies of one of the modules in the latest release version. If you have a problem with that I have some possible solutions for you:

1) Roll up your sleeves and give us a hand.
2) Convince Upwork to pay for a part/full-time contributor.
3) Sit patiently on 0.6.x until 0.9.x is ready.
4) Fork the project.
5) Go someplace else.

If you're going to roll in here spouting "back when Coda ran this show…", I'm going to quickly shush you and point you towards the door.

Coda is gone.

The community is doing the best it can.

I'm not at all sorry that this free open source project isn't meeting the expectations of a multi-billion dollar company that contributes nothing to it. Give us a hand, lower your expectations, or go someplace else.

**Comment by pparth** [comment]
I may have the benefit of the doubt because English is not my native language, but there is no doubt about your tone when you continuously say to me "shut up and go someplace else". Nevertheless, i still say that i have a lot of respect to this project and to your work and that i am just judging where this project seems to be heading to, which apparently is something that i should not do because *Coda Hale is not here now and all you capitalist employees in your big-time companies, should not talk at all and just go to hell*. You are so biased, that i am not going to argue more about this. 

We have contributed to this project in numerous ways. In code too, (i am not the only person working on this) but not as much as we or the community could benefit from, indeed. But code is not the only form of contribution you should care about. We contributed in providing our valuable comments for various issues either here or in Google groups, both for Dropwizard and also for Metrics. 

We also offer another form of contribution which the community should be very interested in: battle testing Dropwizard in very demanding, high-traffic, production, web services. We are the ones that are taking the major risk of hardening this framework by using it in production. And when a component hicks up even for a few seconds, thousands of requests may go bad. Most of the well-hidden bugs arise in such environments. And we are the ones, naturally, to take the hit. You will never find these in 1rqs/sec traffic. Most things work perfect in such an environment.

We are the ones that give momentum to the fame of this project. Endorsement by major companies is what made Dropwizard known to people out there. We would never use it if Yammer was not behind it back then. Hundreds of Stars are due to people working in these companies. And when the time comes for community members to score a job somewhere, by mentioning that they contribute to the Dropwizard project, they will make it because they will say that Dropwizard is used by Yammer and Upwork and not because @ryankennedy says so.

**Comment by joschi** [comment]
To get the issue back on track, I'm also for releasing a version 0.8.2 with the mentioned fixes for Jersey as they should basically be cherry-pickable. I would try to keep the changes in 0.8.2 to a bare minimum because we should focus on getting Dropwizard 0.9.0 out of the door.

@pparth Great that you're using Dropwizard! Feel free to join the [developers mailing list](https://groups.google.com/forum/#!forum/dropwizard-dev) and discuss the project roadmap and the findings in your environment with the Dropwizard contributors. This issue is not the right place for it.

@ryankennedy @pparth I hope that this linguistic misunderstanding didn't make both of you bitter and that we can still have a constructive discussion on the developers mailing list.

I'm closing this issue now (still open for comments) as the upgrade to Jersey 2.19 has already been merged in #1143.

**Comment by pparth** [comment]
Thanks @joschi for considering adding these critical Jersey fixes to the 0.8.x line. I really hope that other critical issues we may find in the near future, find their way into 0.8.x without us having to move forward to 0.9.x.

**Comment by joschi** [comment]
@pparth If you've just started migrating, I'd recommend going for Dropwizard 0.9.x instead of using Dropwizard 0.8.x. You can also take over maintenance over the 0.8.x branch, if it's crucial to your operations.

**Comment by pparth** [comment]
Got it.
Can you point me to the major changes in 0.9.x comparing to 0.8.x?

**Comment by joschi** [comment]
@pparth We try to keep the release notes up to date (but no guarantee that they're complete, sorry): https://github.com/dropwizard/dropwizard/blob/master/docs/source/about/release-notes.rst

**Comment by pparth** [comment]
Sorry for misunderstanding. I was asking about the major points that made you consider moving to a 0.9.x line of code. What were the reasons you did not apply the changes in the release notes to 0.8.x line? Some architectural issues that break things?

**Comment by nickbabcock** [comment]
I believe the only breaking change in 0.9 is #952, which updates how authorization is accomplished (fixes issue #768). I believe the [latest documentation](http://dropwizard.github.io/dropwizard/0.9.0-SNAPSHOT/docs/manual/auth.html) has more details.

**Comment by cowtowncoder** [comment]
At the risk of beating a dead horse...

@pparth "We are the ones that give momentum to the fame of this project. Endorsement by major companies is what made Dropwizard known to people out there... Hundreds of Stars are due to people working in these companies"

Why do you think that contributors of DropWizard are driven by some deep need to be popular? 
Do you think you and other people using, deporting it, should be perhaps given a medal, or songs praised extolling your virtues? I do not get this. I have made minor contributions only, and can say that the reason I give back is based on two main things:

1. Benefit of getting the fixes, improvements integrated TO REDUCE MY OWN MAINTENANCE needs, and
2. As a minor thank you note for all the value I have gotten, am getting and will get out of this project

Your attitude seems to be along lines of "YOU should be grateful for ME for using your stuff, making it popular". That attitude is very arrogant, and I hope that is not what you intend to convey.
No one owes you (or other users) anything for your "implicit endorsement"; and I highly doubt that you or anyone else has started using DropWizard for purpose of marketing it.

Further, it did definitely sound like you were _demanding_ things that you assume should be provided, without offering to -- for example -- help in that happening. That is a certain way to sour OSS relationships.

The sad part here is that I actually think that parts of what you are asking for are things that we as a community could consider and work towards. For example, creating maintenance branches for purpose of targeted backported fixes, is a reasonable idea. Especially if offering help with managing such branches or releases.
It's just that starting with demands, backed by allegations of incompetence and/or ungratefulness ("we made you popular -- now you don't even support old version I am using!"), is not a way to get anything positive going.

Apologies for continuing the debate beyond its natural end, but this is one area that is close to my heart, as both OSS author and user.

**Comment by saadmufti** [comment]
+1

**Comment by joschi** [comment]
I'm locking this issue now. Everyone has made their point. Please continue on the developer mailing list if you feel that there's more to discuss.
