### ISSUE TITLE
dropwizard-jetty's BiDiGzipFilter is no longer compatible with Jetty 9.3+

### ISSUE THREAD

**Issue by joakime** [dropwizard/dropwizard#1147]
Jetty 8 deprecated non-async versions of GzipFilter.

Jetty 9.3 has completely gutted the Filter based Gzip handling in favor of a more fundamental GzipHandler inserted at the Server level (before the webapp).

However, this has rendered the existing BiDiGzipFilter as useless.
See https://bugs.eclipse.org/471577 on Jetty side

**Comment by joschi** [comment]
Dropwizard is still using Jetty 9.2.x, so this is kind of a non-issue for us right now.

I'll leave the issue open to serve as a reminder once we upgrade to Jetty 9.3.x (probably post  Dropwizard 0.9.x because [Jetty 9.3.x requires Java 8](https://webtide.com/jetty-9-3-features/)).

Refs #1036.

**Comment by gregw** [comment]
Gzip handling has been moved to a new interceptor architecture so that it works correctly with all async IO modes.

There is no similar interceptor yet on the input side.

I'll look at making this interception point in the near future, but it would be good to have somebody from the dropwizard team to collaborate with when creating a gzip input handler

**Comment by jplock** [comment]
Can this be closed in favor of #1330 ?

**Comment by arteam** [comment]
Yes. #1130 migrated `BiDiGzipFilter` to `BiDiGzipHandler`.
