### ISSUE TITLE
Http Client Connection Pool Error

### ISSUE THREAD

**Issue by ruimateus** [dropwizard/dropwizard#1160]
Hi,
I have a series of Tasks that connect to multiple targets that have an hourly cronjob running them.

The multiple tasks are using the same JerseyClient instance from JerseyClientConfiguration.

After a while, I start getting **javax.ws.rs.ProcessingException: java.lang.IllegalStateException: Connection pool shut down**

The only way to recover is restarting the application.

This only started to occur in Dropwizard 0.8.2.

Thanks for any help!

**Comment by ruimateus** [comment]
After further investigation, it seems that InstrumentedHttpClientConnectionManager shuts down the pool for an unknown reason:

DEBUG [2015-07-11 14:12:44,652] org.apache.http.impl.conn.HttpClientConnectionOperator: Connecting to ****/****
DEBUG [2015-07-11 14:12:44,652] org.apache.http.impl.execchain.MainClientExec: Connection discarded
DEBUG [2015-07-11 14:12:44,652] org.apache.http.impl.conn.DefaultManagedHttpClientConnection: http-outgoing-6409: Close connection
DEBUG [2015-07-11 14:12:44,652] com.codahale.metrics.httpclient.InstrumentedHttpClientConnectionManager: Connection released: [id: 6409][route: {s}->****:443][total kept alive: 0; route allocated: 7 of 1024; total allocated: 21 of 1024]
DEBUG [2015-07-11 14:12:44,653] com.codahale.metrics.httpclient.InstrumentedHttpClientConnectionManager: Connection manager is shutting down

After this point, any HttpClient call, returns an exception ***java.lang.IllegalStateException: Connection pool shut down***

PoolingHttpClientConnectionManager shuts down on close() and finalize() method.

When does Dropwizard closes the CloseableHttpClient?

Thanks

**Comment by mikeycmccarthy** [comment]
This also affected us - we had to rollback to 0.8.1.

**Comment by nickbabcock** [comment]
I tried to reproduce the issue locally and couldn't get the behavior seen. Does anyone have a gist or repo demonstrating the bug?

**Comment by carlo-rtr** [comment]
This probably not very helpful, but I figured I would list the places I believe close could be called:

* Jetty shuts down
* ``InstrumentedHttpClientConnectionManager`` gets garbage collected and ``finalize`` is triggered
* ``DropwizardApacheConnector#close``
* One thread calls close on the Client

**Comment by carlo-rtr** [comment]
Maybe this should be true?

https://jersey.java.net/apidocs/2.19/jersey/org/glassfish/jersey/apache/connector/ApacheClientProperties.html#CONNECTION_MANAGER_SHARED

**Comment by nickbabcock** [comment]
I believe you are correct (especially because the default is `false`):

- [Jersey issue](https://java.net/jira/browse/JERSEY-2867) on Apache HTTP client connection manager sharing 
- [Jersey commit](https://github.com/jersey/jersey/commit/80c8c7013c52ddf9012932676d1048c79133d0f2) that adds the `CONNECTION_MANAGER_SHARED`

**Comment by carlo-rtr** [comment]
hotness

**Comment by arteam** [comment]
I don't think that's relevant.

The problem described in the Jersey issue is applied only for cases, when user provides own connection manager that's shared between clients. We don't provide such ability,
because we create a new connection manager every time user creates a new instance through JerseyClientBuilder. Moreover, the current fix leaks InstrumentedHttpClientConnectionManager, which will be closed only during a major GC, a highly unpredictable event. It's really easy to end up with a couple of hundred open TCP connections to a remote server.

I think, we should revert connection manager sharing or at least disable it by default.

**Comment by carlo-rtr** [comment]
Okay, I've reverted. Do you have any idea what's causing the issue?

**Comment by arteam** [comment]
I would go with reviewing the changes in Jersey between 2.17 and 2.19, if the issue is reproduced only in 0.8.2. But I have a gut feeling that the issue is connected to the finalizer in some way.

**Comment by krutsko** [comment]
@arteam We faced the same issue with dropwizard 0.8.2. 
I noticed, that finalizer was added into ClientRuntime of Jersey 2.18. https://github.com/jersey/jersey/blob/4eece8eeb3947becdf91188a63412b5011eae2b5/core-client/src/main/java/org/glassfish/jersey/client/ClientRuntime.java#L297 which close() the connector. 
Then, underlying apache client 4.4.1 http://grepcode.com/file/repo1.maven.org/maven2/org.apache.httpcomponents/httpclient/4.4.1/org/apache/http/impl/client/HttpClientBuilder.java#1184 close() the connection manager, cause it's not shared by default. 
So, the patch provided by @carlo-rtr seems valid to me. What do you think, guys?
