### ISSUE TITLE
Allow decoupling of dropwizard and joda-time

### ISSUE THREAD

**Issue by edenman** [dropwizard/dropwizard#1170]
I'm starting a new dropwizard project and would like to use the new java8 time library instead of joda-time.  I tried excluding joda-time from the dropwizard dependencies:

 `io.dropwizard:dropwizard-core` -> `io.dropwizard:dropwizard-util` -> `joda-time:joda-time` 
AND 
`io.dropwizard:dropwizard-core` ->  `io.dropwizard:dropwizard-jackson` -> `com.fasterxml.jackson.datatype:jackson-datatype-joda` -> `joda-time:joda-time`

...but I get CNFEs at runtime, becase `Bootstrap.java` calls `Jackson.newObjectMapper()` which has a hard dependency on `JodaModule` which depends on joda.  

Ideally I'd be able to specify my own `ObjectMapper` in the application so I can avoid that code path entirely, and safely be able to exclude joda-time.  Thoughts?  If I start down the path of making a PR to allow this, would it be accepted?

**Comment by arteam** [comment]
Take a look at #1112. Would it cover your use case? It's available only in unreleased 0.9.0, though.

**Comment by nickbabcock** [comment]
Can you use the [dropwizard-java8](https://github.com/dropwizard/dropwizard-java8)?

**Comment by edenman** [comment]
@nickbabcock I'm already using dropwizard-java8 (it's great!) but it doesn't solve this problem.

@arteam #1112 looks like it would _almost_ work.  Main issue is that I'd need to avoid that constructor call to `Jackson.newObjectMapper()` entirely (presumably by implementing a `ProvidesCustomObjectMapper` interface on the Application that's passed into Bootstrap's constructor).

**Comment by edenman** [comment]
@arteam does that approach sound ok?  Any preference on what that `ProvidesCustomObjectMapper` interface's name?  Once I get the go-ahead I don't mind writing up the PR.

**Comment by arteam** [comment]
Oh, I now see the issue. 

I think that changing `Application` it not a very good option, because then we will have two places where we can set a custom `ObjectMapper`, which is confusing. 

I'm more inclined to the idea of lazy loading of the mapper. We could mark the *objectMapper* field in `Bootstrap` as *volatile* and  load it on demand in the getter. In this case we will avoid `NoClassDefFoundError` if Joda-Time is not present in the classpath and will have one place, where users can provide a custom mapper. What do you think about this approach?

**Comment by joschi** [comment]
To be honest I'm not a big fan of decoupling Joda-Time (or any other of the "core" libraries) and Dropwizard.

The idea of Dropwizard is to have a fixed set of good libraries tightly integrated to simplify the creation of *opinionated* RESTful services. Adding abstraction layers around all core libraries (e. g. Joda-Time, Jersey, or Jetty) is a lot of work and frankly contradicts the "Dropwizard mantra".

**Comment by arteam** [comment]
I would concur, but actually we don't have a compile-time dependency on Joda-Time. We just import it for users' convenience and automatically configure JSON serialization/deserialization. Bearing in mind the fact that there is a viable alternative shipped with JDK 8, I think we should allow users not to import Joda-Time, if they don't want to.

**Comment by edenman** [comment]
If we're being opinionated, then maybe the answer to all of this is to just get rid of Joda-Time entirely in 2.0.  Force people to upgrade to java8 time (if the creator of Joda thinks the java8 stuff is better, [I believe him](http://blog.joda.org/2009/11/why-jsr-310-isn-joda-time_4941.html)).  Or at least remove the hard joda-time dependency and allow people to add the dependency themselves if they really really don't want to migrate?

**Comment by arteam** [comment]
That's actually is not a bad idea for 1.0 version, which will target Java 8.

**Comment by cowtowncoder** [comment]
My suggestion would be to improve configuration so that set of modules to register with Jackson would be determined dynamically from boostrapped `Configuration`.

That is: initialization of things would use a bare-bones Jackson `ObjectMapper`, with minimal set of modules (possibly none), to read in `Configuration` (and not sub-type specified by `Application`), ignoring unknown properties.

Based on core configuration information, bootstrap process would construct "full" `ObjectMapper`, allowing users to specify additional modules, and/or remove other ones.
It would also be possible, if so desired, to handle basic logging configuration and initialization at this point, just to improve troubleshooting (before logging is initialized, things are bit opaque). But very little else should occur at this point.
Fully configured mapper would then be used to re-bind the input configuration file; allowing use of all kinds of additional datatypes as per configuration.

This way it would be simple to change the set of datatype modules registered, as well as any other extensions; and do it fully declaratively. One can still do explicit changes above and beyond declarative stage; this would not change overridability.

One side-benefit of such separation is to make bootstrapping process even more stable: as useful as modules like `Afterburner` are, they also add potential breakage points.

I have hoped to work on this idea for a while, but unfortunately haven't had much time. I thought I'll mention it nonetheless in case anyone else found this interesting.

**Comment by jplock** [comment]
Is this still an issue in the current 1.0.0 code now that we've integrated `dropwizard-java8` into the core?  The usage of Joda Time is now optional.

**Comment by arteam** [comment]
True, but we still import Joda-Time and register its support as a Jackson module. In the end, we took a pragmatic approach and will support Joda-Time and JSR-310 simultaneously in 1.0.0. See #1365.

**Comment by jplock** [comment]
I'm going to close this out for now.
