### ISSUE TITLE
Sub-Resources Created With Locator Have No Metrics

### ISSUE THREAD

**Issue by gilbode** [dropwizard/dropwizard#1206]
See https://github.com/dropwizard/metrics/issues/825.  Current version of metrics used by dropwizard never includes metrics for subresources created using subresource locators.  Would be very nice to get a release of metrics w/ the fix & integrated into dropwizard.

**Comment by mtakaki** [comment]
This is my work around for this: I copied the class `com.codahale.metrics.jersey2.InstrumentedResourceMethodApplicationListener` to inside my project and the class loader will take it over the one from the metrics package. You can keep this until the fix is actually merged and added back to dropwizard.

BTW, that fix https://github.com/dropwizard/metrics/issues/825 didn't fix the issue for me and I sent another PR for it: https://github.com/dropwizard/metrics/pull/861 Feel free to grab that file from my PR. It's working for me and I have already deployed this fix to my environment.
