### ISSUE TITLE
Send Validation Errors with Property Name

### ISSUE THREAD

**Issue by jimmy100r** [dropwizard/dropwizard#1237]
As of now there is no way to map Resource properties to their corresponding validation methods. You can use annotation ValidationMethod, which will return a set with error messages, but there is no way to find the cause (propertyname) of the error. Validator has a method validateProperty (where you can pass the property name which can come from an added field in Validationmethod annotation), but JacksonMessageBodyProvider uses the validate method. 
The propertyPath field of the Violation is of no use, as it is substring of the method name, For example, if your validation method name is isValidName, the property path will be "validName".. It should be just name.

**Comment by jplock** [comment]
@nickbabcock has any of your validator improvement changes done anything to handle this issue?  Can we close this out?

**Comment by nickbabcock** [comment]
I'll have to double check, but what would the expected behavior be for when the `ValidationMethod` is used for cross field validation, where one or more of the fields used in the method could be the problem?

My changes to validations didn't break the error message when a `ValidationMethod` failed, but if we do want to change the message, we should do it sooner rather than later. Potentially the easiest solution would be to strictly take only the `message` on a `ValidationMethod`
