### ISSUE TITLE
@UnitOfWork usable outside of Jersey Resource classes

### ISSUE THREAD

**Issue by dotCipher** [dropwizard/dropwizard#1240]
I have a few use cases where I want to be able to use the slick transaction handling that `@UnitOfWork` provides within a backend service class that is not a Jersey resource.  As you may be aware, Spring has something similar to this  in the form of  [`@Transactional`](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/transaction.html#transaction-declarative-annotations).

There are Stack Overflow [answers](http://stackoverflow.com/questions/26411823/dropwizard-nested-transactions) to this problem where people have given the solution of manually wrapping your business logic transaction and there was also [blog post on using Hibernate DAOs within Dropwizard Tasks](http://spin.atomicobject.com/2015/02/03/dropwizard-hibernate-dao/).

I am simply asking if there is a __"best practice"__ way to abstract some basic transaction handling (like what `@UnitOfWork` does without having to manually wrap my business logic with transaction handling code.  If there is no functionality as part of Dropwizard, then this could be a chance to add it to the Hibernate Bundle.

**Comment by yiweig** [comment]
+1 for this issue, working with non-Jersey resource Hibernate DAOs and would like to just be able to attach `@UnitOfWork` (or something similar) to my methods to get the transaction handling.

**Comment by dotCipher** [comment]
Does anyone have thoughts on proper implementation?  I was thinking of employing an AOP framework like AspectJ, or even just doing something similar to the `HibernateBundle` where you just pass in the non-resource classes you want the transactions handled for.  Thoughts?

**Comment by dmitrygusev** [comment]
We're doing something similar with tapestry-ioc and Tapestry's @CommitAfter
in our backend/REST services:
https://github.com/satago/tapestry-jpa-transactions/

Tapestry-IoC is a lightweight tool that can do simple AOP.

We're not using it with Dropwizard though, but I see no reasons why they
can't be used together.

On Saturday, September 12, 2015, Cody Moore <notifications@github.com>
wrote:

> Does anyone have thoughts on proper implementation? I was thinking of
> employing an AOP framework like AspectJ, or even just doing something
> similar to the HibernateBundle where you just pass in the non-resource
> classes you want the transactions handled for. Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dropwizard/dropwizard/issues/1240#issuecomment-139808796>
> .
>


-- 
Dmitry Gusev

AnjLab Team
http://anjlab.com

**Comment by mcarrierastonish** [comment]
We're currently doing exactly what you are describing with aspectj. I'll see if I can open source it early next week.

**Comment by dotCipher** [comment]
I'd be fine with whatever works with the least overhead here.  Let me know what your implementation looks like when you have it open sourced and we can see what works best for Dropwizard.

**Comment by dotCipher** [comment]
@mcarrierastonish Any updates?

**Comment by mcarrierastonish** [comment]
@dotCipher We recently just got acquired and I'm having to work through the open-sourcing policies here, it may take some time before I can actually get this available.  Meanwhile you can take a look at https://github.com/mattcarrier/metrics-aspectj which is basically the same principals but just using codahale/metrics instead of the UnitOfWork annotation. If you have any questions feel free to message me.  Meanwhile I'll continue on trying to get this open-sourced.

**Comment by vvondra** [comment]
We're currently managing transactions manually like the SO answer suggest, but created a wrapper for it, which simply accepts a callback which should be executed in the transaction. It also handles nesting of transactions, since we decided to drop `@UnitOfWork` annotations and do everything on the service layer: https://gist.github.com/vvondra/1dbcd62306e40fa47294

**Comment by jplock** [comment]
Closing as #1361 was merged
