### ISSUE TITLE
Flaky test: io.dropwizard.cli.ServerCommandTest

### ISSUE THREAD

**Issue by joschi** [dropwizard/dropwizard#1303]
`ServerCommandTest` occasionally fails with a `ConcurrentModificationException`: [Travis CI log.txt](https://github.com/dropwizard/dropwizard/files/19422/ConcurrentModificationException-log.txt)

**Comment by fexbraun** [comment]
It's the ```CliTest```, isn't it?
It's failing due http://jira.qos.ch/browse/LOGBACK-397 which a Logback user reported in 2012 and wich is not fixed yet.

In ```io.dropwizard.logging.DefaultLoggingFactory.stop()``` Artem added a lock to avoid some CMEs, which is obviously not enough to workaround LOGBACK-397 completely. 

I would guess, that it could be hard to fix the root cause. It's not very elegant but an option would be to catch/log/ignore the CME in ```io.dropwizard.logging.DefaultLoggingFactory.stop()```. Question: Should we retry the call one time?

Other option would be not to touch any production code, but catch the exception in the test.

**Comment by patrox** [comment]
@joschi, @fexbraun that bug seems to have been fixed few days ago (according to the logback jira).

**Comment by patrox** [comment]
Bumping logback version to the one which includes the fix should address the issue

**Comment by nickbabcock** [comment]
Thanks @patrox for the reminder, 1869404 (upgrading to Logback 1.1.7) closes this
