### ISSUE TITLE
Bootstrap ObjectMapper not used in Jersey MessageBodyWriter

### ISSUE THREAD

**Issue by josephlbarnett** [dropwizard/dropwizard#1341]
Dropwizard's bootstrap object has an ObjectMapper in it that we've been trying to get to understand java8 datatypes (Optional / DateTime / etc).  Initially we thought the `dropwizard-java8` bundle would do this for us, as it's setting up bootstrap.getObjectMapper() with the appropriate jackson modules, and allows us to return Optional resources.  However, in order to return objects that contain Optionals it appears we need to do the following in our Application's run() method:

``` java
JacksonJaxbJsonProvider provider = new JacksonJaxbJsonProvider();
provider.setMapper(objectMapperWithAppropriateModules);
environment.jersey().register(provider); 
```

It feels like a bug in dropwizard the the boostrap ObjectMapper is not being used by the reflection-instantiated JacksonJaxbJsonProvider?  We're seeing this behavior with Dropwizard 0.9.1 and dropwizard-java8 0.9.0-1

**Comment by arteam** [comment]
It's actualy registered. See [here](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java#L482).

Could you provide a test case, when handling Java8 `Optional` values doesn't work?

**Comment by jbarnettwomply** [comment]
Hmm interesting, if I build a new standalone minimal project, it works properly.  Something in our actual application must be conflicting with the default dropwizard provider somehow?

**Comment by jbarnettwomply** [comment]
It appears that adding:
```
<dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-json-jackson</artifactId>
            <version>2.22.1</version>
</dependency>
```
as a dependency is what causes this to break

**Comment by jbarnettwomply** [comment]
https://github.com/jbarnettwomply/dropwizard-jersey-media-conflict displays the issue.  if the `jersey-media-json-jackson` dependency is removed, the test passes.  alternatively, if the `if (false)` is changed to `if (true)` in `Java8Application.java` in order to manually register a provider, the test passes.

**Comment by oillio** [comment]
I ran into this problem as well and I think I have tracked down the problem.  I am by no means an expert in the internals of Jersey, so this may not be completely accurate.

It looks like `jersey-media-json-jackson` automatically registers `org.glassfish.jersey.jackson.JacksonFeature` (via JacksonAutoDiscoverable).

It will register its own `FilteringJacksonJaxbJsonProvider` which appears to override the dropwizard `JacksonMessageBodyProvider`.

The new provider doesn't get its object mapper set and uses a default one, ignoring the mapper in the Environment.

First off, you may consider setting the `org.glassfish.jersey.internal.InternalProperties.JSON_FEATURE` property in Dropwizard.  This will ensure this (or any other) JSON feature doesn't stomp on the Dropwizard provider.
You may also want to do what the `FilteringJacksonJaxbJsonProvider` does and check the `JSON_FEATURE` property.  If it is set to some other value, do not register your own provider.  This would have made my life slightly easier.

If you want to support the option of entity filtering in Dropwizard, there doesn't look to be a clean fix.  We will need a provider that does both the JsonIgnore stuff currently in Dropwizard's custom provider and the functionality in `FilteringJacksonJaxbJsonProvider`.

I wrote a workaround to make this work in my project.  Maybe it will be helpful to others.  It isn't pretty, if anyone has any ideas on a better way to do this, let me know.
https://gist.github.com/oillio/1c1845059caf47527f94202bf14b2dca

I'm happy to write up the `JSON_FEATURE` functionality described above into a PR, and I can work on a solution to support the entity filtering functionality in DW, if there is interest.  Supporting entity filtering will probably require taking a dependency on `jersey-media-son-jackson`

**Comment by oillio** [comment]
Jersey rejected my request to allow inheriting: https://github.com/jersey/jersey/pull/221

Looking a little deeper, I am wondering why Dropwizard defines a `JacksonJaxbJsonProvider` at all?

It is currently being used to define the ObjectMapper to be used.  From what I understand, Jersey recommends this to be defined through an ObjectMapperProvider, such as in this example:  https://github.com/jersey/jersey/blob/2.23.1/examples/json-jackson/src/main/java/org/glassfish/jersey/examples/jackson/MyObjectMapperProvider.java

The provider is also adding support the `@JsonIgnoreType` annotation.  There may be another way to provide this as well.

I would be happy to dig deeper into the possibility of replacing `JacksonMessageBodyProvider` altogether, if this would be of interest.

**Comment by RobeEW** [comment]
FWIW, a work around is to turn auto discovery off:
`environment.jersey().property(CommonProperties.FEATURE_AUTO_DISCOVERY_DISABLE, Boolean.TRUE);`

This needs to be done for any jersey http clients you build, too:
```
new JerseyClientBuilder(environment)
            .withProperty(CommonProperties.FEATURE_AUTO_DISCOVERY_DISABLE, Boolean.TRUE)
            .build('main');
```

**Comment by lazee** [comment]
Thnx @RobeEW ! Really saved my day :)

**Comment by hoto** [comment]
We have a huge dropwizard project with lots of manually brought in modules and configs.
After adding [DocuSign SDK ](https://github.com/docusign/docusign-esign-java-client) to that project we've noticed some of our unrelated to DocuSign tests fail in weird ways.
Problem is that if a library brings in `jersey-media-json-jackson` it wrecks your existing jersey config.

Now the problem with setting `CommonProperties.FEATURE_AUTO_DISCOVERY_DISABLE` is that it seems to disable more than just the config brought in by `jersey-media-json-jackson` library.
It disables your own stuff as well.

We've managed to fix the issue by setting `InternalProperties.JSON_FEATURE` to `""` mentioned in this issue https://github.com/dropwizard/dropwizard/issues/2158 instead.
That flag is directly checked by the [JacksonFeature](https://github.com/eclipse-ee4j/jersey/blob/068b3b23aaaa4eed5a02dfe210f8e09922074e76/media/json-jackson/src/main/java/org/glassfish/jersey/jackson/JacksonFeature.java#L85) so the blast radius is much lower than setting the `FEATURE_AUTO_DISCOVERY_DISABLE`.

Be aware you need to set the `JSON_FEATURE` everywhere you create the jersey client which is very annoying as forgetting to do so results in unexpected test failures with no obvious explanation what's going on.

Seems like a lot of people complain about the `jersey-media-json-jackson` library.
Usually it's the scenario when someone brings in a 3rd party library (e.g. oauth, docusign etc) to their project and weird things start to happen out of nowhere.
It's very hard to figure out what's wrong and this issue is almost ungooglable.

So if possible stay away from `jersey-media-json-jackson` unless you start with a fresh project.

**Comment by hoto** [comment]
Another solution is to copy in the whole source code of `jersey-media-json-jackson` library into your classpath and remove the `JacksonAutoDiscoverable` (just in case). 
Just keep the package structure intact.
This will make the 3rd party library compile and execute no problem.
You may need to bring in some dependencies of `jersey-media-json-jackson` like `jersey-entity-filtering` to avoid copying that as well.

Not the best solution as you will need to update that manually for the rest of the project but it's the least invasive.

**Comment by hoto** [comment]
After some back and forth it looks like the best workaround is to shadow the `org.glassfish.jersey.jackson.internal.JacksonAutoDiscoverable` with an empty implementation.

So bring in the `jersey-media-json-jackson` and put an empty implementation of `org.glassfish.jersey.jackson.internal.JacksonAutoDiscoverable` on your classpath (somewhere in your project).

With a bit of luck that class will be picked up first and not the one from the library.

This seems to be the cleanest and easiest workaround we could find.
Unfortunately it's prone to stop working when there will be changes in the library like class renaming etc.
Hopefully your tests should start failing when such thing occur.
