### ISSUE TITLE
Unable to pass @Auth injected Principal into Sub-Resources

### ISSUE THREAD

**Issue by nate9** [dropwizard/dropwizard#1352]
Previously, in Dropwizard 0.8.x, we were able to inject and pass down the authenticated Principle throughout the entire path.

E.g.
```
@Path("/protected")
@Produces(MediaType.TEXT_PLAIN)
public class ProtectedResource {
    @GET
    public String showSecret(@Auth User user) {
        return String.format("Hey there, %s. You know the secret! %d", user.getName(), user.getId());
    }

    @RolesAllowed("ADMIN")
    @GET
    @Path("admin")
    public String showAdminSecret(@Auth User user) {
        return String.format("Hey there, %s. It looks like you are an admin. %d", user.getName(), user.getId());
    }
	
	@Path("sub")
	public ProtectedSubResource getSubResource(@Auth User user) {
		return new ProtectedSubResource(user);
	}
}
```

In Dropwizard 0.9.1, this does not seem to work. Stack trace indicates 
```
! java.lang.IllegalStateException: Cannot inject a custom principal into unauthenticated request
```

Are there any plans to implement a way to authenticating an entire resource? Can this be considered a regression?

I have also noticed that @PermitAll does not seem to apply to an entire resource, or it's subresources.

**Comment by edwardsb** [comment]
Did you add this to your jersey environement?

//If you want to use @Auth to inject a custom Principal type into your resource
    environment.jersey().register(new AuthValueFactoryProvider.Binder<>(User.class));

**Comment by nate9** [comment]
Yes, I am working off of the dropwizard examples. I simply edited it to use return a sub resource for testing.

**Comment by badunk** [comment]
I'm running into the same issue

**Comment by badunk** [comment]
@nate9 Actually its quite silly, I just realized it actually still works - just add the `Auth` annotation only to the subresource

**Comment by getconcar** [comment]
But sometimes you really want to check access in the root resources and not the subresources. I still think this is a regression from 0.8.x

**Comment by evnm** [comment]
@getconcar Can you give a concrete example of the deficiency you're identifying, please? It sounds like it may differ from this issue specifically, in which case we should file a separate one.

**Comment by getconcar** [comment]
We have the following structure 

/users/{user_id}/vehicles/{vehicle_id}
This is set up in two classes: UsersResource and VehiclesResource. /users/{user_id} returns the VehiclesResource. 

We would like to set up security in the UsersResource using @Auth so we can verify if the user has access to the specified user's vehicles. We need this because the user could have an admin role, and should have access to all users. Currently we have to check permission for this in the VehiclesResource class, which seems a bit odd. 

Also when we want to provide a /users/me endpoint, we have no access to the currently authenticated user.
