### ISSUE TITLE
Jersey Environment setUrlPattern no longer works

### ISSUE THREAD

**Issue by petey22uk** [dropwizard/dropwizard#1408]
Setting the url pattern via:

```java
environment.jersey().setUrlPattern("/example/*");
environment.jersey().getResourceConfig().setUrlPattern("/example/*");
```

won't actually set the url pattern, whereas amending the 'rootPath' config for the server block in the yml will. I've narrowed it down to this code here in AbstractServerFactory:

```java
jersey.setUrlPattern(jerseyRootPath);
String urlPattern = jerseyRootPath;
if (!urlPattern.endsWith("*") && !urlPattern.endsWith("/")) {
   urlPattern += "/";
}
if (!urlPattern.endsWith("*")) {
   urlPattern += "*";
}
jersey.setUrlPattern(urlPattern);
```

**Comment by jmcampanini** [comment]
i'm running into a similar situation. in short, i'd like to be able to configure this value in code rather than YAML, since it's not a run-time configurable option (i have frontend assets that depend on this prefix being present).

walking through the code, it seems that the `jersey.setUrlPattern` call works, it's just that the code in the application's `run()` block is ran BEFORE the code in `AbstractServerFactory`, and the `jersey.setUrlPattern` does a blind override. the priority of the value ends up being:

1. YAML configured `rootPath`
2. the field's [default value of `"/"`](https://github.com/dropwizard/dropwizard/blob/3d78e02c3daef8d4acd78c570a4363db07eedeea/dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java#L259)
3. the value you configure in your application's `run()` block

and since 2 is always present, it always ignores 3.

i'm working around this for my particular use case by using the YAML file. if i come up with a cleaner solution to this, i'll propose a PR.
