### ISSUE TITLE
Odd dropwizard -> jackson versioning in POM

### ISSUE THREAD

**Issue by nheitz** [dropwizard/dropwizard#1440]
MvnRepository suggests that dropwizard (as of 0.9.2) and all of it's subprojects should now be pointing at Jackson 2.7.1.  However, upon IDE import, and subsequent investigation of POMS, this does not seem to be the case.
Excerpt from dropwizard-bom-0.9.2.pom:
```
        <jackson.api.version>2.6.0</jackson.api.version>
        <jackson.version>2.6.3</jackson.version>
```
Thus, I am getting a mish mash of jackson 2.6.3 and 2.7.1 in my IDE import, and using gradle dependencyInsight.

**Comment by joschi** [comment]
I don't know where you've looked up that Dropwizard 0.9.2 would use Jackson 2.7.x, but that's wrong. Make sure to import the `dropwizard-bom` artifact into your project and don't use incompatible Jackson versions – at least if you didn't test the combination before.

**Comment by nheitz** [comment]
I was going based on mvnRepository:
http://mvnrepository.com/artifact/io.dropwizard/dropwizard-configuration/0.9.2

but the version of jackson-dataformat-yaml that is brought in does not match.

**Comment by joschi** [comment]
Well, that's simply a wrong reading of the website. The "Updates" column merely shows the latest version of the dependency in Maven Central, while the "Version" column shows the actual version of the dependency used in that particular artifact.

Make sure that you don't pull in more recent versions via 3rd party dependencies and use the `dropwizard-bom` artifact. Since you're using Gradle, you probably want to take a look at https://spring.io/blog/2015/02/23/better-dependency-management-for-gradle
