### ISSUE TITLE
setContextPath doesn't seem to work.

### ISSUE THREAD

**Issue by TomCools** [dropwizard/dropwizard#1546]
Maybe it's just me doing something wrong, but in my run(con,env) method, i do the following:
`environment.getApplicationContext().setContextPath("/rest");
 environment.jersey().register(HelloWorldEndpoint.class);`

The HelloWorldEndpoint has the **@Path("/hello")** annotation.

When i launch dropwizard however (without config, just using the **server** command), my endpoint is available on _localhost:8080/hello_, not on _localhost:8080/rest/hello_ wich i would expect.

I have tried this in multiple versions, but it doesn't seem to work. Versions tried:

- 1.0.0-rc2
- 0.9.2
- 0.8.5

Logs for 1.0.0-rc2 list: _Registering jersey handler with root path prefix: /_

**Comment by nickbabcock** [comment]
Is modifying the `rootPath` in the configuration not working as well (it does a `setUrlPattern` behind the scenes)?

**Comment by TomCools** [comment]
rootPath works, but i wonder what the setContextPath is used for then?
I like to set it in code for a simple integration test, for which i just want to invoke the run()-method.

**Comment by nickbabcock** [comment]
Ok I looked into a little more and the reason why you're seeing this issue is that the server is not configured until after the Application's `run`. During server configuration it overwrites whatever context path may have been previously set (`SimpleServerFactory` and `DefaultServerFactory`). To get a custom context path in tests use `ConfigOverride` or a different configuration file to set the `applicationContextPath`
