### ISSUE TITLE
Is it possible to use logback.xml instead of *.yml?

### ISSUE THREAD

**Issue by fedotxxl** [dropwizard/dropwizard#1567]
Hello. We've got a lot of different projects. All of them are configured by `logback.xml` and it works. I don't understand why should I learn one more DSL? Why should I think again:

1. How to create new appender?
2. How to use custom appender?
3. What will happen when logback add new functionality? How to use it with dropwizard?

The question is: how to use `logback.xml` configuration instead of `.yml` one?

**Comment by nickbabcock** [comment]
The only official way is through the yaml configuration though I believe #996 allows one to define their own logging factory, so one should be able to create one to use logback.xml

**Comment by joschi** [comment]
@fedotxxl The intention of Dropwizard as a framework is to provide a single point of configuration (the configuration file) for all parts involved. Otherwise, users would have to write their own `logback.xml`, `jetty.xml`, `hibernate.properties` etc. files.

If you want to use a custom Logback appender, you will have to add it programatically.

Since @nickbabcock mentioned an existing workaround for your use case, I'll close this issue.

**Comment by fedotxxl** [comment]
Fixed. 

1. Read http://stackoverflow.com/a/27513081/716027
2. Or implement custom `LoggingFactory`  (e.g. https://gist.github.com/fedotxxl/0b3cc5e5e4eaeffdcde1f9834796edc6) and override `getLoggingFactory()` of your `Configuration` class to return instance of new loggingFactory (I used this approach).

**Comment by prdoyle** [comment]
Agreed with @fedotxxl. Configuring multiple external libraries in the same yaml has little concrete benefit, and it has the downside that configuration advice from those libraries' own authors doesn't work.

At least, it would be nice if it were possible to opt out without writing code. There should be a way in that one yaml to indicate you want to use a library's own native configuration system.
