### ISSUE TITLE
Dropwizard config validation prints attribute name instead of JsonProperty alias

### ISSUE THREAD

**Issue by msteinhoff** [dropwizard/dropwizard#1576]
Hi,

happens with happens Dropwizard 1.0.0-RC2.

When I have a config property, e.g.

``` java
@NotNull
@JsonProperty("foo")
private String baz;
```

and the config file does not include `foo`, I get a validation error telling me that `baz` is missing.

This confuses users when e.g. the documentation only contains the aliased property names.

I guess this happens because the validation doesn't know anything about the alias from the `JsonProperty` annotation.

**Comment by nickbabcock** [comment]
You're correct in your observation that since validation and deserialization are decoupled it does make it harder to correlate errors with the raw data (in this case, the yaml).

I've documented this limitation as part of #1587

It can be better though, and may be something that can be worked on in the future.

**Comment by msteinhoff** [comment]
Hey @nickbabcock, thank you for the documentation.

I see that you have updated it in the rst file. How does dropwizard documentation publishing work? Is this already online somewhere?

Regarding to work on this issue, have you something in mind how this problem could be approached?

**Comment by nickbabcock** [comment]
It's updated whenever there is a dropwizard version update and on the rare occasion that the docs need updating out of band.

The lowest hanging fruit would be to correlate fields that are directly annotated with `JsonProperty` with the validation errors, which would solve your problem. This is what is done for Jersey's `*Params` (and this isn't 100% either). The issue is that with Jackson, there are many more ways for serializing/deserializing an object that it may be impossible to correlate everything without some breadcrumbs for the validator to take advantage of.

**Comment by natnan** [comment]
I handle the `ConstraintViolationException` with my custom exception mapper to return a DTO with field name and error message; so that the frontend can handle it better (focus, mark etc.). I ended up fixing this on my exception mapper (probably missing a lot of edge cases but good enough at the moment). I was hoping to contribute this to [ConstraintMessage](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/ConstraintMessage.java) class, but I couldn't figure out how I could incorporate into the existing logic there yet. So I'll just drop my fix here so maybe someone can handle it or guide me to it.
```
  public static ViolationDto createViolationDto(ConstraintViolation<?> constraintViolation) {
      try {
        StringJoiner pathJoiner = new StringJoiner(".");
        Class<?> beanClass = constraintViolation.getRootBeanClass();
        for (Path.Node node : constraintViolation.getPropertyPath()) {
          Class<?> currentBeanClass = beanClass;
          String fieldName = node.getName();
          PropertyDescriptor propertyDescriptor = new PropertyDescriptor(fieldName, currentBeanClass);
          beanClass = propertyDescriptor.getPropertyType();
          Optional<Annotation> getterJsonAnnotation = Arrays.stream(propertyDescriptor.getReadMethod().getAnnotations())
              .filter(annotation -> annotation.annotationType().equals(JsonProperty.class))
              .findFirst();
          if (getterJsonAnnotation.isPresent()) {
            String getterName = ((JsonProperty) getterJsonAnnotation.get()).value();
            getterName = fixArraySuffix(node, getterName);
            pathJoiner.add(getterName);
            continue;
          }

          Field field = FieldUtils.getField(currentBeanClass, propertyDescriptor.getName(), true);
          Optional<Annotation> fieldJsonAnnotation = Arrays.stream(field.getAnnotations())
              .filter(annotation -> annotation.annotationType().equals(JsonProperty.class))
              .findFirst();
          if (fieldJsonAnnotation.isPresent()) {
            String fieldJsonName = ((JsonProperty) fieldJsonAnnotation.get()).value();
            fieldJsonName = fixArraySuffix(node, fieldJsonName);
            pathJoiner.add(fieldJsonName);
            continue;
          }

          String propertyName = fieldName;
          propertyName = fixArraySuffix(node, propertyName);
          pathJoiner.add(propertyName);
        }

        return new ViolationDto(pathJoiner.toString(), constraintViolation.getMessage());
      } catch (IntrospectionException e) {
        log.error("Error on violation reflection.", e);
      }

      // be safe
      return new ViolationDto(constraintViolation.getPropertyPath().toString(), constraintViolation.getMessage());
  }
```
