### ISSUE TITLE
Custom Auth configuration for different APIs

### ISSUE THREAD

**Issue by vivekkothari** [dropwizard/dropwizard#1579]
Hi,

I have few APIs which are authenticated by BasicAuth and some by Bearer token, currently I am using a ChainedAuthFilter and annotating my resource method with @Auth annotation, and the auth is enabled, but for all the APIs both the types of Auth (Basic & Bearer) are enabled, I want to restrict APIs to use only a specific type of Authentication mechanism.
I am thinking to create a custom annotation say @BasicAuth which when applied to a resource will enable basic auth, this would require changes in the AuthDynamicFeature

**Comment by situokko** [comment]
Related a bit, I am using Toastshaman JWTAuthFilter it works great for JAX-RS resources but would love to be able to use it also for Jetty Websocket connections. Currently there's no way let the filter do then authentication or inject @Auth Principal-object for WS-connection but I have to do the authentication manually during UpgradeRequest.

I commented this in Toastshaman-JWT AuthFilter project before but then I realised it should be actually handled on DW AuthFilter side.

**Comment by NickEckert** [comment]
Yea I'm having a problem using two different authenticators for two different resource methods. I tried registering them separately and using chained factories but nothing works and I feel like using different types of authentication should be possible.

**Comment by RohanNagar** [comment]
This is also related to auth and what @NickEckert is talking about - I want to protect two resource methods with different Principals. One basic auth using a user's username a password, and another basic auth using an application name and password. Registering two` AuthValueFactoryProvider.Binder<>` instances does not seem to be working. Any information on this?

**Comment by HunterSherms** [comment]
Hey @RohanNagar! From what I have found you can't use multiple Principle types. Our work around was to create a parent object with the various user types as properties and a getUser() method that throws a Forbidden exception if you try to access one of the null properties. Please let me know if you find a more elegant solution!

**Comment by RohanNagar** [comment]
Awesome @HunterSherms, that should work out for me! Thanks a bunch 😄

**Comment by evnm** [comment]
If you only need authentication (i.e. not authorization), then take a look at [PolymorphicAuthDynamicFeature](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-auth/src/main/java/io/dropwizard/auth/PolymorphicAuthDynamicFeature.java). It allows you to specify `Authenticator`s for specific `Principal` subclasses. See [the motivating issue](https://github.com/dropwizard/dropwizard/issues/1318) for details.

As pointed out in #1632, there is a gaping hole in this feature when it comes to authorization. This may be fixed in future, pending the resolution of this issue.

**Comment by evnm** [comment]
@vivekkothari Shall we close this issue or are you still concerned with the lack of polymorphic _authorization_?

We decided to close #1632 after increasing the amount of documentation around PolymorphicAuthDynamicFeature. @psamsotha's thorough discussion of the issue really drove home for me how complicated the auth stack is, especially in terms of coupling between authentication and authorization. Barring some drastic rewrite, there seems to be a general preference for explicit documentation of shortcomings rather than additional functionality to cover corner cases.

**Comment by vivekkothari** [comment]
I am closing this issue now.
