### ISSUE TITLE
Dependency Injection frameworks

### ISSUE THREAD

**Issue by darrenhaken** [dropwizard/dropwizard#1626]
Can you provide any advice on what DI framework works best with Dropwizard?

I've tried both Guice and Dagger plugins yet they always seem to have integration issues with the core Dropwizard framework. I'm surprised that in the Dropwizard tool chain a DI container isn't recommended.

Any thoughts? Do you assume teams will hand roll DI as you're focusing on teams producing smaller APIs?

**Comment by joschi** [comment]
@darrenhaken For simple cases, you can use HK2, which is brought in by Jersey: https://gist.github.com/joschi/f706e394172988f9200b

Which specific problems did you have with Guice and Dagger?

**Comment by darrenhaken** [comment]
Guice had issues when wiring up the Jersey HTTP client provided as part of Dropwizard.
I ended up removing it from the project and hand rolling dependencies as it's a microservice and didn't have many classes anyway.

Having looked into Dagger I was not very impressed with the requirement to create an interface which then a class is compiled from via annotations. I tend to not be keen on annotation processing.

I'll check out HK2 over the next couple of days.

**Comment by HunterSherms** [comment]
Hey @darrenhaken - I'm extremely happy with Dagger in DW. Feel free to reach out if you have any questions.

**Comment by Allsimon** [comment]
Did you manage to inject field directly via dagger2 ? I can inject with constructors just fine, but fields injection clash with HK2

**Comment by terranmoccasin** [comment]
I've managed to get my project working well with Guice. The main gotchas:

1. Making sure you're using [JSR330 annotations](https://github.com/google/guice/wiki/JSR330) instead of com.google.inject annotations when possible
2. Clashes with HK2, which can be resolved by using the [HK2-guice bridge](https://hk2.java.net/guice-bridge/)

I've been able to use the [soabase-guice](http://soabase.io/guice.html) bundle, which is a pretty small dependency, to wire up my project.

**Comment by HunterSherms** [comment]
@Allsimon I use constructor injection. Makes unit testing with Mockito etc. very easy.

**Comment by darrenhaken** [comment]
@terranmoccasin I'll give it a try now. 

I've tried https://github.com/HubSpot/dropwizard-guicier but I'm having some complaints from Jersey about it right now.

**Comment by terranmoccasin** [comment]
@darrenhaken Cool, yeah lemme know if you run into any problems. I wrestled with a lot of obscure stack traces, but it ended up being a quick fix by changing @BindingAnnotation to @Qualifier and @Inject from com.google.inject to javax.inject.

https://github.com/soabase/soabase/issues/35 is the thread where I'm hoping to get DW 1.0 support into soabase. For now, there's a link to my fork with the changes required to get things working with 1.0.0-rc3 (mainly matching the Jersey, Jackson, and HK2 versions) that you can use as a reference.

**Comment by darrenhaken** [comment]
@terranmoccasin can you provide an example of wiring up soabase?

I have looked at the docs:

```Java
InjectorProvider injectorProvider = ...
bootstrap.addBundle(new GuiceBundle<>(injectorProvider));
```

What is the concrete type for the injector provider?

**Comment by darrenhaken** [comment]
@terranmoccasin 
I did the following:
```Java
bootstrap.addBundle(new GuiceBundle<>(new StandardInjectorProvider<>(
            binder -> {
                binder.bind(HealthResource.class);
            }
        )));
```

Seems to at least resolve my dependency. Is there anything else I need to do?
Any example repos or gists are welcome 👍

**Comment by terranmoccasin** [comment]
@darrenhaken Nope, that's pretty much it. Only other things I can think of...

1. If you're using Guice's ServletModule, replace it with [JerseyGuiceModule](https://github.com/soabase/soabase/blob/master/soabase-guice/src/main/java/io/soabase/guice/JerseyGuiceModule.java).
2. If you're using any HK2 bindings (like the latter portion of this [SO answer](http://stackoverflow.com/questions/23231511/jersey-2-how-to-create-custom-http-param-binding)), remember to register it yourself, since it doesn't seem like soabase-guice will do those for you.

I also added binding resources via reflection at runtime (inspired by [dropwizard-guice AutoConfig](https://github.com/HubSpot/dropwizard-guice/blob/master/src/main/java/com/hubspot/dropwizard/guice/AutoConfig.java#L111)) by using [org.reflections](https://github.com/ronmamo/reflections).

```
  private static final Reflections REFLECTIONS = new Reflections(BASE_PACKAGE_PATH);

  /**
   * Bind all @Path annotations with in our package. These binded classes will automatically be
   * registered into Jersey via the soabase-guice bundle.
   */
  private void bindJerseyPaths() {
    REFLECTIONS.getTypesAnnotatedWith(Path.class).forEach(pathClass -> bind(pathClass));
  }
```

**Comment by darrenhaken** [comment]
@terranmoccasin this might sound stupid but how would I know if I'm using the Guice's servlet module?

Nice work on the reflections! I was thinking of doing something with reflection for auto wiring

**Comment by terranmoccasin** [comment]
@darrenhaken You don't really need it - it's the Guice extension for configuring servlets and binding them to paths (AKA map "/test" to MyTestServlet.class), but the Jersey resources handle that with @Path("/test") annotations. The only reason I'm using it is because I have custom Filters for my servlets, and I wanted to make sure they're created via Guice.

**Comment by saumitrabhave** [comment]
I have moved away from guice. I have been using hk2 for DI in multiple DW projects, I think its pretty neat.

**Comment by LeDominik** [comment]
I have to say I'm _very happy_ with Dagger 2 in Dropwizard. Took me a little bit of head-scratching in the beginning but now it's really neat; my little trick is that I have an `EnvModule` which gives me a lot of the Dropwizard things, like e.g. the fully configured [`ObjectMapper`](http://www.dropwizard.io/1.0.0/dropwizard-core/apidocs/io/dropwizard/setup/Environment.html#getObjectMapper--) -- I create everything in run() and pass the re-usable stuff in the nice builder-syntax when creating my component. 

And then I just have a production [`@Component`](http://google.github.io/dagger/api/2.0/dagger/Component.html) and a few for testing-purposes (especially one with fake implementations instead of real connections). I have not yet done multiple scopes for session / request but shouldn't be too hard.

What I just ❤️ about Dagger 2 is that it's just generated code and I can honestly report the compiler did report _a lot_ that other systems would have told me sometime lazily...

**Comment by leordev** [comment]
Hey guys, I decided to go on with the default HK2...

But now I'm confused in how can I inject an object in AuthDynamicFeature (dropwizard-auth) ->> https://gist.github.com/joschi/f706e394172988f9200b#gistcomment-1853132 

Any ideas for that?

**Comment by alex-shpak** [comment]
If you still interested I created HK2 integration for dropwizar: https://github.com/alex-shpak/dropwizard-hk2bundle
Enabling injection for dropwizard objects like health-checks and etc.
You also can obtain `ServiceLocator` from there. Just register some service and inject `ServiceLocator`.

Basically there are 2 service locators: one before server initialization and one after, which has first `ServiceLocator` as parent.

**Comment by HunterSherms** [comment]
"HK2 defines services and injection points that can be dynamically discovered at runtime"

Use Dagger and find your bugs at compile time instead 😉

**Comment by joschi** [comment]
@HunterSherms Dagger is an external dependency, HK2 comes with Dropwizard (via Jersey), to it's not that easy.

Also Dagger (obviously) doesn't support runtime discovery of bindings AFAIK, which can be used for implementing a plugin system.

**Comment by ramsrib** [comment]
Guys, please include a section for `Dependency Injection` in the official documentation with some examples.

**Comment by ramsrib** [comment]
Does soabase is supported by the dropwizard community?

**Comment by joschi** [comment]
@ramsrib [Soabase](http://soabase.io/) is a 3rd party bundle.

**Comment by mikeholler** [comment]
Where are we at with documentation on dependency injection frameworks? When we started using Dropwizard a month ago I thought we could just supply our own DI framework and provide Jersey with instances rather than classes via `register(Object)` and not `register(Class)`.

This worked well initially until we wanted to inject things from the Jersey HK2 `@RequestScoped` context, like `UriInfo` for example.

We're currently using Kodein with the `register(Object)` approach described above, and I researched writing my own bridge to HK2 using `ComponentProvider` from Jersey, but that didn't pan(it still seems like it's possible, but I have no idea how to go about using it to accomplish what I need in Jersey, much less Dropwizard).

To get this to work, I've investigated Jersey's official `jersey-spring3` support, which apparently isn't compatible with Dropwizard (https://github.com/dropwizard/dropwizard/issues/1736), the HK2 Guice Bridge (https://javaee.github.io/hk2/guice-bridge) which doesn't have much documentation for use with Jersey much less Dropwizard, and using HK2 straight (IMO HK2 is not a great DI framework, but this seems like the easiest option -- but there's still not good documentation on it).

I'm kind of at a loss here. Dropwizard's documentation is great in so many other ways, and I love it as a framework, but I'm having a really hard time with the fact that there's no resources on Dependency Injection. IMO this is something that should come with a "batteries-included" solution for a framework in Dropwizard's space. DI is so important to writing good, modular enterprise projects. It really doesn't matter to me what Dropwizard's solution is here (Dagger/Dagger 2/Spring 3/Spring 4/HK4/Guice/Kodein/ete.), just that there's some guidance. Can anybody point me in the right direction?

**Comment by HunterSherms** [comment]
@mikeholler I think that recommending or baking in a DI framework runs counter to DropWizard's "no magic" philosophy. If you want to bake in DI you can but it's not forced on you as it is in Spring, and as a result you have more choices, but for some things you kind of just have to figure it out.

If you're interested in wiring in Dagger I'd be happy to jump on a hangout or something and show you how I do it.

**Comment by mikeholler** [comment]
Thanks for the quick response @HunterSherms! :smile: 

> I think that recommending or baking in a DI framework runs counter to DropWizard's "no magic" philosophy. If you want to bake in DI you can but it's not forced on you as it is in Spring, and as a result you have more choices, but for some things you kind of just have to figure it out.

I know my post above was suggesting that Dropwizard pick a framework and say that's the way to do it, but what you're suggesting is fine for me too. Either way though, there's no documentation and I have no idea how to get started. I got my own DI working of course (Kodein) but I have no idea how I'd even start to go about linking it into Jersey so that `register(MyResource.class)` causes Jersey to create and inject new instances of `MyResource` using my DI graph.

> If you're interested in wiring in Dagger I'd be happy to jump on a hangout or something and show you how I do it.

This is super generous. Give me a day or two and I may very well take you up on this. Even if I'm not interested in using Dagger (I'm on the fence, as with everything else) seeing how to link it in would be very valuable. It sounds like your setup does what I want mine to accomplish, as described above?

**Comment by HunterSherms** [comment]
I have no experience with Kodein, but with Dagger you basically init your DI within the Run method and can either pass your `Environment` into your DI modules there for wiring things into DW/Jersey, or you can return your top level resources from the DI component and wire them in below where you init Dagger.

Here's a little example with both approaches:

``` Java
    // Your application's Run method
    @Override
    public void run(ExampleConfiguration configuration, Environment environment) {

        final ExampleComponent exampleComponent = DaggerExampleComponent.builder()
                .dbModule(new DbModule(environment, configuration))
                .utilModule(new UtilModule(environment, configuration))
                .resourcesModule(new ResourcesModule(environment, configuration))
                .build();

        // Wiring dependencies in outside of Dagger modules
        environment.jersey().register(exampleComponent.getExampleResource());
        environment.admin().addTask(exampleComponent.getExampleTask());
    }
```

```Kotlin
// From within one of your Dagger modules
@Module
class ExampleModule(private val env: Environment, private val configuration: ExampleConfiguration) {

    @Singleton
    @Provides
    fun providesExampleManagedThing(): ExampleManagedThing {

        try {

            val thing = ExampleManagedThing()
            env.lifecycle().manage(object : Managed {
                override fun start() {
                    //Start your thing
                }

                override fun stop() {
                    //Stop your thing
                }
            })

            return thing
        } catch (e: Exception) {

            log.error("Unable to initialize Thing", e)
            throw RuntimeException(e)
        }
    }
}
```

**Comment by mikeholler** [comment]
Yeah, see that's exactly what I'm doing in Kodein, but

```
environment.jersey().register(exampleComponent.getExampleResource());
```

I want to be able to do `environment.jersey().register(ExampleResource::class.java)` so I can let Jersey create an instance of my resource _per request_. This is something that Jersey has native support with via HK2, but HK2 is not very popular of a framework anymore.

**Comment by HunterSherms** [comment]
In what scenario would you want to build a resource for each request? If I understand what you're asking that's a bit of an anti-pattern as they're intended to be stateless singletons that last the lifetime of your application.

If you have a specific object that needs to be instantiated per-request then pass a factory class as a dependency to your resource and call `exampleFactory.get()` on each request.

**Comment by mikeholler** [comment]
> In what scenario would you want to build a resource for each request? If I understand what you're asking that's a bit of an anti-pattern as they're intended to be stateless singletons that last the lifetime of your application.

I actually disagree with this quite heavily. Creating new instances reduces the chance that any shared state or threading issues within resources could become a problem. That being said, it's an anti-pattern to write stateful resources of course and I try to avoid that at all costs, but I also try to code defensively. Creating objects on the JVM is not as expensive as it used to be, and it's good practice to keep your object lifecycles short; also reduces the likelihood for memory leaks, etc.

But really, we can debate about best practices all we want, but at the end of it I can't have an `Authenticator` that has access to the whole request via injection without letting Jersey's HK2 DI graph construct it for me per request, so there are functional differences between the two approaches (where it's not a matter of preference but lack of access).

**Comment by mikeholler** [comment]
I've decided to stick with my Kodein approach for now, after attempting to see if I could work with HK2 to leverage Jersey's built-in graph (I really can't -- doing so requires too much restructuring).

@HunterSherms thanks again for your help and suggestions. You're right that the way you've gone about it (which is very similar to what we're doing here) is probably the best we have right now. Thanks so much for your time :smiley:

**Comment by kibertoad** [comment]
@joschi I can contribute documentation on doing DI with HK2 in Dropwizard-friendly way, if you think project would benefit from that.

**Comment by joschi** [comment]
@kibertoad Yes, definitely! It would be great if you could improve the documentation in this regard.

**Comment by kibertoad** [comment]
@joschi Just sent in a PR with example. It is somewhat more heavyweight than the gist you shared before, but I'm not sure if it can be done in less code if you want to preserve option of overriding some of your dependencies in tests, which is one of the main reasons of using DI in the first place.

If there are better ways to achieve same goal, I would be happy to rework the documentation proposal.

**Comment by CrazyBolillo** [comment]
@kibertoad 
Im a complete noob at this. Based on the documentation you provided I understand that you need to manually bind the classes you would like to inject by adding them to the array returned from 
```public List<Class<?>> get Singletons()```?

If anyone is interested I have more or less figured how to use hk2 with ```@Service``` and ```@Contract``` annotations. I don't know how common or valuable that knowledge is. Perhaps I am bad at searching but I had to look for a few hours around Stack Overflow to get the approach working, and there are still some details I haven't figured out yet. 

I don't use Dropwizard but I use the same stack (Jersey on Jetty) so perhaps I think it can be adapted to work with Dropwizard.
