### ISSUE TITLE
How to add provider for authenticator in  ResourceTestRule ?

### ISSUE THREAD

**Issue by bruce-genhot** [dropwizard/dropwizard#1629]
We are trying to upgrade dropwizard 0.8.2 to 1.0.0.rc3, but original integration tests do not work any more. 

When we use dropwizard 0.8.2, we add authenticator provider like below.
```
ResourceTestRule.builder().addProvider(AuthFactory.binder(new BasicAuthFactory<>(new UserAuthenticator(userStore, userOrganizationDAO), "", AuthenticatedUser.class)))
```

In 1.0.0.rc3, class AuthFactory has been removed, my question is how to do the same thing against the version 1.0.0.rc3 ? thank you.

**Comment by psamsotha** [comment]
Look at the current (9.3) [auth documentation](http://www.dropwizard.io/0.9.3/docs/manual/auth.html). 1.x auth seems to be pretty much backward compatible with the latest 9.3, at least from what I can tell. So that documentation should still be good. There's really not much change. If you look at the Basic Authentication section, you'll see the three main providers you'll want to register and how to register them.

Another thing is you will need to make your principal class implement `Principal`, which I don't think was the case in 0.8.x

**Comment by bruce-genhot** [comment]
OK, thanks, it works for me now.
