### ISSUE TITLE
JerseyClient ExecutorService not Shutdown gracefully

### ISSUE THREAD

**Issue by saumitrabhave** [dropwizard/dropwizard#1671]
Hi:

I am looking at https://github.com/dropwizard/dropwizard/blob/master/dropwizard-client/src/main/java/io/dropwizard/client/DropwizardExecutorProvider.java

which provides an executor service to Jersey Client for Async Execution. I think that, because of NO-OP implementation of dispose method, any async requests waiting in queue are just killed like that.

It would be good to have an implementation for dispose which calls shutdown and awaitTermination(With Configurable wait time maybe). This will make sure that any async() WebTargets submitted already are given time to complete in case DW Service is being closed/terminated.

**Comment by evnm** [comment]
I think this is a valid concern, but I don't think it's as simple as invoking `ExecutorService#shutdown` within the `dispose` method. Doing so is the right thing to do _as long as the `ExecutorService` isn't shared_ (see third paragraph in [ExecutorServiceProvider Javadoc](https://jersey.java.net/apidocs/2.22/jersey/org/glassfish/jersey/spi/ExecutorServiceProvider.html)).

In this case, we can't guarantee that the service isn't shared. For example, the `ExecutorService` used in `JerseyClientBuilder` may be passed in via the appropriate `using` method, in which case that executor could be used in other parts of an application.

All of this is to say that a fix for this issue is still possible, it would just need to be nuanced. I can put a change together and we can take further discussion to a PR.

**Comment by saumitrabhave** [comment]
ohh, I missed that use-case,
 
one alternate place can be https://github.com/dropwizard/dropwizard/blob/master/dropwizard-client/src/main/java/io/dropwizard/client/JerseyClientBuilder.java#L349 

here we can shutdown the executorService explicitly after client.close(), as it is the environment shutdown() callback everything has to go away anyways i guess.

or some mix of both of these approaches, to handle shutdown in dispose() when custom execService is not provided via using() and do it in lifecycle shutdown if custom execService is provided to builder.

I think you will have better idea of whats needed, please link this issue to PR so I can add my 2 cents.

**Comment by arteam** [comment]
Closed via #1676
