### ISSUE TITLE
Dropwizard Request timeout

### ISSUE THREAD

**Issue by darrenhaken** [dropwizard/dropwizard#1674]
I'm trying to ensure that requests timeout after a suitable period. 
Looking through the docs the idleTimeout config param should define that (default 30 seconds).

I tried running a request with a Thread.sleep for > 30 seconds and it didn't time out to the client.
Any idea why this might be?

**Comment by evnm** [comment]
I don't know Jetty's internals super well, but I think that it comes down to the semantics of what the [idle timeouts on `Connector`s](http://download.eclipse.org/jetty/9.3.9.v20160517/apidocs/org/eclipse/jetty/server/AbstractConnector.html#setIdleTimeout-long-) mean (emphasis mine):

>The max idle time is applied:
>
> * When waiting for a new message to be received on a connection
> * When waiting for a new message to be sent on a connection
>
> This value is interpreted as the maximum time between some progress being made _on the connection_.

I think that in the case you're describing, where you stick a `Thread.sleep(...)` within a resource method, the server is pausing during request-handling rather than while Jetty is waiting for bytes to be transferred. That is to say, a connection is _idle_ if it's hung in the transfer state rather than the request-handling state.

Somebody please correct me if I'm wrong. This is what "idle timeouts" mean in Netty/Finagle parlance, at least. These other server libraries provide more granular types of timeouts (ex: [Finagle](https://twitter.github.io/finagle/guide/Clients.html#timeouts-expiration)), which unfortunately Jetty doesn't seem to provide.

**Comment by nickbabcock** [comment]
[Someone asked a similar question several years ago](http://jetty.4.x6.nabble.com/how-to-set-connection-request-timeout-for-jetty-sever-td43743.html). I'm under the impression that nothing changed under this situation. The answer then:

> Jetty has no timeout that limits how long a handler can handle for. 
>
> You could simply write a handler wrapper than imposed such a timeout 
> and interrupted the thread if it took longer than your 2s etc. and 
> wrote a response in the finally block. 

Nowadays, one could use [Guava's SimpleTimeLimiter](https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/util/concurrent/SimpleTimeLimiter.html) or [Jersey's async server timeout handler](https://jersey.java.net/documentation/latest/async.html).

**Comment by nickbabcock** [comment]
Closing the issue as the solution presented should be satisfactory. If not, please respond with additional details.

**Comment by BenRomberg** [comment]
I'd be happy to write my own `Handler`/`HandlerWrapper` to achieve this, just wondering how I'd inject this to be used within Dropwizard. Write my own `ServerFactory` and return a custom `Handler` from `createAppServlet`? Would that work or is there a simpler way?
