### ISSUE TITLE
Mappings for url patterns of Servlet Filters are not working properly

### ISSUE THREAD

**Issue by htimur** [dropwizard/dropwizard#1694]
Effected only in dropwizard 1.0.0

After adding the filter:
```
environment.servlets().addFilter("Guice Filter", GuiceFilter.class).addMappingForUrlPatterns(null, false, "/some/context/path/*");
```
and calling the resource with specified path, filter is never invoked.

It only works if root context is specified as the pattern:

```
environment.servlets().addFilter("Guice Filter", GuiceFilter.class).addMappingForUrlPatterns(null, false, "/*");
```

**Comment by evnm** [comment]
Hello Timur. Are you overriding the application context path in your config file?

**Comment by htimur** [comment]
Hi @evnm, yes the application context path is overridden, and that application context is used to set the url mapping:
```
environment.servlets().addFilter("Guice Filter", GuiceFilter.class).addMappingForUrlPatterns(null, false, environment.getApplicationContext().getContextPath() + "*")
```

**Comment by evnm** [comment]
I think the problem has to do with the difference between the context path and the servlet path. As I understand it, the context path _precedes_ servlet paths and is not included within them. For instance, given a path `/context_path/foo/bar` where `/context_path` is the application context path, then filters must be registered for URL patterns that match `/foo/bar`.

In your case, I suspect that `.addMappingForUrlPatterns(null, false, "/*")` is actually what you want. This wildcard path will result in all paths being filtered, which I assume is what you want.

**Comment by htimur** [comment]
@evnm the issue appeared after migrating to dropwizard 1.0, previously with 0.9 version it was working without any problems.

**Comment by evnm** [comment]
If my assumption above is correct, then the behavior in 0.9.x may have been relying on a bug. [Jetty's changelog](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/VERSION.txt) doesn't indicate anything changes to context path interpretation between 9.2.13.v20150730 and 9.3.9.v20160517 (the versions on which Dropwizard 0.9.3 and 1.0.0 depend, respectively).

Does this change in behavior actually cause problems for you? Does using a path pattern of `"/*"` not work for your application? Instead of debating what "working properly" means, perhaps we can just improve the documentation on context path interpretation.

**Comment by htimur** [comment]
@evnm Thanks, you are right. And would be good to improve documentation on context path interpretation.
