### ISSUE TITLE
@POST method with @Auth parameter can not use a JSON bean as another method parameter

### ISSUE THREAD

**Issue by Rwprice** [dropwizard/dropwizard#1697]
```
@POST
@Consumes(MediaType.APPLICATION_JSON)
public Response receivePost(@Auth ExtendedPrincipal principal, @Valid ResourceSet resourceSet)
```

I have a resource that I am trying to protect with my auth filter that I have. The AuthFilter should resolve the principal and not factor into this. The ResourceSet is being passed in the Post's body.

Sending a valid ResourceSet object causes an immediate "400: Bad Request" response before hitting my code. Sending a Post without a body though, makes it to my code with a null ResourceSet.

Is there a known workaround for this? Is this something that can be fixed?

**Comment by evnm** [comment]
Hello Ryan. A few questions:

Is there any error message included in the 400 you get from your server? For instance, when I've run into issues like this, it's typically because the JSON in the request body isn't properly formatted, in which case you get a "Unable to process JSON" message in the response.

Can you provide more detail about your application? What version of Dropwizard are you using? What authenticators/authorizers are you using in conjunction with the `@Auth` annotation? What happens if you remove the `@Auth` parameter of `receivePost`?

**Comment by Rwprice** [comment]
Whoops, my bad, I was making a mistake in my authfilter that was actually the cause. Its working as expected now. You can delete/close this issue
