### ISSUE TITLE
DropwizardTestSupport not compatible with Failsafe 2.19

### ISSUE THREAD

**Issue by cowwoc** [dropwizard/dropwizard#1709]
Failsafe 2.19 now runs tests out of JAR files: https://issues.apache.org/jira/browse/SUREFIRE-855

DropwizardTestSupport assumes that `configPath` can be a String (the file path) but this isn't possible for config files located inside JAR files.

The only way I can think of fixing this is to replace `String configPath` with a URI, then open an `InputStream` to read the config file whether it resides in target/classes or inside a JAR file.

However, you just released version 1.0.0 and this sounds like a breaking change ;)

**Comment by evnm** [comment]
Thanks for reporting the issue, Gili.

Rather than change the type of the `configPath` field, perhaps we could add a new `io.dropwizard.configuration.ConfigurationSourceProvider` which produces an `InputStream` from a file within a JAR. The `configPath` string could be formatted according to the JAR protocol expected by `java.net.URL` (i.e. `"jar:file:/path/to/some.jar!/path/to/file"`).

`DropwizardTestSupport` could then optionally invoke `Bootstrap#setConfigurationSourceProvider` depending on the state of `configPath`.

Would you be interested in bringing this change to a PR?

**Comment by cowwoc** [comment]
That could work. Unfortunately this is too elaborate for me to be able to provide a PR for (too busy at work) so I am afraid I will have to leave the implementation to you.

**Comment by Tibor17** [comment]
@cowwoc 
@evnm 
I am from Maven Surefire project. I see you have mentioned Jira issue 855. If you need to have any support just let me know.

**Comment by cowwoc** [comment]
Hi @Tibor17,

I am not actively working on this issue as I have bigger fish to fry at the moment. For now, I am just passively interested in this issue's resolution.
