### ISSUE TITLE
SOAP Service Client framework

### ISSUE THREAD

**Issue by rpawarmca** [dropwizard/dropwizard#1712]
We have a requirement to consume SOAP services. Can you please advise, which framework we should use with dropwizard to write SOAP service client?

**Comment by evnm** [comment]
Hello @rpawarmca. The question of what is the best-of-breed Java SOAP client library is outside of Dropwizard's scope, since we'll never be in the business of providing a SOAP library. I think [the dropwizard-users mailing list](https://groups.google.com/forum/#!forum/dropwizard-user) would be a more suitable venue for your question, so perhaps you could ask there?

**Comment by rpawarmca** [comment]
Thanks @evnm , let me check on the mailing list.

**Comment by gavarava** [comment]
Hey, this is a dropwizard SOAP solution if you are still interested :) 
https://github.com/roskart/dropwizard-jaxws
