### ISSUE TITLE
append hostname to graphiteReporter metric key prefix

### ISSUE THREAD

**Issue by rafael-driutti-olx** [dropwizard/dropwizard#1725]
Hello!

I'm running several instances of a same dropwizard project behind a load balancer, and all of them report to the same graphite host. Since all of the instances have the same config all the metrics go to graphite with the same prefix, so it gets impossible to have metrics per individual instance.
I worked around this issue adding a command-line option like this in the init scirpt:

> -Ddw.metrics.reporters[0].prefix=common.prefix.for.my.app.`hostname`

I.E. using the back-ticks to add the output of the shell command "hostname" to the prefix for the graphite metrics. This way I get the name of the machine on the metrics and I can inspect them individually if I need to do so.

I really prefer to control this from the application config rather than the init script. Wrote  some changes for the GraphiteReporter so I can pass an option  on the yml config so it tries to get the hostname using **InetAddress.getLocalHost().getHostName()** to append it to the prefix from the config.
https://github.com/rafael-driutti-olx/dropwizard/commit/94e0f0092902de7b09b3fe89dd5fb503ce0085b4

Do you think this could be useful?

If so, what's the best way to handle an eventual UnknownHostException ? I just assign "localhost" to the prefix... should I raise an error and/or prevent the server from starting?

```
  try {
                localHostName = InetAddress.getLocalHost().getHostName();
            } catch (UnknownHostException e) {
                localHostName = "localhost";
            }
```

Thanks!

**Comment by evnm** [comment]
Could your deployment workflow allow you to set the [`prefix` configuration option of `GraphiteReporter`](http://www.dropwizard.io/1.0.0/docs/manual/configuration.html#graphite-reporter)? If you use some configuration management system to distribute templatized Dropwizard config files to your instances, you could simply include the hostname in the prefix:

```
metrics:
  reporters:
    - type: graphite
      prefix: common.prefix.for.my.app.59.13.234.31
```

The purpose of the `prefix` config option is to be general enough to satisfy most use cases. I'm hesitant to entertain a hostname-prefixing patch, since it strikes me as one among multiple possible pieces of application metadata that could feasibly be used to prefix metrics. For instance, you could imagine using a PID or something cloud-provider-specific like an EC2 instance ID or tag.

**Comment by rafael-driutti-olx** [comment]
Hi!
I see your point, but I tend to identify my hosts (and things in general) by _name_ rather by AWS id, process id or other difficult to remember reference, so that I can easily find them on my metrics storage. Especially on multiple instance/HA/ASG setups.
I just thought was better to add this kind of logic to the application rather than the init scripts or deploy pipelines. Must be because I'm a sysadmin not a developer :D
Thanks for the feedback!
