### ISSUE TITLE
Should OptionalMessageBodyWriter return 404 when the response is Optional.empty()

### ISSUE THREAD

**Issue by qinfchen** [dropwizard/dropwizard#1727]
Instead of returning NotFoundException for Optional.empty(), should it return 204 instead 404 based on the definition of the status codes below?

*404* client error
>The server has not found anything matching the Request-URI. No indication is given of whether the condition is temporary or permanent. The 410 (Gone) status code SHOULD be used if the server knows, through some internally configurable mechanism, that an old resource is permanently unavailable and has no forwarding address. This status code is commonly used when the server does not wish to reveal exactly why the request has been refused, or when no other response is applicable.

*204* success
> The server has fulfilled the request but does not need to return an entity-body, and might want to return updated metainformation. The response MAY include new or updated metainformation in the form of entity-headers, which if present SHOULD be associated with the requested variant.

>If the client is a user agent, it SHOULD NOT change its document view from that which caused the request to be sent. This response is primarily intended to allow input for actions to take place without causing a change to the user agent's active document view, although any new or updated metainformation SHOULD be applied to the document currently in the user agent's active view.

>The 204 response MUST NOT include a message-body, and thus is always terminated by the first empty line after the header fields.

>Wikipedia
The server successfully processed the request, but is not returning any content.

 >Status when wrapped responses (e.g. JSEND) are not used and nothing is in the body (e.g. DELETE).

http://www.restapitutorial.com/httpstatuscodes.html

**Comment by nickbabcock** [comment]
This makes sense, but I'm always wary of changing status codes, so CC: @dropwizard/committers 

I think treating this as a bug could be the appropriate response.

**Comment by evnm** [comment]
I think the short answer is "no". JAX-RS specifically intends for `NotFoundException` to trigger 404s.

See [the `javas.ws.rs` package summary](http://docs.oracle.com/javaee/7/api/javax/ws/rs/package-summary.html):

> NotFoundException—A runtime exception indicating a resource requested by a client was [not found](http://docs.oracle.com/javaee/7/api/javax/ws/rs/core/Response.Status.html#NOT_FOUND) on the server.

**Comment by nickbabcock** [comment]
I think @qinfchen was arguing that the writer shouldn't throw `NotFoundException` -- not that the behavior of `NotFoundException` should change.

**Comment by evnm** [comment]
D'oh. My bad.

I'm not sure that there's a right answer here, but I think it'd be make sense to return 204s on `Optional.empty()`. I think it's beneficial to compel applications to be explicit about when they return errors. The semantics of whether an endpoint returns 204 or 404 is an application concern, but I think it makes sense to force developers to explicitly throw `NotFoundException` or a 404  `Response` if they truly want to convey a client error.

The concern would be confusion caused by this behavior changing in Dropwizard. Many applications may be implicitly relying on their `Optional.empty()` results being translated into 404s.

**Comment by qinfchen** [comment]
Exactly, I'd prefer having defaults set to 204 and forcing devs to explicitly throw 404 response to convery the client error. 
For the change of default behavior, i think it should be fine as long as this is clearly stated in the release notes.

**Comment by qinfchen** [comment]
@evnm, i created a PR to change the types, please let me know if I can help with alleviating the concerns on changing of the default behavior.

**Comment by joschi** [comment]
I'm not sure that this change is good.

At least for existing users of Dropwizard it will be *very* surprising to get a 204 (No Content) response status instead of 404 (Not Found).

From a semantics point of view (Java, not HTTP) and having an `Optional<String>`, it should return "not found" if the optional value isn't present and "no content" if the optional value is the empty string. Of course that's only one example, but I'd like to discuss more "real world" examples before implementing such a change.

> EDIT: maybe also provide a way for users to configure the writer for the old behavior

👍  if we decide to implement this change.

**Comment by qinfchen** [comment]
However, having an empty string can considered as a valid response which isn't the same as "no content" and `Optional.empty()` isn't the same os Optional.of("");
