### ISSUE TITLE
Documentation issue for dropwizard 1.0 Validations

### ISSUE THREAD

**Issue by jmoney8080** [dropwizard/dropwizard#1740]
http://www.dropwizard.io/1.0.0/docs/manual/validation.html#extending says 

> The The method used to determine what status code to return based on violations is ConstraintViolations.determineStatus

However the method `io.dropwizard.validation.ConstraintViolations#determineStatus` no longer exists in 1.0.  Could use some documentation love on what to do here.

**Comment by nickbabcock** [comment]
Thanks for pointing out the deficiency in the docs. I can take a look and fix it up.

To help me out, do you mind elaborating on your use case for `determineStatus`?

**Comment by jmoney8080** [comment]
We used it in a custom ExceptionMapper to hook into our error hierarchy.

```
ValidationErrors validationErrors = new ValidationErrors(Object.class, exception.getConstraintViolations());
        ApiError error = new ApiError(ErrorCode.VALIDATION, exception.getMessage(), validationErrors, RequestIdUtils.getApiRequestId());
        logger.info(String.format("%s : Bad Request (%s) %s", getContextString(), error.getId(), error.getMessage()));
        return Response.status(ConstraintViolations.determineStatus(exception.getConstraintViolations()))
                .entity(error)
                .build();
```

That's what we did in 0.9.  In 1.0 we are reworking the Exception stuff but if there is a more preferred approach than what `io.dropwizard.validation.ConstraintViolations#determineStatus` used to do we will gladly investigate.  `io.dropwizard.validation.ConstraintViolations#determineStatus` was just never deprecated so we had no idea it was being removed in 1.0.

**Comment by nickbabcock** [comment]
Yeah, you're looking at the guy responsible for your pain, I apologize (PR: #1251)

`ConstraintViolations#determineStatus` was moved to the jersey sub-module `ConstraintMessage#determineStatus` because the status code no longer relies on just the constraint violations, but it also depends on the resource endpoint where the violation occurred. The previous `ConstraintViolationExceptionMapper` has been moved to `JerseyViolationExceptionMapper`, and since it looks like you're defining your own exception mappers you should be able to create your own `ExceptionMapper<JerseyViolation>` and call the new `determineStatus`

**Comment by jmoney8080** [comment]
No worries at all! It was 1.0, expected some pain.

It seems all methods in `ConstraintMessage` require an `Invocable` parameter.  Any suggestions on how to get one of these from an `ExceptionMapper`?

**Comment by nickbabcock** [comment]
`ExceptionMapper<JerseyViolationException>`: a `JerseyViolationException` contains `getInvocable` 😃 

A `JerseyViolationException` extends `ConstraintViolationException`

**Comment by jmoney8080** [comment]
HA! Thanks!  Using `ExceptionMapper<JerseyViolationException>` worked like a charm!  Thanks again!

**Comment by nickbabcock** [comment]
Glad to hear it! I'm going to keep this issue open until the docs get updated. Thanks for report
