### ISSUE TITLE
Dropwizard fails reading config.yml with Retrofit2 converter-jackson

### ISSUE THREAD

**Issue by chriskessel** [dropwizard/dropwizard#1792]
I'm on dropwizard 0.8 (1.0 has some sort of circular Jersey/Guice startup race condition) and I'm adding Retrofit2 as a way to talk to another REST service.

If I add in the dependency for Retrofit's jackson support to Gradle I'll see the following error. Not even using anything from it, just having added that dependency. Presumably some sort of low level initialization with yml->object mapping gets hosed and that's why it's failing to read the config.yml? 

Hoping for something I can change at startup, a way to tell Dropwizard not to look at the Retrofit classes?

If I take out that convert-jackson dependency line, the config.yml parsing works just fine again.

```
    compile group: 'com.squareup.retrofit2', name: 'retrofit', version: '2.1.0'
    compile group: 'com.squareup.retrofit2', name: 'converter-jackson', version: '2.1.0'
```
```
src/dist/config.yml has an error:
  * Unrecognized field at: server.requestLog
    Did you mean?:
      - adminConnectors
      - adminContextPath
      - adminMaxThreads
      - adminMinThreads
      - applicationConnectors
        [1 more]
```

**Comment by arteam** [comment]
Hi @chriskessel,

Sorry for a late reply. Could you try to exclude the `jackson-databind` dependency from `com.squareup.retrofit2:converter-jackson`? Dropwizard 0.8.* uses Jackson 2.5.1, but `converter-jackson` uses 2.7.2. Depending how your application is packaged, different versions of Jackson could be included in the jar distribution. I think there could be issues if the 2.7.2 version is included, because Dropwizard 0.8.* doesn't support it.

**Comment by chriskessel** [comment]
Excluding jackson-databind does seem to solve the problem:
```
   compile ('com.squareup.retrofit2:converter-jackson:2.1.0') {
        exclude module: 'jackson-databind'
    }
```

**Comment by nickbabcock** [comment]
Closing as it the issue seems resolved.
