### ISSUE TITLE
how can I read configurations from database instead of yml

### ISSUE THREAD

**Issue by ajak6** [dropwizard/dropwizard#1822]
I want to boot my application using configuration from database instead of yml file. I am not able to access the database in run method of my application.  getting following exception. I tried adding @unitofwork on the run method but same error. 
```Exception in thread "main" org.hibernate.HibernateException: No session currently bound to execution context
	at org.hibernate.context.internal.ManagedSessionContext.currentSession(ManagedSessionContext.java:75)
	at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:1014)
	at io.dropwizard.hibernate.AbstractDAO.currentSession(AbstractDAO.java:36)
	at io.dropwizard.hibernate.AbstractDAO.criteria(AbstractDAO.java:46)```

**Comment by arteam** [comment]
Hi @ajak6,

The issue is that you need to have an open transaction before accessing a database with Hibernate.
The `@UnitOfWork` annotation does precisely that, but it works only in the context of Jersey resources.
You have 2 options;
* You can use the declarative transactions with `@UnitOfWork`, but then you need to create your Hibernate DAO object with [UnitOfWorkAwareProxyFactory](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactory.java).
```java
new UnitOfWorkAwareProxyFactory("default", sessionFactory)
.create(UserDao.class, SessionDao.class, sessionDao)
```

* You can manage transactions manually, as described in the Hibernate [wiki article](https://developer.jboss.org/wiki/Sessionsandtransactions).
