### ISSUE TITLE
Cannot use parameter @Auth in parent resource

### ISSUE THREAD

**Issue by parkdcom** [dropwizard/dropwizard#1872]
We have a root/parent resource "Users", and a sub-resource "Vehicles".
For example: `/users/<id>/vehicles` will return the vehicles of the given user.

But before letting sub-resource "Vehicles" handle the request, we want to check if the currently authenticated user has access to data of the given user.
The reason is that there will be more than one endpoint in "Vehicles", and we would like to have one centralised access check in the parent resource "Users", instead of having to check in every endpoint of sub-resource "Vehicles".

But when using the @Auth parameter in the parent resource, like so (`@Auth User authedUser`):
```
@Path("{userId}/vehicles")
@RolesAllowed(Role.USER)
public Class<VehiclesResource> getVehicles(@Auth User authedUser, @PathParam("userId") Long userId) {
    return VehiclesResource.class;
}
```
the following exception is thrown:
`java.lang.IllegalStateException: Cannot inject a custom principal into unauthenticated request`

Is there a way to check the authenticated user in the parent resource?

**Comment by arteam** [comment]
Did you register `AuthDynamicFeature`? Please, see the [Authentication](http://www.dropwizard.io/1.0.5/docs/manual/auth.html#man-auth-basic) section in the docs. Usually this error message means that the `AuthFilter` wasn't created for the provided resource.

**Comment by getconcar** [comment]
Thanks for your fast response!

Yes, we indeed register `AuthDynamicFeature`:
```
env.jersey().register(new AuthDynamicFeature(
    new JwtAuthFilter.Builder<User>()
        .setJwtConsumer(consumer)
        .setRealm("realm")
        .setPrefix("Bearer")
        .setAuthorizer(new ParkdAuthorizer())
        .setAuthenticator(new JWTAuthenticator(guiceBundle.getInjector().getInstance(AuthManager.class)))
        .setUnauthorizedHandler(new JsonUnauthorizedHandler())
        .buildAuthFilter()));
```
Note that the `@Auth` parameter in other cases works fine. This problem only occurs when returning sub-resources, either using an instance of the sub-resource, or statically as in the given example of `Vehicles`.

Maybe the cause of this problem is related to #1352? But the OP of that issue didn't mind moving his `Auth` checks completely to the sub-resource. We however, for the reasons mentioned in the previous post, would like to check the authenticated user in the parent resource.

**Comment by getconcar** [comment]
@arteam Did you already have some time to look into this? Thanks!

**Comment by Gaudon** [comment]
Any update on this? I seem to be running into the same issue.

**Comment by whitfin** [comment]
Likewise, same issue; and it's not viable to move to the children due to the auth duplication it'll lead to.

**Comment by psamsotha** [comment]
The problem is that non-prematching filters are not called before the sub-resource locator method is called. At this point, the resource method has not been matched yet, so the filter is not called yet either. It gets called just prior to the resource method being called. And the authentication filter is what will set the `Principal` in the `SecurityContext`. When there is no `Principal` for the parameter injection, you will see this error message.

https://github.com/dropwizard/dropwizard/blob/7acede06f2df73f1db80461e44ba23708eb6bdd5/dropwizard-auth/src/main/java/io/dropwizard/auth/PrincipalContainerRequestValueFactory.java#L17-L24

**Comment by yp** [comment]
Same issue here. @parkdcom @whitfin @Gaudon how did you get around this issue?

**Comment by whitfin** [comment]
@yp I used the `@Auth` on the parent resource and then passed it through to the subresource, I think.

**Comment by splatch** [comment]
This issue is still valid for 2.0.6. I made my own filter and been struggling with it for half a day thinking that it is something wrong with my code. It turns out that my code is fine.

So to everyone who is still struggling with this one - as a workaround I marked my filter with `@PreMatching` annotation. It doesn't look right to me, but works. This bug (or feature) comes from Jersey code which sort filters in such a way that they are called after the sub-resource method chain is being called. There are at least two issues standing in Jersey project for quite long time eclipse-ee4j/jersey#3297 and eclipse-ee4j/jersey#3021.

Anyhow, hope it helps someone in future to solve the problem.
