### ISSUE TITLE
Feature Request: Support logging via syslog unix socket

### ISSUE THREAD

**Issue by jaredledvina** [dropwizard/dropwizard#1873]
Hi! I'm working on deploying an application that's using Dropwizard and am interested if it's possible for Dropwizard to support logging to a syslog unix socket (specifically it'd be `/dev/log`). I noticed in the docs here: http://www.dropwizard.io/1.0.5/docs/manual/core.html#syslog-logging that logging to a unix socket isn't support:
```
Because Java doesn’t use the native syslog bindings, your syslog server must have an open network socket.
```

Is this a strict limitation within Java? Or, would this be something Dropwizard could implement and simply hasn't based on need? Happy to provide any additional information that might help!

**Comment by joschi** [comment]
@jaredledvina
> Is this a strict limitation within Java?

Yes, it is. Java was designed to be platform-independent and thus doesn't support platform-specific features (like *UNIX* sockets) by default. There are 3rd party libraries taking care of this, though.

I'm not aware of any syslog appender for [Logback](http://logback.qos.ch/) which supports UNIX sockets, so you would probably have to write one yourself.

In conclusion, you might just want to open a UDP socket in your syslog daemon and bind it to `localhost` because everything else will cause additional work.
