### ISSUE TITLE
An HTTP body consisting of a single string is incorrectly deserialized

### ISSUE THREAD

**Issue by jroitgrund** [dropwizard/dropwizard#1894]
The following code

```
Path("/")
@Produces(MediaType.TEXT_PLAIN)
@Consumes(MediaType.APPLICATION_JSON)
public class Resource {
    @PUT
    @Path("endpoint")
    void endpoint(String jsonBody) {
        // resource code;
    }

}
```

behaves incorrectly. When posting `foo`, we have `jsonBody.equals("foo")`, when it should throw an error because `foo` is not JSON. When posting `"foo"`, we have `jsonBody.equals("\"foo\"")`, when it should be deserializing the string.

The same thing happens when returning `String` from a method (it's unquoted, whereas I would expect it to be quoted). The behavior I expect (throwing with no quotes and deserializing the quoted string) is consistent with what other frameworks do (e.g. Flask) and more intuitive.

**Comment by joschi** [comment]
@jroitgrund That's the standard behavior of JAX-RS/Jersey. The `MediaType` in the `@Consumes` annotation doesn't automatically validate the HTTP request body against that media type.

I'd recommend using a proper value class with appropriate `javax.validation` annotations instead of an untyped `String` in your JAX-RS method.
