### ISSUE TITLE
OSS dropwizard-views-jade ownership 

### ISSUE THREAD

**Issue by wuchenwang** [dropwizard/dropwizard#1906]
Hi DW Community,

Would dropwizard be interested in taking ownership/internalize this project  [dropwizard-views-jade](https://github.com/gethalfpintoss/dropwizard-views-jade)?

Our organization started to use this OSS project a while ago, we have since then uplifted our dependency on several dropwizard components, only to find that this project has tech debt that prevent us from staying up-to-date (some dropwizard-views changes would break it). 

We have logged several requests to the project to uplift, but due to it being inactive we haven't heard from it since (Actually the only commits made to the repo were several that made into one release). Since this is a small project dedicated for supporting jade template for view rendering, which is similar to what dropwizard have onboard for mustache and freemarker, would it make sense for you guys to take this OSS jade project in. 

Our organization could also contribute to this by making the necessary uplifts to work with latest release.

Thanks a lot,

Wuchen

**Comment by joschi** [comment]
@wuchenwang We're currently not interested in adopting any more projects into the Dropwizard core repository.

You might want to post to the [User Mailing List](https://groups.google.com/forum/#!forum/dropwizard-user) or the [Developer Mailing List](https://groups.google.com/forum/#!forum/dropwizard-dev) in order to find potential maintainers for the dropwizard-views-jade project.
