### ISSUE TITLE
JUnit 5 support in dropwizard-testing

### ISSUE THREAD

**Issue by ramsrib** [dropwizard/dropwizard#1944]
I think `dropwizard-testing` module doesn't support JUnit 5 yet.  Mainly the rules/class rules written in Junit 4 (in dropwizard-testing) doesn't work in Junit 5.

FYI, Frameworks like Mockito now officially supports JUnit 5.

**Comment by nickbabcock** [comment]
Thanks for filing a issue so we can track this improvement. I took a quick look at the [migration guide](http://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4). And since junit5 will support `ExternalResource`, it looks like the only code in `dropwizard-testing` that has to change (or be complemented) is `ResourceTestRule` which implements `TestRule`

**Comment by ramsrib** [comment]
Since Junit 5 has been released. It would be nice if someone updates the dropwizard testing documentation with JUnit 5 specific example.

**Comment by arteam** [comment]
Closed via #2166

**Comment by krupeshf** [comment]
@ramsrib where you able to test using JUnit5?  
As you mentioned, the documentation still points to JUnit4
https://www.dropwizard.io/1.3.9/docs/manual/testing.html#id2
