### ISSUE TITLE
Unknown class in Dropwizard guide

### ISSUE THREAD

**Issue by kahd1993** [dropwizard/dropwizard#1954]
I'm reading docs from dropwizard home. In Dropwizard core, in Configuration section, i see a **MessageQueueFactory.class** and **MessageQueueClient.class**, and the class **MessageQueueClient** have **close()** method, but i can't find **MessageQueueClient.class**'s location and don't know how to create **MessageQueueClient.class**.

Here is link to that docs and photo of code block in docs: [http://www.dropwizard.io/1.0.6/docs/manual/core.html](url)
![capture](https://cloud.githubusercontent.com/assets/13777242/23781452/fd2a7aae-057f-11e7-854f-0e895733c4c0.PNG)

Please help me how to create that **MessageQueueClient.class** , thanks so much! 
@tommorris @codahale @brianm @xaviershay @bretthoerner

**Comment by evnm** [comment]
That code block is a contrived example of how configuration factory classes work in Dropwizard.

As the preceding paragraph says, "if your application requires a set of configuration parameters in order to connect to a message queue, for example, we recommend that you create a new MessageQueueFactory class". The code block is simply show how one would _hypothetically_ go about implementing such a class.

Closing this issue, as the class in question is hypothetical, not missing.

**Comment by kahd1993** [comment]
@evnm thanks for your explain!
