### ISSUE TITLE
Improve "Organizing Your Project" section of Dropwizard Core manual

### ISSUE THREAD

**Issue by fabriziocucci** [dropwizard/dropwizard#1979]
In the `Organizing Your Project` section of the Dropwizard Core manual, I think the following could be improved:

> In general, we recommend you separate your projects into three Maven modules: project-api, project-client, and project-application.

> project-api should contain your Representations; project-client should use those classes and an HTTP client to implement a full-fledged client for your application, and project-application should provide the actual application implementation, including Resources.

It would be nice to provide a little bit more context on **why** splitting a Dropwizard project into those three modules is such a good idea. And if that's really the case, it would also be nice to update the [dropwizard-example](https://github.com/dropwizard/dropwizard/tree/master/dropwizard-example) to reflect this recommendation.

**Comment by nickbabcock** [comment]
The recommended structure is only for when one plans on distributing a java library for other developers to access their API. For instance, if we were to imitate [stripe's api](https://stripe.com/docs/api/java) we would setup our project as follows:

- `stripe-api` maven submodule. This project contains all the shared model code. The model is either used as a request or response object. For instance: `com.stripe.model.Charge` would be found here, as the server returns a `Charge` object to the client and client subsequnetly deserializes the payload into a `Charge` object on their end.
- `stripe-app` maven submodule is the Dropwizard app with server specific code
- `stripe-client` abstracts away the raw HTTP interactions and deserialization logic. The client library may also take care of connection pooling, and may provide a more friendly way of interpreting error messages. Basically, distributing a client library for your app will let other developers more quickly against the app.

If there is no reason to distribute a client library with your app then there is no reason to break up the code into different submodules. How to structure the code within a single project is a different matter. :smile:

**Comment by fabriziocucci** [comment]
@nickbabcock, I was exactly talking about describing the recommended structure by example highlighting the use case like you did! :+1: 

And I guess another source of confusion is related to what follows the recommendation:

> Our applications tend to look like this:
>-- com.example.myapplication:
>---- api: Representations.
>---- cli: Commands
>---- client: Client implementation for your application
>---- core: Domain implementation
>---- jdbi: Database access classes
>---- health: Health Checks
>---- resources: Resources
>---- MyApplication: The application class
>---- MyApplicationConfiguration: configuration class

Here it looks like `api` and `client` are actually packages of the same project, which is true for `api` if, as you said, you are not planning on distributing a java library for other developers. But then again, if that is the case, the `client` package doesn't make much sense there.

Ultimately, it would be nice to clarify that the recommended structure make sense if you want your microservice to be easily consumable by other (Java) microservices.

**Comment by nickbabcock** [comment]
The `client` package is used to house code that accesses other HTTP endpoints -- not your own endpoints. For instance, as client of Stripe, if we wanted to eschew Stripe's Java library and strictly access their HTTP JSON endpoints our own way, the code used for accessing / interpreting Stripe's API would be stored in the `client` package.

>it would be nice to clarify that the recommended structure make sense if you want your microservice to be easily consumable by other (Java) microservices

The easiest way to distribute access to your microservice is to document the API 😄 

In seriousness, and as an aside, there are many ways to create a client library, and it's made difficult because one often doesn't control the environment in which the client library is used. If we go back to our stripe example, [they use `java.net` classes](https://github.com/stripe/stripe-java/blob/035cd45bc9029a615c78c61bf8dbb51de75a301a/src/main/java/com/stripe/net/LiveStripeResponseGetter.java), which are low level and may be hard to get right, but at least one won't have to worry about dependency hell. Should one use jersey's client? Should one allow customizations to the jersey client? To shade or not to shade? I'm not sure what the current literature says about these questions, so I'm not going to make a statement how one should design their client apis.

I'll see if I can't spruce up the documentation a bit with this conversation.

**Comment by fabriziocucci** [comment]
> The client package is used to house code that accesses other HTTP endpoints -- not your own endpoints.

Way better this line than the one currently existing in the documentation! :smile: 

> In seriousness, and as an aside, there are many ways to create a client library, and it's made difficult because one often doesn't control the environment in which the client library is used.

In general, thas is unfortunately true for whatever library/framework...

> The easiest way to distribute access to your microservice is to document the API

Completely agree!
