### ISSUE TITLE
Jersey @Context injection is not possible on ConstraintValidator instances

### ISSUE THREAD

**Issue by mszabo-wikia** [dropwizard/dropwizard#2234]
Jersey runtime allows for `@Context` injection on `ConstraintValidator` instances ([see manual](https://jersey.github.io/documentation/latest/bean-validation.html#bv.injecting)) via its `InjectingConstraintValidatorFactory` that is configured as the default `ConstraintValidatorFactory` implementation.

Somewhere between Dropwizard 0.9.2 and 1.1.3, the implementation of `dropwizard-validation` has changed such that these injections are no longer possible. To reproduce, use `@Context` injection in the constructor or field of a custom `ConstraintValidator`, and set it to validate a resource method parameter.

Ideally, it should be possible to continue to make use of this useful Jersey feature.

**Comment by nickbabcock** [comment]
In 1.0 we moved validation away from Jackson's deserialization and into a Jersey feature. In both versions, the validator used is already pre-built (eg, there is no chance to inject using `ValidatorFactory::usingContext`), which leads me to believe that any `ConstraintValidator` referencing a `Context` variable in 9.2 would not be using Dropwizard's configured validator by a default validator.

I was able to get context injection to work for a custom `ConstraintValidator` but not in a backwards incompatible way using the below factory inside the `HibernateValidationFeature` class:

```java
private static class ConfiguredValidatorProvider implements Factory<ConfiguredValidator> {
    @Inject
    private Configuration configuration;
    @Context
    private ResourceContext resourceContext;

    @Override
    public ConfiguredValidator provide() {
        final ValidatorFactory factory = configuration.buildValidatorFactory();
        final ValidatorContext context = factory.usingContext();
        context.constraintValidatorFactory(resourceContext.getResource(InjectingConstraintValidatorFactory.class));
        return new DropwizardConfiguredValidator(context.getValidator());
    }
}
```

This is backwards incompatible as Dropwizard has a validator already constructed without `InjectingConstraintValidatorFactory` and I don't see a way to add this to an already constructed instance. So there are two solutions:

1. When initially constructing a validator, there might be a way to get jersey's `ResourceContext`. This is the preferable solution as it keeps backwards compatibility.
2. Change `HibernateValidationFeature` to receive a `Configuration` instead of `Validator`. I fear this would be a decently big change as a already built validator is used extensively in Dropwizard (yaml validation, jersey client code, server, dropwizard environment) -- but this is the only way I can confirm works.

**Comment by TK-999** [comment]
@nickbabcock Thanks for the quick response.

From a quick glance around there - it seems `Validators.newValidatorFactory` would provide us with a `ValidatorFactory` correctly configured with Dropwizard's Hibernate etc. settings. Then it could be invoked in a Jersey context, overriding `ConstraintValidatorFactory` with Jersey's implementation. What do you think?

**Comment by nickbabcock** [comment]
Yeah I think we're having the same thought. Using `Validators.newValidatorFactory` would require the following change though:

```diff
--- a/dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/HibernateValidationFeature.java
+++ b/dropwizard-jersey/src/main/java/io/dropwizard/jersey/validation/HibernateValidationFeature.java

 /**
  * Register a Dropwizard configured {@link Validator} with Jersey, so that Jersey doesn't use its
  * default, which doesn't have our configurations applied.
  */
 public class HibernateValidationFeature implements Feature {
-    private final Validator validator;
+    private final ConfigurationFactory factory;

-    public HibernateValidationFeature(Validator validator) {
+    public HibernateValidationFeature(ConfigurationFactory factory) {
         this.validator = validator;
     }
```
The `Validator`, (now) `ConfigurationFactory` that `HibernateValidationFeature` receives is / would come from the `Bootstrap` class which is what is initialized. So possibly the least intrusive way would be to add a `ConfigurationFactory` field to `io.dropwizard.setup.Environment` so that the configuration factory could flow downstream through all the classes until finally the `HibernateValidationFeature` is instantiated 😆

Maybe ... I'll have to ponder it, but this might be doable without too great of a disruption 🤔

**Comment by alex-shpak** [comment]
As an option I guess you can use one of DI integrations: with [HK2](https://github.com/alex-shpak/dropwizard-hk2bundle/tree/master/src/main/java/net/winterly/dropwizard/hk2bundle/validation) or [Guice](https://github.com/xvik/guice-validator) to inject into validators

**Comment by TK-999** [comment]
Yes, Guice " Swiss army knife" `Provider` injection works for this case :)

**Comment by nickbabcock** [comment]
I may totally be off here, but the Dropwizard repo doesn't use Guice, so we wouldn't want to add that dependency. And while HK2 is bundled with Jersey, we don't use HK2 internally for injection purposes when we own the path from instantiation to usage, so starting now would be tangential to current code (imo).

My purposed solution is setting up a `ValidatorFactory` for Jersey via HK2, but I haven't followed through long enough to see how backwards compatible it is.
