### ISSUE TITLE
Support bootstrap logging json format?

### ISSUE THREAD

**Issue by mattnelson** [dropwizard/dropwizard#2250]
Pulled in `1.3.0-rc4` to experiment with json logging before the release. Bootstrap logging[1] defaults to a traditional format. Should there be an option to flex bootstrap logging to json? In the use cases that all logs are sent to log processors (splunk, elk, etc..) they may not be configured to recognize the non-json log event.

> 22:10:37.601 [main] INFO org.eclipse.jetty.util.log - Logging initialized @414ms to org.eclipse.jetty.util.log.Slf4jLog
{"level":"INFO","logger":"io.dropwizard.server.DefaultServerFactory","thread":"main","message":"Registering jersey handler with root path prefix: /","timestamp":"2018-01-21T22:10:40.131Z"}

[1] https://github.com/dropwizard/dropwizard/blob/v1.3.0-rc4/dropwizard-logging/src/main/java/io/dropwizard/logging/BootstrapLogging.java

**Comment by nickbabcock** [comment]
Makes sense. While users can already override the bootstrap logging in their application classes, it does seem reasonable to provide convenience function for JSON log apps. The only (minor) concern I have is that since bootstrapping is done in code there could be a mismatch where the developer bootstraps as JSON, but config log format is traditional.
