### ISSUE TITLE
[Tests] InvalidKeyException: Illegal key size

### ISSUE THREAD

**Issue by nickbabcock** [dropwizard/dropwizard#2408]
#2390 introduced a keystore that appears can only be loaded if unlimited crypto strength is enabled. As a result, one of my machine's is no longer able to run dropwizard's test suite. @nheitz is there a way to decrease the key length to fit so that we don't require unlimited crypto strength.

```
ERROR [2018-06-22 22:17:46,949] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.io.IOException: exception decrypting data - java.security.InvalidKeyException: Illegal key size
! at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.cryptData(Unknown Source)
! at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
! at java.security.KeyStore.load(KeyStore.java:1445)
```

**Comment by arteam** [comment]
Good point. But, if I remember correctly, one of the points of using Bouncy Castle was to use custom keystores with big key sizes which are not supported by the default JVM ciphers. Still, it would be nice to have a stable test suite on all JVMs.

**Comment by nheitz** [comment]
ah right.  I may have difficulties compying with a shorter key setup. AS @arteam suggests, the main reason to bring in bouncycastle is to support stronger encryption in the PKCS12 container (i.e. AES256 with CBC) which definitely falls outside the standard Oracle JVM support.

I personally use openjdk because it doesn't have key size restrictions.

I can certainly add an "assume" style assertion at the top of the unit test to to check for AES key support, but then it is likely the test will never run!  Let me think on this.

**Comment by nickbabcock** [comment]
Alright, sounds good! I just know that if beginners want to run `dropwizard-example` project they'll need to run package on the whole repo, which means that they can be tripped up by this issue. Since this error message is not beginner friendly and unlimited strength crypto is a bizarre concept, I strive to make testing out / contributing to dropwizard as easy as possible 😄

**Comment by nheitz** [comment]
@nickbabcock 
I've (tentatively) pushed a fix for this issue, but I would appreciate if you could test it in your "reduced strength" env, as I struggled to be fully confident here.  Keystore and Truststore strengths have been dropped (AES -> 128, RSA -> 1024), so I'm anticipating success.
https://github.com/dropwizard/dropwizard/pull/2411

**Comment by jplock** [comment]
Fixed by https://github.com/dropwizard/dropwizard/pull/2411
