### ISSUE TITLE
EarlyEofExceptionMapper doesn't seem to work (<=Dropwizard 1.3.5)

### ISSUE THREAD

**Issue by winklehner** [dropwizard/dropwizard#2482]
As I see so far, dropwizard registers by standard some Exception Mappers, one of the is the EarlyEofExceptionMapper. Unfortunately though this mapper never seems to get called, as I'm seeing lots of those messages when a client aborts the transfer:

! java.io.IOException: Broken pipe
! at java.base/sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
! at java.base/sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
! at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:185)
! at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:132)
! at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:506)
! at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:266)
! ... 73 common frames omitted
! Causing: org.eclipse.jetty.io.EofException: null
...aso.

But this should be catched right? (org.eclipse.jetty.io.EofException) 

Am I missing something or is this a bug?

**Comment by winklehner** [comment]
Could it be that reason is null and not EOF?

**Comment by nickbabcock** [comment]
We have a test that confirms an eof exception mapper is hit when a client advertises it will send 100000 bytes, but it disconnects after sending a single byte. But there could be an edge case that you discovered. Do you have steps to reproduce?

**Comment by winklehner** [comment]
In my case its always caused when the server sends data to the client, but the client stops receiving or disconnects during transfer. I will try to build up a test case.

**Comment by nickbabcock** [comment]
Ah ok that makes sense. We don't have any tests for that! I can see that functionality slipping through the cracks.

**Comment by winklehner** [comment]
Great, than I can lean back and wait for an update ;)

**Comment by nickbabcock** [comment]
So I investigated this a bit today, and I'm not sure what the best solution is. The only two options are:

- Keep the current behavior
- Log the behavior under a different level

The reason being is that by the time the client has disconnected, the response code (and potentially body) have already been committed (this would change if one used http trailers, but afaik jersey doesn't support that feature). Since the response is already committed it won't hit an exception mapper.

Aside: The good news is that I can replicate that exception by eschewing an http client and closing a `Socket` as soon as the request is sent

**Comment by winklehner** [comment]
Okay. The reason I would like to get rid of this error, is that it floods the log with dumping the full stack trace. Isn't there any way to catch it with an CustomEOFException handler and just log e.g. "Client abort"?

**Comment by nickbabcock** [comment]
> Okay. The reason I would like to get rid of this error, is that it floods the log with dumping the full stack trace. Isn't there any way to catch it with an CustomEOFException handler and just log e.g. "Client abort"?

Agreed that is sensible. So 5 days ago, I said I could reproduce this issue, but I chucked the example code. I thought I'd be able to recreate it quickly, but apparently I'm wrong. Can you help me out and create a quick dropwizard example resource + test case that exhibits this behavior?

**Comment by nickbabcock** [comment]
No update, I lost my reproduction case and haven't been able to reproduce it since. If you have such a test case, we can further this issue.

**Comment by shail** [comment]
@nickbabcock I've only been able to test it by running a server (adding a `Thread.sleep` to an endpoint) and then running a `curl` command and hitting Ctrl-C to close the socket. I haven't been able to reproduce this in a test because by killing the client connection, the DropwizardAppRule never returns anything for the error.

**Comment by shail** [comment]
@nickbabcock I've narrowed down where the issue is arising I believe. When Jetty tries to handle writing the response, it uses the Jersey servlet which throws an EofException when it can't write to the client given the connection has been broken. If we use an ExceptionMapper which will again try to write to the client when returning the `Response` object, we'll get an EofException which doesn't get caught.

This is just a proof of concept, not really what we need:
https://github.com/shail/dropwizard/commit/6c709a5e678926a28dd197bf3f512dd1b63c1f66

**Comment by esiqveland** [comment]
Did you find a way to test/resolve this?

**Comment by nickbabcock** [comment]
This was closed by #2541
