### ISSUE TITLE
Log all request and response headers

### ISSUE THREAD

**Issue by cwagnello** [dropwizard/dropwizard#2556]
It would be nice to have a flag to allow all request headers and all response headers to be logged instead of having to specify which ones we want.

**Comment by eichstam** [comment]
Great idea, very useful.

**Comment by nickbabcock** [comment]
Can you expand a bit on your use case?

**Comment by eichstam** [comment]
My dropwizard services receives requests from many diverse clients. Occasionally I want to debug issues and would like to log all request headers so I can pick through any additional information passed along in headers. Since the client apps are diverse I don't know what all the possible headers are called.

**Comment by nickbabcock** [comment]
I forget, when you enable debug logging for jetty, does it log the headers?

**Comment by cwagnello** [comment]
I'm not sure. I don't see much in the Jetty logging docs about what gets logged.
