### ISSUE TITLE
CSV Injection through CsvReporterFactory.java

### ISSUE THREAD

**Issue by p-upadhyay** [dropwizard/dropwizard#2564]
CSV Reporter should be validating for CSV injection (as well as macros) before producing a .csv file?

**Comment by nickbabcock** [comment]
Hello, wrong project. Please see: https://github.com/dropwizard/metrics

Also, a tip. Make sure you when create an issue to more deeply explain the problem. The issue is vague and deprived of an example.

I'm assuming you are worried about creating a metric name which contains a column delimiter (eg: `,`) and/or security implications of opening a CSV which contained metric names [that can be interpreted](https://www.owasp.org/index.php/CSV_Injection). IMO this would be pretty low priority as no current metric names are susceptible to these issues. User created metrics should follow this lead.

**Comment by p-upadhyay** [comment]
Thanks Nick, I was not worried about metrics. I was actually worried about CSV injection via CSVReporterFactory.java.

Applications or framework when create a csv from untrusted data, that can be used in exploiting csv injection. I agree above comment was little vague and I should've given some more details. If you're already taking care of this or there is no untrusted data getting exported through this class or validated before the export, please ignore this issue. 
Also, please find below few references to CSV Injection

http://georgemauer.net/2017/10/07/csv-injection.html
https://www.owasp.org/index.php/CSV_Injection

**Comment by p-upadhyay** [comment]
Got it! Thanks.
