### ISSUE TITLE
Dependencies versions upgrade for 1.3.x line

### ISSUE THREAD

**Issue by usulkies** [dropwizard/dropwizard#2568]
I understand that most of the development efforts are focused on dropwizard 2.0.0 release - 
But, since 1.3.x is the current stable line of versions - I'd appreciate if some dependencies versions in dropwizard-bom can be done and released as dropwizard 1.3.8, where possible.
Especially:
jetty.version: 9.4.11.v20180605 -> 9.4.14.v20181114
jdbi3.version: 3.2.1 -> 3.5.1

I know that jersey version is more complicated to upgrade and breaks some compatibility, and might fit to be done only in version 2.0.0.

**Comment by eodonohoe** [comment]
I second the dependency bump, especially for jdbi3.

Encountered a strange issue with JDBI3 3.2.1 that is in Dropwizard 1.3.8 which I believe will be fixed by an upgrade to JDBI3 3.5.1.  The change has to due with ignoring static methods that may be in an interface.

I think this is due to the java compiler adding a static method that for a switch statement on an enum that is in one of our default methods on the interface.

java.lang.IllegalStateException: Method [CLASS_NAME_REMOVED].$SWITCH_TABLE$[METHOD_NAME_REMOVED] must be default or be annotated with a SQL method annotation.
! at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$buildMethodHandler$11(SqlObjectFactory.java:129)
! at java.util.Optional.orElseThrow(Optional.java:290)
! at org.jdbi.v3.sqlobject.SqlObjectFactory.buildMethodHandler(SqlObjectFactory.java:129)
! at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$9(SqlObjectFactory.java:120)
! at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
! at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$methodHandlersFor$10(SqlObjectFactory.java:120)
! at java.util.Map.computeIfAbsent(Map.java:957)
! at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2672)
! at org.jdbi.v3.sqlobject.SqlObjectFactory.methodHandlersFor(SqlObjectFactory.java:104)
! at org.jdbi.v3.sqlobject.SqlObjectFactory.attach(SqlObjectFactory.java:81)
! at org.jdbi.v3.core.extension.Extensions.lambda$findFor$0(Extensions.java:70)
! at java.util.Optional.map(Optional.java:215)
! at org.jdbi.v3.core.extension.Extensions.findFor(Extensions.java:70)
! at org.jdbi.v3.core.Jdbi.withExtension(Jdbi.java:435)
! at org.jdbi.v3.core.OnDemandExtensions.lambda$create$2(OnDemandExtensions.java:61)

**Comment by isaki** [comment]
If you use managed dependencies, you can just override the version. That being said, I might put together a PR with a few other library updates as well for 1.3.x if I get the time.

**Comment by joschi** [comment]
Jetty and jDBI have been updated in #2592 and #2591, respectively, and will be part of Dropwizard 1.3.9.

**Comment by petermant** [comment]
Since this contains breaking changes (according to the JDBI release notes) shouldn't it be 1.4.0 not 1.3.9?
