### ISSUE TITLE
Implementation of runtime/build time compilation to Jetty handler code

### ISSUE THREAD

**Issue by zloster** [dropwizard/dropwizard#2714]
The idea is from here: https://github.com/noboomu/proteus
`Proteus rewrites your controller methods into high performance Undertow response handlers at run time.`
The same thing should be possible to be implemented for Jetty handlers.

## What?
Basically the project is translating the JAX-RS annotated methods to Java code when the application is started. There is an example project: https://github.com/noboomu/proteus-example/

## Why?
On of the committers of this project (`dropwizard`) has a blog were he explored the performance impact of Jersey. And it was significant. The post is here: https://nbsoftsolutions.com/blog/turning-dropwizard-performance-up-to-eleven

## Drawbacks?
No dynamic endpoint creation. Probably problems with the DI (dependency injection) framework integrations. Probably a lot of other things that I can't point out currently.

**Comment by nickbabcock** [comment]
Interesting idea. Not sure it is a priority for maintainers to dedicate time to such a major task, but if a contributor came with a working version it's something that I'd consider (if only at the start, under an experimental flag)

> On of the committers of this project (`dropwizard`) has a blog were he explored the performance impact of Jersey. And it was significant. The post is here: https://nbsoftsolutions.com/blog/turning-dropwizard-performance-up-to-eleven

Hello, yes, author here. The caveat to the approach demonstrated is that one would need to benchmark adding back in some of the facets I disabled (like logging). Not sure how big the win would be otherwise. 😄
