### ISSUE TITLE
Context injection not working as expected in DW 2.0.0-rc1

### ISSUE THREAD

**Issue by matthias-mueller** [dropwizard/dropwizard#2781]
The following code works with __DW 1.3.9__ (_UriInfo_ and _CloseableService_ are properly injected), but fails with __DW  2.0.0-rc1__ (both fields are _null_ at runtime)

```java
import org.glassfish.jersey.server.CloseableService;
import javax.ws.rs.*;
import javax.ws.rs.core.*;

@Path("/upload")
public class UploadResource {

    @Context
    UriInfo requestUri;

    @Context
    CloseableService closer;
```

Is this expected behaviour in the 2.0 release?

p.s.: I use JUnit4 and the deprecated DropwizardAppRule for setting up test resources

```java
@ClassRule
    public static final DropwizardAppRule<UploadServiceConfiguration> RULE =
            new DropwizardAppRule<>(UploadServiceApplication.class, ResourceHelpers.resourceFilePath("uploadservice.yml"));
```

**Comment by joschi** [comment]
@matthias-mueller Thanks for reporting this!

Could you provide a minimal project to reproduce the issue?

**Comment by matthias-mueller** [comment]
@joschi Sorry for the delay.

Here's the minimal project: https://github.com/matthias-mueller/dropwizard-issue2781

**Comment by joschi** [comment]
@matthias-mueller Thanks for your effort and posting the reproducible example!

There is a small bug in your code, which causes the test to fail with Dropwizard 2.0.0-rc1 and Dropwizard 1.3.9, too.

In `InfoApplication#run()`, your registering an *instance* of `InfoResource` instead of the resource *class*, which means that the class fields with the `@Context` annotation (`requestUri` and `closer`) are `null` when creating a new instance.

If you're registering the resource class instead, Jersey (or more precisely HK2, the dependency injection framework used by Jersey) will take care of instantiating `InfoResource` and fill the class fields annotated with `@Context`.

As a side note, using `@Context` in method parameters also works when registering an instance of `InfoResource`.

Here's the changes needed to make your example application work with Dropwizard 1.3.9 and 2.0.0-rc1:

```diff
diff --git a/src/main/java/io/dropwizard/issue2781/InfoApplication.java b/src/main/java/io/dropwizard/issue2781/InfoApplication.java
index 4283a20..c3630b2 100644
--- a/src/main/java/io/dropwizard/issue2781/InfoApplication.java
+++ b/src/main/java/io/dropwizard/issue2781/InfoApplication.java
@@ -23,7 +23,6 @@ public class InfoApplication extends Application<InfoConfiguration> {

     @Override
     public void run(InfoConfiguration configuration, Environment environment) {
-        final InfoResource infoResource = new InfoResource();
-        environment.jersey().register(infoResource);
+        environment.jersey().register(InfoResource.class);
     }
 }
diff --git a/src/main/java/io/dropwizard/issue2781/resources/InfoResource.java b/src/main/java/io/dropwizard/issue2781/resources/InfoResource.java
index 6d85ba4..9f6b2fe 100644
--- a/src/main/java/io/dropwizard/issue2781/resources/InfoResource.java
+++ b/src/main/java/io/dropwizard/issue2781/resources/InfoResource.java
@@ -25,9 +25,10 @@ public class InfoResource {
     CloseableService closer;

     @GET
-    public String getInfo() {
+    public String getInfo(@Context UriInfo requestUriParam) {
         try {
             Objects.requireNonNull(requestUri);
+            Objects.requireNonNull(requestUriParam);
             Objects.requireNonNull(closer);
             LOGGER.info(requestUri.getRequestUri().toString() + " -- " + closer.getClass().toString());
             return requestUri.getRequestUri().toString() + " -- " + closer.getClass().toString();
```

**Comment by matthias-mueller** [comment]
@joschi I thought registering resource instances is perfectly legal because the documentation has such an example:

```java
@Override
public void run(ExampleConfiguration config,
                Environment environment) {
    // encapsulate complicated setup logic in factories
    final Thingy thingy = config.getThingyFactory().build();

    environment.jersey().register(new ThingyResource(thingy));
    environment.healthChecks().register("thingy", new ThingyHealthCheck(thingy));
}
```
(taken from: https://www.dropwizard.io/1.3.9/docs/manual/core.html#man-core-environments)

I didn't expect this to have side effects with context injection. (My application actually uses that mechanism because some of its resources require reference to an external object. The minimal example does not show that part though.) Have I missed something?

To be absolutely sure, I just double-checked that context injection with registered resource _instances_ did work with DW 1.3.9 and lower (My test environments use OpenJDK 8 or 11 if that matters).

**Comment by joschi** [comment]
Since it was working with Dropwizard 1.3.x (Jersey 2.25.2) and doesn't with Dropwizard 2.0.x (Jersey 2.28), I'll reopen the issue.

The "correct" way remains to register the class instead of a specific instance of the JAX-RS resource.

**Comment by matthias-mueller** [comment]
Since I was obviously not following the spec I am fine if this is closed. 2.0 In general I prefer fail-fast and this is now the case with DW 2.0 / Jersey 2.28.

**Comment by meshuga** [comment]
I believe the previous behaviour was unintended since it is to be expected not to do anything with an object that is being registered. That approach can be seen in e.g. Spring DI.

**Comment by joschi** [comment]
@meshuga I agree. So maybe let's add it to the release notes and the migration guide.

**Comment by nickbabcock** [comment]
Added this to the migration guide

**Comment by aahammedarkin** [comment]
I am facing the same issue and implementing the recommended changes in my application is challenging due to internal complexities related to resource object initialization.

While experimenting with a dropwizard sample application, I observed that context objects get injected correctly even for a registered resource instance, as long as they are injected at the method level as shown in the above patch. **Is this is a behavior that I can rely upon?**

On another note, I was going through some forums to understand if the behavior of the 1.3.x version of dropwizard was intentional. I could see that JAX-RS 2.1 specification [here](https://github.com/jax-rs/spec/blob/master/spec.pdf), section 10.1 suggests that implementations should provide a request-specific context even for those resources which don't have a per-request lifecycle

> Context is specific to a particular request but instances of certain JAX-RS components (providers and resource classes with a lifecycle other than per-request) may need to support multiple concurrent requests.
> When injecting an instance of one of the types listed in Section 10.2, the instance supplied MUST be capable of selecting the correct context for a particular request. Use of a thread-local proxy is a common way to
> achieve this.

Having said that, I am not sure if this is the right version of the JAX-RS specification that the jersey used in the dropwizard implements. But I am just curious to know what caused this change.
