### ISSUE TITLE
Website (dropwizard.io) does not redirect to HTTPS

### ISSUE THREAD

**Issue by nightowlengineer** [dropwizard/dropwizard#3073]
#2477 implies that dropwizard.io should 'always' be served over HTTPS (#1878 is also a useful read for some context). Currently, browsing to http://dropwizard.io serves the site up without HTTPS which looks like a regression.

**Comment by joschi** [comment]
@nightowlengineer Thanks for reporting this!

#2477 was reported when Dropwizard was still using GitHub Pages to serve the documentation. The project has since moved to ReadTheDocs.org.

In general, the documentation site is available via HTTPS:

* https://dropwizard.io/
* https://www.dropwizard.io/
* https://www.dropwizard.dev/

Unfortunately ReadTheDocs.org doesn't seem to redirect from HTTP to HTTPS at the moment, although it's been configured that way.

**Comment by joschi** [comment]
Seems this has been fixed on all relevant domains:

```
# for i in dropwizard.io www.dropwizard.io dropwizard.dev www.dropwizard.dev; do echo "GET $i:" ; curl -sI http://www.dropwizard.io | grep -E '^(Location|HTTP/1.1)'; done
GET dropwizard.io:
HTTP/1.1 302 Found
Location: https://www.dropwizard.io/en/latest/
GET www.dropwizard.io:
HTTP/1.1 302 Found
Location: https://www.dropwizard.io/en/latest/
GET dropwizard.dev:
HTTP/1.1 302 Found
Location: https://www.dropwizard.io/en/latest/
GET www.dropwizard.dev:
HTTP/1.1 302 Found
Location: https://www.dropwizard.io/en/latest/
```
