### ISSUE TITLE
malicious attack request

### ISSUE THREAD

**Issue by lp2jx0309** [dropwizard/dropwizard#3091]
valid request:  https://localhost:28005/test/test.js
malicious attack request:  https://localhost:28005/test/test.js;;";;alert(12);;s="

jetty server return PathInfo is : /test/test.js, how to avoid malicious attacks

            final StringBuilder builder = new StringBuilder(req.getServletPath());
            if (req.getPathInfo() != null) {
                builder.append(req.getPathInfo());
            }
            final CachedAsset cachedAsset = loadAsset(builder.toString());

**Comment by reneploetz** [comment]
Refer to this for avoidance stategies for this type of malicious requests: https://www.owasp.org/index.php/Reflected_File_Download

As per Servlet spec: Use ```javax.servlet.http.HttpServletRequest.getRequestURI()``` to get the unprocessed (raw) http request line.

**Comment by lp2jx0309** [comment]
thanks, reneploetz.but,
the code of question is the source code of dropwizard. Without modifying the source code, do I have any other ways besides adding a filter to filter out the attack URL? Does the dropwizard take this into account?

**Comment by joschi** [comment]
@lp2jx0309 You can add a [Servlet Filter](https://www.oracle.com/technetwork/java/filters-137243.html) to your Dropwizard application which drops or denies that kind of request.

See [`ServletEnvironment#addFilter()`](https://javadoc.io/static/io.dropwizard/dropwizard-project/2.0.0/io/dropwizard/jetty/setup/ServletEnvironment.html#addFilter-java.lang.String-java.lang.Class-).

**Comment by reneploetz** [comment]
This kind of parameters are not necessarily attacks - they are valid matrix parameters that can be handled in JAX-RS (via ```@javax.ws.rs.MatrixParam```).
The main problem can be that you return the values sent to your application as part of the response, hence the name "reflection attack". Note that the mentioned download attack is one of the issues - other is the possibility of a reflected XSS. Those issues are application-specific tough, because allowing matrix parameters or not is depending on the application as well as injecting user-sent content without application-specific validation can be problematic.

With the assets servlet that you mentioned, all of this is not relevant unless you would want to support matrix parameters within this resources. Only static resources are served which by definition cannot contain the passed parameters. Note that even passing those parameters might result in 404-errors as the static resources usually do not contain matrix parameters in their filename.
So while you can sent this request to a static resource, it lead to a resource without parameters being returned, but would have no security impact other than that (matrix parameters are simply ignored).

**Comment by lp2jx0309** [comment]
@reneploetz，Indeed, the static resources do not require matrix parameters. I added Filter to filter this matrix parameters request.

**Comment by lp2jx0309** [comment]
@reneploetz

Indeed, the static resources do not require matrix parameters. I added Filter to filter this matrix  parameters request.

**Comment by lp2jx0309** [comment]
@joschi 
thanks, I have added a filter
