### ISSUE TITLE
Custom Serialization/Deserialization in dependency

### ISSUE THREAD

**Issue by ashu101** [dropwizard/dropwizard#3111]
If there is some custom serialization/deserialization happening in a dependency included with dropwizard, dropwizard jersey is unable to identify it until unless the custom serializers/deserializers are registered manually via code with jersey.

```
@JsonSerialize(using = MapValueSerializer.class)
@JsonDeserialize(using = MapValueDeserializer.class)
public class MapValue extends Value {
//some code
}
```

Below has to be done explicitly to ensure that the ser/deser are available to jersey, which is not a nice way!
```
        environment.jersey().register(MapValueDeserializer.class);
        environment.jersey().register(MapValueSerializer.class);
```

If this is not done, jackson is not able to do ser/deser of `MapValue` and throws exception.

**Comment by ashu101** [comment]
any idea when this issue will be looked at?

**Comment by reneploetz** [comment]
I would like to understand your expected behaviour or error messages that occur, but I cannot reproduce your problem with the following testcase (Request ```http://localhost:8080/test``` and you will get "hello world" back):

```
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.dropwizard.Application;
import io.dropwizard.Configuration;
import io.dropwizard.setup.Environment;
import java.io.IOException;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

public class DropwizardTest extends Application<Configuration> {

    public static void main(final String[] args) throws Exception {
        new DropwizardTest().run("server");
    }

    @Override
    public void run(final Configuration configuration, final Environment environment) {
        environment.jersey().register(Resource.class);
    }

    @Path("/test")
    @Produces(MediaType.APPLICATION_JSON)
    public static class Resource {

        @GET
        public Value get() {
            return new Value("world");
        }
    }

    @JsonSerialize(using = ValueSerializer.class)
    public static class Value {

        private final String value;

        public Value(final String value) {
            this.value = value;
        }

        public String nonDefaultGetter() {
            return value;
        }
    }

    public static class ValueSerializer extends JsonSerializer<Value> {

        @Override
        public void serialize(final Value value, final JsonGenerator gen, final SerializerProvider serializers)
                throws IOException {
            gen.writeString("hello " + value.nonDefaultGetter());
        }
    }
}
```

As you can see, there is no need to register the ValueSerializer for it to be called, the ```@JsonSerialize``` annotation is enough.

**Comment by ashu101** [comment]
This issue happens when the custom serializer/deserializer are present for a class(A) which is in a dependency(X) and not in the dropwizard main application itself like it is shown above. The class(A) is not in the created dropwizard main packages.

**Comment by reneploetz** [comment]
Have a look at the attached test code - I did split the code above into modules.

Inside, there are two maven modules:
- a dto module that contains a Value class and the ValueSerializer to use
- an app module with the application and the resource class

If you build and run the module you should see the "hello world" when requesting "/test".

Can you modify the program so that it's possible to reproduce your issue? Or provide a different - ideally minimal - program that shows the issue?

[issue-3111.zip](https://github.com/dropwizard/dropwizard/files/4108366/issue-3111.zip)
