### ISSUE TITLE
Command line argument not working without configuration entry

### ISSUE THREAD

**Issue by karussell** [dropwizard/dropwizard#3145]
The PR #866 does not seem to fix #636 (tried dropwizard version 1.3.12) and also other people seem to have this issue. I.e. you have to specify a config.yml with at least:

```
server:
  applicationConnectors:
   - type: http
```

in order to change the port. Otherwise you'll get:

```
IllegalArgumentException: Unable to override server.applicationConnectors[0].type; node with index not found
```

Sorry have reposted here [again](https://github.com/dropwizard/dropwizard/issues/636#issuecomment-579227758) after 2 weeks, to avoid that this problem disappears in the closed issue.

**Comment by easbar** [comment]
The problematic code is here (current master): 

https://github.com/dropwizard/dropwizard/blob/4e201e02b4d438fd0cf6b9bb7ed8263cf7decc12/dropwizard-configuration/src/main/java/io/dropwizard/configuration/BaseConfigurationFactory.java#L189-L199

Instead of throwing an error one would have to add logic that adds the object/array nodes that appear in the overriding system properties but do not exist in the jackson tree yet. 

For example assuming the configuration file does not contain a `server` node, then in the above example

```shell
-Ddw.server.applicationConnectors[0].port=8888
``` 

one would have to add (in this order):

* an object node with key `server`
* an array of object nodes with (at least) one element with key `applicationConnectors` under the `server` node
* the `port` property under the first element of the `applicationConnectors` object node with value `8888`

There are some corner cases like:

```shell
-Ddw.server.applicationConnectors[3].myOtherList[12].port=8888
```
* need to create an array `applicationConnectors` with four elements (with the first three initially being empty)
* need to handle nested arrays

There can even be conflicts like this:
```shell
-Ddw.server.applicationConnectors[3].myNode.port=8888
-Ddw.server.applicationConnectors[3].myNode[12].port=8888
# oops is `myNode` supposed to be an array or an object?
```

Has this 'advanced' overriding functionality simply not been implemented in Dropwizard so far or was it left out intentionally? Does Jackson not also provides some support for 'merging' object trees? Maybe a better approach than the manual merging in `BaseConfigurationFactory` would be to first create a Jackson tree from the system properties and then merge this tree with the tree that was created from the configuration file.
