### ISSUE TITLE
Willingness to auto-register ThreadNameFilter for admin context?

### ISSUE THREAD

**Issue by accwebs** [dropwizard/dropwizard#4208]
One minor nuisance for me is that the admin context frequently behaves rather inconsistently compared to the app context.  While admittedly they are different things and have very different rules, is there openness to syncing the admin context up better with the app context?

If yes to the general question, then in particular, would there be openness to auto-registering the ThreadNameFilter per the same rules as the app scope?

Specifically, in AbstractServerFactory, we have:

```
protected Handler createAppServlet(Server server,
                                       JerseyEnvironment jersey,
                                       ObjectMapper objectMapper,
                                       Validator validator,
                                       MutableServletContextHandler handler,
                                       @Nullable Servlet jerseyContainer,
                                       MetricRegistry metricRegistry) {
        ... 
        if (enableThreadNameFilter) {
            handler.addFilter(ThreadNameFilter.class, "/*", EnumSet.of(DispatcherType.REQUEST));
        }
        ...
```

How about adding the same "if" block to createAdminServlet(...) such that if enableThreadNameFilter is true, we add the filter in both admin and app scopes?  

---

Is there openness to this type of change?  If so, happy to raise a PR.  

My one concern is that we should probably call this out in the release notes.  For instance, in case someone has manually been registering ThreadNameFilter themselves and then they upgrade to the new DW version, getting 2x registration without realizing it when they upgrade.  IDK.

**Comment by accwebs** [comment]
(remove stale)

**Comment by accwebs** [comment]
Try again to remove stale....

**Comment by accwebs** [comment]
Bump

**Comment by accwebs** [comment]
Bump

**Comment by zUniQueX** [comment]
Hi @accwebs. Sorry, it took a while to get to this.

Both contexts use the same `Server`, i.e. the same `QueuedThreadPool`. The `ThreadNameFilter` is only for debugging purposes to identify threads. This shouldn't make any difference for thr server's behavior.

Since the new thread name doesn't contain sensitive information, registering this filter shouldn't be a problem. I don't have a strong opinion whether to do this or not. But as you said, it would be a breaking change for users who already register this filter. So I'd rather integrate this in the next major version, if we decide to do so.

**Comment by accwebs** [comment]
Hi,

Thanks for your feedback.  For now I've moved on to other things so Dropwizard isn't super fresh in my mind.  I'd vote we close this issue for now (if you're okay with that) and next time I start doing serious work on Dropwizard I'll see about opening a PR. 

Thanks.
