### ISSUE TITLE
Ability to replace/disable JacksonMessageBodyProvider

### ISSUE THREAD

**Issue by Samiruaks** [dropwizard/dropwizard#4459]
Hello,

currently `JacksonMessageBodyProvider` is registered via `AbstractServerFactory#createAppServlet()` like this:
`jersey.register(new JacksonFeature(objectMapper));`

I want to register my own custom JacksonProvider and I'm doing it like this: `environment.jersey().register(MyCustomJacksonProvider());`

The problem is that with this implementation Jersey has two custom providers (one created by Dropwizard and another created by me) and it is resolved randomly by `org.glassfish.jersey.message.internal.MessageBodyFactory`.

My question - is there a possibility to disable Dropwizard registered `JacksonMessageBodyProvider` or replace it in order to have only one custom provider?

**Comment by zUniQueX** [comment]
Once a feature is registered, it may not be overridden or unregistered. So if you want to have a custom `JacksonFeature`, you have to prevent Dropwizard from registering the default one.

The only option I currently see for this is to provide a custom `ServerFactory`. Since `createAppServlet` is `protected`, you could extend `DefaultServerFactory` and override the method with your custom behaviour.

**Comment by mattnelson** [comment]
Does adding a non-default/higher priority on the custom provider take precedence over the dropwizard registered instance?

https://jakarta.ee/specifications/platform/8/apidocs/javax/annotation/priority

**Comment by zUniQueX** [comment]
In the [Jersey docs](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/message-body-workers.html#providers-selection) the selection algorithm doesn't specify it would handle `@Priority` annotations.

But you could try explicitly setting json as media type, since the default Jackson provider [uses `MediaType.WILDCARD`](https://github.com/FasterXML/jackson-jaxrs-providers/blob/2.14/json/src/main/java/com/fasterxml/jackson/jaxrs/json/JacksonJaxbJsonProvider.java).

**Comment by zUniQueX** [comment]
@Samiruaks any luck with providing a custom provider with a more specific media type?

**Comment by mattnelson** [comment]
> In the [Jersey docs](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/message-body-workers.html#providers-selection) the selection algorithm doesn't specify it would handle `@Priority` annotations.

I suggested it based on this comment > https://github.com/eclipse-ee4j/jersey/issues/3473#issuecomment-460624390

**Comment by zUniQueX** [comment]
> I suggested it based on this comment > https://github.com/eclipse-ee4j/jersey/issues/3473#issuecomment-460624390

Then it should be explicitly stated in the selection algorithm IMO. If it works anyway, then we should report this to the Jersey team to update their docs.
