### ISSUE TITLE
PolymorphicAuthValueFactoryProvider issue when upgrading to v2

### ISSUE THREAD

**Issue by liriarte** [dropwizard/dropwizard#4471]
I am getting the following error after upgrading to v2

`final AbstractBinder binder = new PolymorphicAuthValueFactoryProvider.Binder<>(
                                                                                    ^
    reason: no instance(s) of type variable(s) T,E exist so that Binder<T> conforms to AbstractBinder
  where T,E are type-variables:
    T extends Principal declared in class Binder
    E extends Object declared in method <E>of(E,E)
`

The code is pretty standard and was working before the upgrade.

```
final PolymorphicAuthDynamicFeature<?> feature = new PolymorphicAuthDynamicFeature<>(
            ImmutableMap
                .of(MyPrincipal.class, myfilter,
                    MyPrincipal2.class, myfilter2));

        final AbstractBinder binder = new PolymorphicAuthValueFactoryProvider.Binder<>(
            ImmutableSet.of(MyPrincipal.class, MyPrincipal2.class));

        environment.jersey().register(feature);
        environment.jersey().register(binder);
```

Please help.

**Comment by zUniQueX** [comment]
Do your custom principal classes both implement `Principal`?

**Comment by liriarte** [comment]
Yes

**Comment by zUniQueX** [comment]
Okay. I was just curious of the error message related to the type unification.

**Comment by liriarte** [comment]
I don't think it would have worked with the previous version if those classes did not implement `Principal`

**Comment by zUniQueX** [comment]
Yes, you're correct. The error message was just a bit misleading.

I figured out, what your problem is. Since Jersey now uses its own `InjectionManager` for DI and doesn't rely on HK2's `ServiceLocator` [any more](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/user-guide.html#mig-2.26-injection-manager), your `AbstractBinder` import should be incorrect now. The proper import for Dropwizard 2 is now `org.glassfish.jersey.internal.inject.AbstractBinder`.

**Comment by zUniQueX** [comment]
@liriarte did this solve it for you?

**Comment by liriarte** [comment]
@zUniQueX yes it did. many thanks!
