### ISSUE TITLE
Setting logging appender target as lowercase "stdout" or "stderr" failure

### ISSUE THREAD

**Issue by yingliu928** [dropwizard/dropwizard#5243]
- Dropwizard version 2.1x

- Issue description: 
   In the [Dropwizard Console Logging Doc](https://www.dropwizard.io/en/latest/manual/core.html#console-logging) as well as javadoc of the `ConsoleAppenderFactory Class`, both indicate that the `target` property can be a lowercase word `stderr` or `stdout`. However, this setting failure is exposed when we are using customized JSON Deserialization in the application as following:
   ```java
        bootstrap.getObjectMapper()
        .enable(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE);
   ```
   and addressed out the logging appender's target setting in `test-example.yml` and `example.yml`:

   ```yaml
   appenders:
       - type: console
         # add target for test
         target: stdout
  ```

   Exception is thrown as following:
   ```bash
   [ERROR] com.example.helloworld.IntegrationTest  Time elapsed: 0.456 s  <<< ERROR!
   io.dropwizard.configuration.ConfigurationParsingException: 
   test-example.yml has an error:
     * Incorrect type of value at: logging.appenders.[0].target; is of type: String, expected: ConsoleStream

   Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: 
   Cannot deserialize value of type `io.dropwizard.logging.ConsoleAppenderFactory$ConsoleStream` from String "stdout": not 
   one of the values accepted for Enum class: [STDERR, STDOUT]  at [Source: UNKNOWN; line: -1, column: -1] (through reference 
   chain: com.example.helloworld.HelloWorldConfiguration["logging"]- 
   >io.dropwizard.logging.DefaultLoggingFactory["appenders"]->java.util.ArrayList[0]- 
   >io.dropwizard.logging.ConsoleAppenderFactory["target"])

   ```
- Issue can be reproduced by `git clone` this [dropwizard-example forked branch](https://github.com/yingliu928/dropwizard/tree/test-target).
   run`mvn clean install` after `git clone`, the above exception will be thrown.
  Also,  [this PR](https://github.com/yingliu928/dropwizard/pull/1) shows the modifications from the original `dropwizard-example` repo to expose this issue.

The exception won't be thrown when ommitting out the `target` property in `test-example.yml`  or using the default JSON Deserialization settings. In this case, I assume the default setting "STDOUT" is being used.

This exception won't be thrown when passing an uppercase word `STDOUT` or `STDERR` as the value to the target. So it indicates that the `enum ConsoleStream` Class won't accept lowercase words for the `target` property, which contradicts the [Dropwizard Console Logging Doc](https://www.dropwizard.io/en/latest/manual/core.html#console-logging) as well as the javadoc for the `ConsoleAppenderFactory` Class.

**Comment by zUniQueX** [comment]
Hi @yingliu928, thanks for reporting this. The issue should be caused [here](https://github.com/dropwizard/dropwizard/blob/release/2.1.x/dropwizard-jackson/src/main/java/io/dropwizard/jackson/FuzzyEnumModule.java#L83). In the default configuration, the `FuzzyEnumModule` from Dropwizard ensures the property is deserialized correctly when using the lowercase values. Therefore the docs are fine for common use cases. However, when using one of the three Jackson features listed in the linked class, the custom deserializer won't be used.

Updating the docs won't help us much because this is a problem for all enum values, what you already experienced at commenting out the 'health' configuration.

As the `FuzzyEnumModule` does more than just ignore cases, we could use the [`MapperFeature#ACCEPT_CASE_INSENSITIVE_ENUMS`](https://www.javadoc.io/static/com.fasterxml.jackson.core/jackson-databind/2.13.2.2/com/fasterxml/jackson/databind/MapperFeature.html#ACCEPT_CASE_INSENSITIVE_ENUMS) as a fallback strategy.

@dropwizard/committers I'd put a vote for enabling the `MapperFeature#ACCEPT_CASE_INSENSITIVE_ENUMS` by default. As the `FuzzyEnumModule` is also registered by default, this shouldn't be a behavior change, the custom deserializer still gets invoked and the value is parsed correctly. Any concerns against that?

**Comment by yingliu928** [comment]
@zUniQueX Thanks for the feedback!
