### ISSUE TITLE
Custom logFormat should use the configured timeZone

### ISSUE THREAD

**Issue by maffe** [dropwizard/dropwizard#5733]
I tried to add the time zone to log entries. According to the [logback documentation](https://logback.qos.ch/manual/layouts.html#date), this should work by adding [`%d{z}`](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html) (or adding `z` to an existing `%d` pattern). And indeed, a time zone appears, but it’s not the one [configured with `timeZone`](https://www.dropwizard.io/en/latest/manual/configuration.html#console), but the system default.

I’ve found #3530 but I don’t really see the need for `%dwTimeZone`. `%d{z,%dwTimeZone}` would work but I think any `%d` pattern without the timezone parameter should use the one set by `timeZone`. I’m not entirely sure but the following line could be the one causing `%d{z}` to display the system default timezone.
https://github.com/dropwizard/dropwizard/blob/1b652299c64af16cf617bff702f0003c33a606ee/dropwizard-logging/src/main/java/io/dropwizard/logging/BootstrapLogging.java#L54

I use Dropwizard 2.0.28 but this doesn’t seem to have changed in 2.1.x.

**Comment by cleiner** [comment]
The `%d` patterns are handled by Logback's `DateConverter` which only sets a custom time zone if it's included in the pattern:

https://github.com/qos-ch/logback/blob/4eb2914cb65214d13e14a9ed3dfb9f044df98358/logback-classic/src/main/java/ch/qos/logback/classic/pattern/DateConverter.java#L52-L56

Otherwise the `SimpleDateFormat` in `CachingDateFormatter` will always use `TimeZone.getDefault()`.

To override this behavior, Dropwizard would have to parse the `logFormat` string and figure out where to insert the time zone ID before passing the format to Logback. I think this would potentially result in a much more complicated and fragile implementation than the `%dwTimeZone` placeholder.

Also, the Logback documentation you linked explicitly says 
>  Note that in the absence of the timezone parameter, the default timezone of the host Java platform is used.

So automatically modifying the `logFormat` string might even be seen as unexpected behavior.

**Comment by maffe** [comment]
Thanks for the explanation. I did not expect any other timezone to be used in the logging than the one configured by the appender’s `timeZone` parameter but I see why this is the case now. I will add `%dwTimeZone` to my pattern.
