### ISSUE TITLE
Vulnerability issue in io.dropwizard.modules:dropwizard-jdbi:jar:2.1.1

### ISSUE THREAD

**Issue by zZToasterZz** [dropwizard/dropwizard#5870]
After running the OWASP Dependency checker against the dropwizard, one vulnerability is raised against dropwizard-jdbi:jar 2.1.1 dependency which is brought in:
snakeyaml-1.31.jar: CVE-2022-38752
<img width="554" alt="image" src="https://user-images.githubusercontent.com/79910936/190184791-e9bb62ea-0f5d-4a43-9d38-f31b24878862.png">

**Comment by zUniQueX** [comment]
Jackson [already upgraded](https://github.com/FasterXML/jackson-dataformats-text/commit/2c163ff0ef15b534df6f266f07fdc7bfae2ffdcf) to snakeyaml 1.32, but hasn't provided a release yet.

**Comment by zUniQueX** [comment]
The upgrade to snakeyaml 1.32 was reverted in the Jackson 2.13 branch because they had to introduce an option to configure the limit of the YAML file. So Jackson 2.13 probably won't upgrade to snakeyaml 1.32. Dropwizard isn't immediately affected by the vulnerability, since we don't use the YAML format for user supplied input.

Dropwizard 2.1.x won't upgrade to Jackson 2.14, as @joschi pointed out in [this comment](https://github.com/dropwizard/dropwizard/pull/6177#issuecomment-1310504117). So I'll close this issue for now.
