### ISSUE TITLE
jackson-databind vulnerability CVE-2022-42003

### ISSUE THREAD

**Issue by snehal-d** [dropwizard/dropwizard#6095]
There is jackson-databind 2.13.4 vulnerability CVE-2022-42003 in the most recent version of dropwizard. 
com.fasterxml.jackson.core_jackson-databind - In FasterXML jackson-databind before 2.14.0-rc1
Is there any plan to mitigate this issue? Please suggest!

**Comment by tmack8001** [comment]
There were a few micro patches to jackson-databind to solve this. In order to get those fixes Dropwizard would need to upgrade to the latest jackson bom, https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13#micro-patches

There have been two of such patches so far to 2.13.4.x (.1 and .2) both added last week (two were needed due to a issue in the gradle module). So we should updaate to 2.13.4.2 via jackson-bom version 2.13.4.20221013

**Comment by tmack8001** [comment]
This work has already been done, just no release has been made yet. https://github.com/dropwizard/dropwizard/commit/d605cd900b617b7051d004ca3447bcad7e4e1bad for reference was the dependency bump commit for this specific issue.

**Comment by tmack8001** [comment]
I'll defer to @joschi on when to cut a new v2.1.4 for the 3 or 4 CVEs that are currently unreleased.

**Comment by joschi** [comment]
Dropwizard 2.1.4 has been released and should be available on Maven Central soon.

https://github.com/dropwizard/dropwizard/releases/tag/v2.1.4
