### ISSUE TITLE
Add ability to limit "message" length for "JSON Layout"

### ISSUE THREAD

**Issue by dude-abides** [dropwizard/dropwizard#6266]
We use ELK for logging and have configured it to build indexes based on JSON messages. If the message size exceeds 8k it gets truncated by ELK and it is no longer valid JSON and subsequently not included in the indexes. If JSON Layout can limit the message size, this problem goes away. ELK is always going to have a limit. If we can't assure the output of Logback is within that limit, we lose the JSON based message processing ELK provides.

**Comment by zUniQueX** [comment]
Hi @dude-abides. What do you exactly mean by limiting the message size? If we would apply truncation in the layout, wouldn't we then also lose part of the message or am I misunderstanding you there?

**Comment by dude-abides** [comment]
Set a limit on the "message" size. In the dropwizard configuration it shows many fields for JSON Layout [timestamp, threadName, level, loggerName, message, mdc, exception, etc.].

In the ideal scenario it would calculate size of all other fields and truncate the message field to fit a maximum size, like 8k.

The main issue:
- log processing tools like ELK stack have a limit on the length of log lines
- if the log line exceeds this limit, ELK truncates the log line
- the log line is no longer valid JSON and is useless and cannot be indexed

With a valid JSON log line, it is indexed and I can search by http status, log level, thread name, etc.

Please ask more question if this is not clear. We are about to abandon JSON based indexes because of this issue.

**Comment by zUniQueX** [comment]
Hi @dude-abides. I personally can't think of a case, where I'd like to have my log messages truncated to avoid information loss. That's why I wouldn't want to add this to the framework as a core feature. Since you can manually use a layout factory which suits your needs, I don't think we'll have to provide this in the framework. If somebody else will request this feature, we can integrate it later.

To accomplish the message truncation you describe, you'll have to extend the JSON layout factory you're using, e.g. `EventJsonLayoutBaseFactory`. The formatting of the JSON is done in the `JsonFormatter`, which can be overridden in the `createDropwizardJsonFormatter()` method. The following code describes a simple (yet not that efficient) way of applying message truncation based on the size of the other included attributes. It's just a starting point, feel free to adjust it.
```java
@Override
protected JsonFormatter createDropwizardJsonFormatter() {
    return new CustomJsonFormatter(Jackson.newObjectMapper(), isPrettyPrint(), isAppendLineSeparator());
}

public static class CustomJsonFormatter extends JsonFormatter {
    private static final int MAXIMUM_JSON_SIZE = 8192;

    public CustomJsonFormatter(ObjectMapper objectMapper, boolean prettyPrint, boolean doesAppendLineSeparator, int bufferSize) {
        super(objectMapper, prettyPrint, doesAppendLineSeparator, bufferSize);
    }

    public CustomJsonFormatter(ObjectMapper objectMapper, boolean prettyPrint, boolean doesAppendLineSeparator) {
        super(objectMapper, prettyPrint, doesAppendLineSeparator);
    }

    @Nullable
    @Override
    public String toJson(@Nullable Map<String, Object> map) {
        if (map == null || map.isEmpty()) {
            return null;
        }
        if (!map.containsKey("message") || !(map.get("message") instanceof String)) {
            return super.toJson(map);
        }
        String messagePlaceholder = "<MESSAGE_PLACEHOLDER>";
        Map<String, Object> clonedMap = new HashMap<>(map);
        clonedMap.put("message", messagePlaceholder);
        String json = super.toJson(clonedMap);
        if (json == null) {
            return null;
        }
        String message = (String) map.get("message");
        int endIndex = Math.min(message.length(), MAXIMUM_JSON_SIZE - (json.length() - messagePlaceholder.length()));
        return json.replace(messagePlaceholder, message.substring(0, endIndex));
    }
}
```
(This is experimental code - only a few simple cases are tested -, it may not work correctly in every case).

This factory would generate a layout according to your request. To adjust the size of the output JSON, you'll need to update the `MAXIMUM_JSON_SIZE` constant. (Ideally, you'll make this a configuration option for the new layout factory). To use the newly created layout factory, you'll have to provide a `@JsonTypeName("<custom-json-layout-name>")` annotation and a file `META-INF/services/io.dropwizard.logging.layout.DiscoverableLayoutFactory` that contains the FQCN of the factory class. Then you can use the layout factory by referencing it with the name you've specified in the `@JsonTypeName` annotation.

**Comment by mattnelson** [comment]
I have experienced similar issues with splunk(10k limit) and typically with events with long stack traces.

There are some options available with config only changes to reduce the size of the message. 
https://www.dropwizard.io/en/latest/manual/configuration.html#exception

- Ensure root first exceptions are configured, this is the default. When exceptions are wrapped multiple times the true cause is at the end of the default stack trace. Using root first puts that information at the top of message. And while it may no longer be valid json when truncated, at least you have the more relevant information in that event.
- Coupled with limiting stack trace depth, even with deep stacks(100s of call sites deep) I've found I really only need the last ~20 stack elements to know with a reasonable degree of accuracy the cause of the issue.
- Filter noisy packages from the stack elements.

**Comment by dude-abides** [comment]
I do filter stack traces. The existence of this feature shows there is a concern about data length.

The Logback developers recognize the need for truncating data as well.

https://logback.qos.ch/manual/layouts.html

Look at Format Modifiers.

Example:
%.30logger
Truncate from the beginning if the logger name is longer than 30 characters.

I appreciate your time @zUniQueX and will try your solution. Note: It does not look like your solution JSON escapes the message data.

I think I need to escape the data, the truncate without interrupting an escape sequence.
