### ISSUE TITLE
doc: Getting started refers to 2.x-SNAPSHOT as latest 

### ISSUE THREAD

**Issue by OneCricketeer** [dropwizard/dropwizard#7225]
ref. https://www.dropwizard.io/en/latest/getting-started.html#tutorial

I assume at one point this was being automatically updated? But doesn't answer how it got stuck at a snapshot release?

edit: I see the rst uses a release variable. Maybe an ordering issue with cutting the 2.x branch and overriding the docs?

**Comment by OneCricketeer** [comment]
Similar for Upgrade Notes and Other Versions page. Newer versions aren't mentioned

**Comment by joschi** [comment]
@OneCricketeer Thanks for reporting this! ❤️ 

The problem was indeed that `latest` was still pointing to the `release/2.1.x` branch as its source. I've changed it to `release/4.0.x` and rebuilt that documentation version.

**Comment by OneCricketeer** [comment]
I still feel the tutorial should use the latest release? Not refer to a snapshot?

**Comment by joschi** [comment]
> I still feel the tutorial should use the latest release? Not refer to a snapshot?

I agree, this has been a tradeoff we chose to reduce the manual effort for maintaining this particular part of the documentation.

These code snippets are real, runnable projects, for example https://github.com/dropwizard/dropwizard/blob/release/4.0.x/docs/source/examples/getting-started/pom.xml, and as such they show the _latest_ state of the `release/4.0.x` branch.

This being said, the `stable` documentation is based on the latest Git tag and there it's showing the latest release version:
https://www.dropwizard.io/en/stable/getting-started.html#tutorial

I'll try making `stable` the default target instead of `latest` on ReadTheDocs.
