### ISSUE TITLE
Security issue: Data representation leaks because validation takes places before authentication

### ISSUE THREAD

**Issue by X3Cutor** [dropwizard/dropwizard#768]
Reported this on the mailing list and was asked to create an issue. I'm attaching some basic code to illustrate the problem.

My application
```
public class TestApplication extends Application<Configuration> {

    public static void main(String[] args) throws Exception {
        new TestApplication().run(args);
    }
    @Override
    public void initialize(Bootstrap<Configuration> configurationBootstrap) {

    }

    @Override
    public void run(Configuration configuration, Environment environment) throws Exception {
        environment.jersey().register(new BasicAuthProvider(new SecuredResourcesAuthenticator(),"SecuredEndpoints"));
        environment.getObjectMapper().disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
        ValidatedResource resource = new ValidatedResource();
        environment.jersey().register(resource);
    }
}
```

My resource
```
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@Path("/greet")
public class ValidatedResource {

    @POST
    @Timed
    @ExceptionMetered
    public Object createSolution(@Valid TransportObject validatedObject,@Auth Object userPlaceholder) throws JsonProcessingException {
        String response = "Hello";
        return response;
    }
}
```

The object with "secret" internal representation I only want authenticated people to know about
```
public class TransportObject {

    @NotNull
    @Size(min = 1)
    @Pattern(regexp="some_regexp_here")
    private String given_name;

    public String getGiven_name() {
        return given_name;
    }

    public void setGiven_name(String given_name) {
        this.given_name = given_name;
    }
}
```

The class that "handles" authentication by denying everybody
```
public class SecuredResourcesAuthenticator implements Authenticator<BasicCredentials,Object> {

    @Override
    public Optional<Object> authenticate(BasicCredentials credentials) throws AuthenticationException {
        //Deny everybody access
        return Optional.absent();
    }
}
```

I'm using dropwizard 0.7. A POST to http://localhost:8080/greet after the service has been started with an empty JSON body gives the following response:
```
{
errors: [1]
0:  "given_name may not be null (was null)"
-
}
```

After  getting that info I POST
```
{
    "given_name": ""
}
```
And get basically the full internal representation of this rather simple resource
```
{
errors: [2]
0:  "given_name must match "some_regexp_here" (was )"
1:  "given_name size must be between 1 and 2147483647 (was )"
-
}
```
Now that I figured out how it works, I can POST
```
{
    "given_name": "some_regexp_here"
}
```
And only then am I asked for credentials, which I don't have (valid one's that is) in the first place.

**Comment by glennmcallister** [comment]
I've created pull request #891 which has a couple of tests which verify that this data leakage no longer occurs in Dropwizard 8.x (current master). Presumably this issue was also discovered by the Jersey folks and they addressed it, and we've been the beneficiaries of that. I'd just like a couple of pairs of eyes to go over the tests to make sure I haven't missed anything or if there are any other tests I should add, which I'm happy to do.

**Comment by carlo-rtr** [comment]
I'll take a stab at recapping what was found in https://github.com/dropwizard/dropwizard/pull/891

Jersey provides the parameters to a resource method in the order they are defined in the resource.

So if the @Auth param is first, the rest of the parameters will short circuit when the AuthFactory throws an exception because the user is invalid.

However, if the first parameter is @Valid SomeBean, that will go thru validation and return any validation errors before being authenticated because the @Auth param is defined after SomeBean

I can think of few options:

[1] Say this is a limitation and document very well. "If you do auth, it must be the first param"
[2] Do the security in a filter, which I think would happen before calling the resource method. I think this would mean some annotation on the resource method. Since the resource method may need the principal, we can have the filter call ContainerRequestContext#setProperty with the principal. We can then create a provider for a principal parameter which knows to look there. This means you would need the method annotation and the principal parameter annotation. TBH, I think this would work but would need to do a POC to be sure

https://jersey.java.net/documentation/latest/security.html

**Comment by jplock** [comment]
I personally like option 2 as I've been trying to use the `@RolesAllowed` annotations to handle authorization in my application which required me to implement my own `SecurityContext` and request filter to set `request.setSecurityContext()`.  Then in the resources, you have to fetch the principal from the `@Context SecurityContext sc`.

**Comment by carlo-rtr** [comment]
@jplock I put some work into this. Let me know if it's the right the direction.
https://github.com/dropwizard/dropwizard/compare/master...carlo-rtr:auth_rewrite?expand=1

* I want to think a little bit more about the class names and abstractions
* I want to see if I can create a Provider to encapsulate reading the attribute and casting to a type. To make it easier to access a typed principal other than one that's a String.

**Comment by carlo-rtr** [comment]
d5410fbb22df73e7e086cde3538b014a0b2c6e5f

**Comment by X3Cutor** [comment]
Nice to see that the issue is being fixed, although I won't be upgrading to a version of dropwizard that incorporates the fix anytime soon so I'll have to make due with the workaround. I couldn't help but notice the following line though: "Fixed security issue where info is leaked during validation of unauthenticated resources(#768)", surely that should say "authenticated resources"?

**Comment by glennmcallister** [comment]
Depends on your point of view, I suppose. The principle attempting to
obtain the resource resource has not been authenticated when the data is
being leaked. The resource has been marked as requiring authentication, but
the leak occurs before the authentication stage occurs in the original
issue.

Perhaps a better wording would be "Fixed security issue where info is
leaked during validation of resource requiring authentication"?

**Comment by ryankennedy** [comment]
It looks like this comes with some pretty significant user-facing API changes. Can someone sum the changes up (I keep losing a mental list as I scroll through commit d5410fb)? The API changes appear to be more feature development (role-based auth) than bug fixing. Maybe I missed the discussion around the API changes, but this seems like something the committers may want to have a quick discussion and vote on.

There's a little bit of context lost between Feb. 22nd and March 10th in this thread where the issue was reopened. But it looks like if we reordered the parameters internally (we could generate a proxy object) then Jersey could be made to do the right thing, which would fix this bug without introducing the API change.

The original authentication API was intentionally pretty simple. From quickly looking at the diffs in the commit, the changes to user applications appear to be significant.

**Comment by carlo-rtr** [comment]
The high level description is that auth now happens at the filter level, not at parameter injection. This means that information isn't leaked when parameters that fail to validate are listed before the auth parameter. Doing auth at the filter level, meant we could use provided authentication & authorization filters. So we did that, that's why it feels like a slight feature upgrade. The bulk of the implementation conversation happened starting May 10th in this issue, and in this PR https://github.com/dropwizard/dropwizard/pull/945

**Comment by carlo-rtr** [comment]
We have had some discussions on the mailing thread: https://groups.google.com/forum/#!topic/dropwizard-user/1xNzJe7GpV8

Given we have merged the provider, the changes to the API don't seem that dramatic. If other community members want a simpler approach to Auth, I think they can put something together and share it. I don't think we should keep the old auth under a separate module, and leave that security risk. I know we do that at the risk of upsetting some people, but I think that's going to be inevitable.
