### ISSUE TITLE
JerseyClient not reporting metrics

### ISSUE THREAD

**Issue by mabn** [dropwizard/dropwizard#789]
JerseyClientBuilder does not register any metrics. In particular JerseyClientBuilder.builder is not used for anything - it's possible to pass various parameters (JerseyClientConfiguration, HttpRequestRetryHandler, etc), but they are ignored.

That affects v0.8.0-rc1

**Comment by arteam** [comment]
Good, #791 added metrics for `ConnectionManager`. 

But unfortunately request timers remained not reported. I guess that because Jersey [ApacheConnector](https://github.com/jersey/jersey/blob/master/connectors/apache-connector/src/main/java/org/glassfish/jersey/apache/connector/ApacheConnector.java) doesn't expose a way to set a custom `HttpRequestExecutor`, so we can't instrument the client.
We can't override or delegate this connector because it's package-protected.
What options do we have?

* Report an issue to Jersey and wait for possible resolution
* Shade Jersey `ApacheConnector` to *dropwziard-client* and maintain it separately 
* Write own Connector
* Embrace absence of request timer metrics for Jersey client

Personally I more inclined to the second option.

**Comment by cmicali** [comment]
@arteam It does solve it, but it needs to be merged and DW updated for that, and given the current pace of metrics progress I'm nervous it may never happen :worried:
