### ISSUE TITLE
Shouldn't Tasks get their parameters from the body rather than the url

### ISSUE THREAD

**Issue by RichoDemus** [dropwizard/dropwizard#838]
Currently Tasks get their parameters from the URL of the request rather than the POST body of the request. I'm no HTTP expert but I believe it would be more correct to get them from the body instead

**Comment by arteam** [comment]
I don't the original reasoning of this design, but one benefit of query parameters against a POST body is that they are a part of URI. Because of that they are logged in HTTP access log of any web server (as well in Dropwizard).

This fact simplifies the job of people who maintains applications. They can easily derive from logs which parameters were passed to tasks. With a POST body you need to do logging manually, which can lead to non standard logging implementations or forgetting to log at all.

**Comment by scottaj** [comment]
I recently ran into a situation where having access to the request body would have been useful. I wanted to make a data loading task task that could take a large blob of JSON data. I was surprised that `Task`s could not access the POST request body.

Would you be opposed to a PR that provided access to the request body to the `Task` object? I think there are probably a lot of situations where it could be useful. The URL parameters would could still be used as the main configuration method that makes sense to me, but it would make providing larger amounts of data to a task easier.

**Comment by nickbabcock** [comment]
@scottaj, sorry for the late response, but yes a PR that allows access to the request body would be welcomed.

**Comment by nickbabcock** [comment]
Closed by #1606
