### ISSUE TITLE
JerseyClient does not respect keepAlive parameter

### ISSUE THREAD

**Issue by mabn** [dropwizard/dropwizard#849]
JerseyClient does not respect keepAlive parameter - underlying HttpClient uses DefaultConnectionKeepAliveStrategy. If the server does not specify keep-alive timeout in the response headers the connection will survive in the connection pool until it's closed.

In case of idle connections they tend to be closed on the server side (which connection pool is unaware of). The result is that the next request:
- leases a (stale) connection from the pool
- sends the request
- tried to read from the underlying socket but fails
- invalidates the connection and retries
AFAIR there are 2 retry attempts (retry configuration is also ignored).

In addition it's not possible to easily fix it because the client is built inside the constructor of org.glassfish.jersey.apache.connector.ApacheConnector (which is package-protected). 
It's not possible to change ConnectionKeepAliveStrategy via reflection because the field in question is final.

I see following options:
1 - spawn a separate thread which will periodically expunge idle connections - see http://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html#d5e405
2 - write own version of ApacheConnector which builds underlying HttpClient correctly (could reuse HttpClientBuilder here). It would mean reverting pull request #791 and doing it differently, but it would fix all the things that were broken in JerseyClient in 8.0

I think the 2nd seems to be the best as it would allow to have the same code/bahavior of HttpClient in both cases (when using jersey or apache clients)

**Comment by TheTweak** [comment]
+1, I've created an issue in Jersey's JIRA about keepAlive a month ago https://java.net/jira/browse/JERSEY-2736

**Comment by pparth** [comment]
+1

I really don't understand how Dropwizard team is discussing about actually releasing a 0.8 version without supporting the ability to properly configure Jersey Client's keepalive and retry policies.

**Comment by joschi** [comment]
@pparth That's simple: Until now nobody seemed to require it really (there wasn't any bug reported on this before) and it's something we can easily fix in a patch release (i. e. Dropwizard 0.8.1).

**Comment by pparth** [comment]
Comparing to Dropwizard 0.6.X, Jersey Client support in 0.8.X is actually crippled. Most of the configuration options are not even there. I have the feeling that we are not talking here about "bugs" but large sections of missing functionality that was previously supported and it somehow got missed in the latest versions. 
Nevertheless, we will try to add bugs for each and every one of them if you feel that this is the way we should handle them.

**Comment by arteam** [comment]
I've recently started to work to a custom version of [`ApacheConnector`](https://github.com/arteam/dropwizard/blob/dropwizard_jersey_apache/dropwizard-client/src/main/java/io/dropwizard/client/DropwizardApacheConnector.java) for the Jersey client.
It uses a pre-configured Apache's *CloseableHttpClient* by *HttpClientBuilder* rather than configures one from parameters on the fly.

Its more concise and, as I believe, more reasonably designed then the stock one.
And, more importantly, it correctly behaves according to the configuration. 

If I am not mistaken and I didn't make some blunders during implementation, it should close all open problems with Jersey Client.

There is a lot a work to do (testing, documentation, review), but I think it's the right approach
with integration Apache and Jersey clients. 

Also unfortunately using this approach means we should revert the approach taken in #791 with a base class of the common configuration.

**Comment by TheTweak** [comment]
@arteam cool, are you going to propose it for official usage in Dropwizard, when it would be done? Btw there is another issue new ApacheConnector could fix: #863
