### ISSUE TITLE
Throwing exception to the client

### ISSUE THREAD

**Issue by edpichler** [dropwizard/dropwizard#873]
I followed the instructions here http://dropwizard.io/manual/core.html#error-handling but nothing is being throwed to the client.

I must inherit the WebApplicationException or do I can throw directly a WebApplicationException object?
I just need to throw it from a resource method?

Any more concrete example on internet? The documentation is not good on this part

PS: I' m really enjoying using this framework. Lot of hours saved!

**Comment by MarkHerhold** [comment]
I can answer some of your questions because I have recently been investigating the issue myself. but don't know what the best practices are. Take my answers with a grain of salt.

> I must inherit the WebApplicationException or do I can throw directly a WebApplicationException object?

If you are like me, you will want an application/JSON response to result from throwing an exception.
You need to create your own exception class by **extending** `WebApplicationException`.

```java
/**
 * A HTTP 409 (Conflict) exception that produces an application/JSON response.
 */
public class MyConflictException extends WebApplicationException {
	/**
     * Create a HTTP 409 (Conflict) exception.
     */
    public MyConflictException() {
        super(Responses.conflict().build());
    }
    
    /**
     * Create a HTTP 409 (Conflict) exception.
     * @param message the String that is the exception message of the 409 response.
     */
    public MyConflictException(String message) {
        super(Response.status(Responses.CONFLICT).
                entity(new JSONExceptionMessageContainer(message)).type(MediaType.APPLICATION_JSON).build());
    }    
}
```

JSONExceptionMessageContainer:
```java
/**
 * Simple container for mapping an exception message to a JSON object
 */
public final class JSONExceptionMessageContainer {
	private String message;

	public JSONExceptionMessageContainer(String message) {
		this.message = message;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}
}
```


> I just need to throw it from a resource method?

Yes. Do `throw new MyConflictException("something conflicted!")`

> Any more concrete example on internet? The documentation is not good on this part

Tell me about it! Here are some pages I have open right now:

[Jersey - WebApplicationException and Mapping Exceptions to Responses](https://jersey.java.net/documentation/latest/user-guide.html#d0e6500)

[SO - Return Jersey exceptions in JSON](http://stackoverflow.com/questions/15111134/return-jersey-exceptions-in-json)

[SO - JAX-RS / Jersey how to customize error handling?](http://stackoverflow.com/questions/583973/jax-rs-jersey-how-to-customize-error-handling)

[Dropwizard and Jersey ExceptionMappers](http://thoughtspark.org/2013/02/25/dropwizard-and-jersey-exceptionmappers/)

You may also want to look into ExceptionMappers as a part of Jersey, which some of these links talk about.

**Comment by edpichler** [comment]
Wow, excelent answer @MarkHerhold 
Thanks! Now it's clear and working.

**Comment by leodangal** [comment]
Thanks!  @MarkHerhold
