### ISSUE TITLE
Dropwizard doesn't support HTTP trailers

### ISSUE THREAD

**Issue by fmurray-r7** [dropwizard/dropwizard#8762]
Dropwizard doesn't seem to support HTTP [trailer response headers](https://datatracker.ietf.org/doc/html/rfc2616#section-14.40), despite trailers being supported by [jetty](https://github.com/jetty/jetty.project/issues/612).

Is this something that can be added, considering it is supported by the underlying library and is part of the HTTP specifications?

**Comment by zUniQueX** [comment]
Hi @fmurray-r7. Since Jetty supports trailers, dropwizard supports them as well.

Trailers can be set through the servlet api. To do that, you'll inject the `HttpServletResponse` in your resource method and set the trailers:
```java
@GET
public String helloWorld(@Context HttpServletResponse response) {
    response.setTrailerFields(() -> Map.of("Testkey", "Testvalue"));
    return "Hello World!";
}
```

To check, if the trailers are set correctly, you can use the Jetty client:
```java
ContentResponse response = client
        .newRequest("http://localhost:8080")
        .method(HttpMethod.GET)
        .onResponseSuccess(response1 -> {
            if (response1 instanceof HttpResponse httpResponse) {
                System.out.println(httpResponse.getTrailers());
            }
        })
        .send();
```

**Comment by fmurray-r7** [comment]
Ah, my mistake, thank you for the clarification!
