### ISSUE TITLE
Request Logs do not provide valid user field

### ISSUE THREAD

**Issue by abuchanan920** [dropwizard/dropwizard#898]
It seems that the authentication schemes of Jetty and Dropwizard don't communicate enough information for the request logs to include the user field.

The user field would definitely be useful for identifying how much usage was being generated by different api users or identifying which users are still using an older version of the api so they can be targeted for upgrade, etc.

It looks like io.dropwizard.jetty.Slf4jRequestLog extends org.eclipse.jetty.server.AbstractNCSARequestLog which does the actual creation of the message.

In that class we see:

```
            Authentication authentication = request.getAuthentication();
            if (authentication instanceof Authentication.User)
                buf.append(((Authentication.User)authentication).getUserIdentity().getUserPrincipal().getName());
            else
                buf.append(" - ");
```

In all of my logs, I only ever see "-" for the user, although dropwizard basic authentication seems to be working correctly. I can't find anywhere in the code where it attempts to push the user info back into the Jetty world for logging to work correctly though.

Am I missing something?

Thanks!
Andrew

**Comment by glennmcallister** [comment]
You aren't missing anything. The Dropwizard and Jetty authentication
mechanisms are currently more or less completely disconnected. When I was
satisfying auditing requirements I had to add my own logging handler class
to write out auth results in JSON format to a separate file, based on a
separate logger I had instantiated in my authentication class.

And yes, I agree this is something that could be improved upon. However,
the problem is that we are effectively doing authentication as part of
parameter processing rather than as a filter, as it's typically done. We
are planning on looking into this in more detail to address a known defect
(see issue #768) post the 0.8 release.

Glenn

**Comment by yvandb** [comment]
Is there any update on this issue? @glennmcallister? It seems dw 0.9 moved to filter based authentication, however jetty still doesn't pick up the user identity for the requestlog. 
Thank you very much for your attention.

**Comment by asiletto** [comment]
@yvandb I think if you are using a filter based authentication, you can try to set the user name as said here: https://groups.google.com/forum/#!topic/dropwizard-user/lVP0nDI-NT4

**Comment by glennmcallister** [comment]
Sorry, I've long since been doing next to nothing with Dropwizard; no time
and a bit handcuffed by my current employer for various reasons. That being
said, from what I know, given the current authentication model employed by
DW there is likely no reason why this can't be supported, it just hasn't
been looked at.

**Comment by yvandb** [comment]
Thanks @asiletto @glennmcallister 
I'm using an AuthFilter similar to the one in the documentation: http://www.dropwizard.io/0.9.1/docs/manual/auth.html
I doubt that this is the best way to get to the jetty Request, but it sure does the job:

```
Request request = HttpChannel.getCurrentHttpChannel().getRequest();
if (request != null) {
  UserIdentity userId = new DefaultUserIdentity(null, principal.get(), null);
  request.setAuthentication(new UserAuthentication(null, userId));
}
```

**Comment by ianferguson** [comment]
Is there anything that can be done to get this included in a future version of Dropwizard? Adding the code @yvandb to AuthFilter.java at the end of the authenticate method immediately prior to the `return true` on line 165 should fix this
