### ISSUE TITLE
Vote: should we add something like this to the docs?

### ISSUE THREAD

**Issue by carlo-rtr** [dropwizard/dropwizard#911]
My guess is that having it laid out like this is useful, but could easily go stale.

https://groups.google.com/d/msg/dropwizard-user/Om_N_4WIZfQ/0U03LI8oZC0J

**Comment by glennmcallister** [comment]
Keeping on top of it is the primary issue. Otherwise, I'm all for clarity. Having that laid out somewhere in the documentation would be great in my opinion.

**Comment by arteam** [comment]
I find it extremely useful.

We could create "Dropwizard Internals" section in the docs, where we can post such guides.

About keeping it relevant, I believe that not writing a documentation just because it's hard to maintain is a lame excuse. If we would start to write about internals, we will motivate more people to hack on Dropwizard. Community should help us to find mistakes and improve quality and relevance of the docs.

**Comment by carlo-rtr** [comment]
Okay. I like the ideas. I'll work on it.

**Comment by carlo-rtr** [comment]
https://github.com/dropwizard/dropwizard/pull/918

**Comment by joschi** [comment]
Closed by merging #918.
