### ISSUE TITLE
BasicAuthFactory in dropwizard-testing.

### ISSUE THREAD

**Issue by phxql** [dropwizard/dropwizard#922]
I'm trying to get the `BasicAuthFactory` in dropwizard testing to work. As stated in the documentation, I'm using `GrizzlyTestContainerFactory` as test container factory. `BasicAuthFactory` still isn't working because `@Context private HttpServletRequest request;` isn't injected. I also tried `GrizzlyWebTestContainerFactory`, this throws an exception:

```
java.lang.IllegalArgumentException: The deployment context must be an instance of ServletDeploymentContext.
	at org.glassfish.jersey.test.grizzly.GrizzlyWebTestContainerFactory.create(GrizzlyWebTestContainerFactory.java:85)
	at org.glassfish.jersey.test.JerseyTest.createTestContainer(JerseyTest.java:277)
	at org.glassfish.jersey.test.JerseyTest.setUp(JerseyTest.java:609)
	at io.dropwizard.testing.junit.ResourceTestRule$1.evaluate(ResourceTestRule.java:157)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
```

How to test basic auth protected resources?

**Comment by scho** [comment]
Have you tried the way it is done here:
https://github.com/dropwizard/dropwizard/blob/master/dropwizard-auth/src/test/java/io/dropwizard/auth/oauth/OAuthCustomProviderTest.java

It worked for me, except that I couldn't assert the result in case of a non-200 response (we render json with some error information, but grizzly always renders html/text).

Another idea:
Have you tried to test it with an integration test and the [DropwizardAppRule](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-testing/src/main/java/io/dropwizard/testing/junit/DropwizardAppRule.java)?

**Comment by vultron81** [comment]
I am also having issues getting ResourceTestRule to work with BasicAuthFactory and GrizzlyTestContainerFactory for v0.8.0.  I tried to implement what was done in the OAuthCustomProviderTest.java code but no matter what I do I get a HTTP 401 error.  Also my custom Authenticator is never called.  Below is how I am initializing the ResourceTestRule:

@ClassRule
    public static final ResourceTestRule resources = ResourceTestRule.builder()
            .setTestContainerFactory(new GrizzlyTestContainerFactory())
            .addProvider(AuthFactory.binder(new BasicAuthFactory<User>(new CustomAuth(), "Test-Realm", User.class)))
            .addResource(new MyResouce())
            .build();

I then call my resource in my tests via:
Response response = resources.getJerseyTest().target("/mypath")
                .request(MediaType.APPLICATION_JSON)
                .header(HttpHeaders.AUTHORIZATION, "user pass")
                .post(Entity.json("blah"));

I have also tried using the HttpAuthenticationFeature unsuccessfully. Any help would be appreciated.

**Comment by glennmcallister** [comment]
I have an example here of several basic authentication tests:
https://github.com/dropwizard/dropwizard/pull/891. Again thanks to @joshi
for beefing the tests up for me. :)

Note that 2 of them are failing as expected due to a known issue, hence the
failing TravisCI build. They are based off of existing tests in the
dropwizard-auth module.

**Comment by vultron81** [comment]
Thanks Glenn.  I was able to get it working by using your example and properly formatting the Authorization header.  However, I am a little disappointed I could not get it to work using the ResourceTestBuilder() and instead having to inherit from the JerseyTest class.

**Comment by glennmcallister** [comment]
If I get some spare time (HA!) I'll see if I can take a shot at getting it
to work with ResourceTestBuilder. I hadn't tried testing this part of the
system before so I simply copied what was there and built off of it. It's
possible the ResourceTestBuilder is missing some necessary plumbing, I
dunno.

**Comment by moxie0** [comment]
Is this not an upgrade-blocker for most dropwizard users? Maybe I'm unusual, but almost every resource across every dropwizard service I run is auth-protected.

Should I bite the bullet and rewrite every resource test across every service I maintain to use JerseyTest instead of ResourceTestRule, or is fixing this on the roadmap for the next dropwizard release?

**Comment by carlo-rtr** [comment]
I spent some time looking at this. Here is what I found:

1. I'm pretty sure you can't use the in-memory test container, instead you must use the grizzly one. [Relevant discussion](http://stackoverflow.com/questions/13283542/whats-the-difference-between-the-different-jersey-test-containers)

2. Even if you configure ``ResourceTestRule`` to use ``GrizzlyWebTestContainerFactory``, and replace [this] with 
```
@Override
protected DeploymentContext configureDeployment() {
return ServletDeploymentContext.builder(resourceConfig)
       .initParam(ServletProperties.JAXRS_APPLICATION_CLASS,              ResourceTestResourceConfig.class.getName()).build();
}
```
There are still issues. I think the problem is that ResourceTestRule uses a dynamicResourceConfig. In the other authorization tests that work, ResourceConfig is extended and defined statically. The reason this matters is because the Grizzly container will create an instance of your ResourceConfig via reflection every time there is a request, not just on initialization. So what this means, is that zero arg constructor gets called, but the post init steps never happen. I tried subclassing ResourceConfig but still configuring dynamically. This requires dependency injecting a handle to the ResourceTestRule, so the configuration can happen on every request. I couldn't get the plumbing to work.

I'm feeling like the fluent interface for testing isn't going to be possible with tests that require Auth. I hope someone can prove otherwise.

**Comment by ferdy-lw** [comment]
After a couple of hours hacking around with this, there is a solution, albeit inelegant. As per Carlo's solution (see his branch), if you configure `ResourceTestRule` to use `GrizzleyWebTestContainerFactory` and set the `DeploymentContext` to a `ServletDeploymentContext` you still run into the issue of the `ResourceConfig` being reflectively created.

I'd really like to be able to test my resources using the resource rule; however, all my resources require `@Auth`.

Instead of using DI you can simply hold onto a static reference. In the `ResourceTestRule` class add a static class of the `DropwizardResourceConfig`, and construct it with the rule when building the `ServletDeploymentContext`. When Grizzly constructs the ResourceConfig the static reference to the rule will already be there and can be used to register providers again.

```java
public static class ResourceTestResourceConfig extends DropwizardResourceConfig {

    public static ResourceTestRule msResourceTestRule = null;  // Keep a reference to the RULE

    public ResourceTestResourceConfig(ResourceTestRule rule) {
        msResourceTestRule = rule;
    }

    public ResourceTestResourceConfig() {
        super(true, new MetricRegistry());

        ResourceTestRule resourceTestRule = msResourceTestRule;

        for (Class<?> provider : resourceTestRule.providers) {
            register(provider);
        }
        for (Map.Entry<String, Object> property : resourceTestRule.properties.entrySet()) {
            property(property.getKey(), property.getValue());
        }
        register(new JacksonMessageBodyProvider(resourceTestRule.mapper, resourceTestRule.validator));
        for (Object singleton : resourceTestRule.singletons) {
            register(singleton);
        }
    }
}


@Override
public Statement apply(final Statement base, Description description) {
    final ResourceTestRule rule = this;
    return new Statement() {
        @Override
        public void evaluate() throws Throwable {
            try {

                test = new JerseyTest() {
                    @Override
                    protected TestContainerFactory getTestContainerFactory() throws TestContainerException {
                        return testContainerFactory;
                    }

                    @Override
                    protected DeploymentContext configureDeployment() {
                        return ServletDeploymentContext.builder(new ResourceTestResourceConfig(rule))
                                    .initParam(ServletProperties.JAXRS_APPLICATION_CLASS, ResourceTestResourceConfig.class.getName())
                                    .build();
                    }
                };
                test.setUp();
                base.evaluate();
            } finally {
                if (test != null) {
                    test.tearDown();
                }
            }
        }
    };
}
```

**Comment by carlo-rtr** [comment]
@ferdy-lw thanks for looking. I thought about doing it with a static reference, but I think that will be problematic in a multithreaded testing environment. If multiple tests with rules that differ are run concurrently that static ref is shared mutable state with no lock protection.

**Comment by ferdy-lw** [comment]
Good point. What about using ThreadLocal to store the rule?

Another path I looked at but couldn't figure out how to do was setting the [ServletProperties.SERVICE_LOCATOR](https://jersey.java.net/apidocs/2.17/jersey/org/glassfish/jersey/servlet/ServletProperties.html#SERVICE_LOCATOR) to the locator you created when making the deployment context. I'm not sure how that property is used.

**Comment by alph486** [comment]
Thanks @ferdy-lw for the insight and workaround. This is all unfortunately complex considering setting up Auth in production is a simple matter of registering an `AuthFactory`. I'm sure most folks would expect this work similarly when configuring a `ResourceRule` and adding a provider.

**Comment by ferdy-lw** [comment]
@alph486 the proposal is internal to the rule, the way you use it should be exactly the same as before, so no additional complexity.

```java
private static final RunDao msRunDao = mock(RunDao.class);
private static final UserDao msUserDao = mock(UserDao.class);
private static final BasicAuthenticator msAuthenticator = new BasicAuthenticator(msUserDao);

@ClassRule
public static final ResourceTestRule RESOURCES = ResourceTestRule.builder()
        .setTestContainerFactory(new GrizzlyWebTestContainerFactory())
        .setIsServletContext(true)
        .addProvider(AuthFactory.binder(new BasicAuthFactory<>(msAuthenticator, AuthBundle.BASIC_REALM, User.class)
                .responseBuilder((prefix, realm) -> AuthBundle.BASIC_FAILURE_RESPONSE)))
        .addProvider(GeneralExceptionMapper.class)
        .addResource(new WFRRuns(msRunDao))
        .build();
```

@carlo-rtr ThreadLocal wont work as the grizzly container runs the requests in a separate worker thread. The problem with using the service locator property is it used as an attribute in `WebComponent` and the way I see to get it into the attribute is through a `ServletContextListener`, which is registered in the `ServletDeploymentContext` as a listener class, and I see no way to get closure over the rule.

However, staying on the same path as before, instead of a single static test rule reference I got it to work via a map whose key is the rule hash, when creating the servlet deployment context the rule hash can be included as an init parameter. When the `ResourceConfig` is constructed the servlet config (and init params) are injected so it can lookup the rule for that config. (I've also changed the impl. to handle both servlet and non servlet contexts.)

```java
public static final String RULE_ID = "io.dropwizard.testing.junit.resourceTestRuleId";
public static class ResourceTestResourceConfig extends DropwizardResourceConfig {

    public static Map<String, ResourceTestRule> msResourceTestRule = new HashMap<>();

    public ResourceTestResourceConfig(String ruleId, ResourceTestRule rule) {
        super(true, new MetricRegistry());
        msResourceTestRule.put(ruleId, rule);
        ResourceTestResourceConfig.configure(this, rule);
    }

    public ResourceTestResourceConfig(@Context ServletConfig servletConfig) {
        super(true, new MetricRegistry());
        ResourceTestResourceConfig.configure(this, msResourceTestRule.get(servletConfig.getInitParameter(RULE_ID)));
    }

    public static Application configure(ResourceTestRule resourceTestRule) {
        return ResourceTestResourceConfig.configure(DropwizardResourceConfig.forTesting(new MetricRegistry()), resourceTestRule);
    }

    public static Application configure(DropwizardResourceConfig config, ResourceTestRule resourceTestRule) {

        for (Class<?> provider : resourceTestRule.providers) {
            config.register(provider);
        }
        for (Map.Entry<String, Object> property : resourceTestRule.properties.entrySet()) {
            config.property(property.getKey(), property.getValue());
        }
        config.register(new JacksonMessageBodyProvider(resourceTestRule.mapper, resourceTestRule.validator));
        for (Object singleton : resourceTestRule.singletons) {
            config.register(singleton);
        }

        return config;
    }
}


@Override
public Statement apply(final Statement base, Description description) {
    final ResourceTestRule rule = this;
    return new Statement() {
        @Override
        public void evaluate() throws Throwable {
            try {

                test = new JerseyTest() {
                    @Override
                    protected TestContainerFactory getTestContainerFactory() throws TestContainerException {
                        return testContainerFactory;
                    }

                    @Override
                    protected DeploymentContext configureDeployment() {
                        if (! isServletContext) {
                            return DeploymentContext.builder(ResourceTestResourceConfig.configure(rule)).build();
                        } else {

                            String ruleId = String.valueOf(rule.hashCode());
                            return ServletDeploymentContext.builder(new ResourceTestResourceConfig(ruleId, rule))
                                    .initParam(ServletProperties.JAXRS_APPLICATION_CLASS, ResourceTestResourceConfig.class.getName())
                                    .initParam(RULE_ID, ruleId)
                                    .build();
                        }
                    }
                };
                test.setUp();
                base.evaluate();
            } finally {
                if (test != null) {
                    test.tearDown();
                }
            }
        }
    };
}
```

**Comment by carlo-rtr** [comment]
@ferdy-lw thanks for work around. I've posted the PR, let's see what others think.

I'm not sure it's the most elegant solution, but it works and this is limited to the test code base.
