### ISSUE TITLE
Migration guide from 0.7.1 to 0.8.0

### ISSUE THREAD

**Issue by McPringle** [dropwizard/dropwizard#934]
I'm trying to update Dropwizard 0.7.1 to 0.8.0 in one of my applications. I could not get it to work for about 2 complete business days. I have compile errors in every class (really every class, I have no single class without compile errors). It is really hard to find information what to do. I had to search the internet for hours. That was the reason to stop the migration because it is a lot too expensive.

Am I the only one with these problems? I don't think so because I develop software for a long time and I don't think (or hope) that I'm really such bad. Can you please provide a migration guide what has to be done to upgrade Dropwizard?

**Comment by jplock** [comment]
There's currently a post on the mailing list that describes some migration steps - https://groups.google.com/d/msg/dropwizard-user/S4K3Ayfij3g/AzMBwJekfnEJ

**Comment by jplock** [comment]
Oh sorry, you are going from 0.7 to 0.8.  What sort of errors are you seeing?  Besides updating a lot of the Jersey Client stuff and then changing all of your unit tests to use assertj (those are the big ones), what else are you experiencing?

**Comment by arteam** [comment]
There is a [post](https://groups.google.com/forum/#!topic/dropwizard-dev/VInOW_ebiAc) in the dropwizard-dev mailing list about migration from 0.7.1 to 0.8.

Most problem are caused by update to Jersey 2. We had to change a lot internally to fully support
it. Despite that migration could be painful, we had successfull feedback from people about updates to RC builds.

About documentation, you are right - we need some guide about migration. You are not the first, asking for that and refer people to the mailing discussion is not good.

**Comment by McPringle** [comment]
I think a wiki could be useful, where everyone can add information about migration steps. For example I use a lot of Apache commons lang features which are now in a different package. Easy to solve if you know it. Can be hard to find if you first think the library was replaced by guava which provides nearly the same functionality.

**Comment by carlo-rtr** [comment]
I think the wiki is a good idea. Here is a first go:
https://github.com/dropwizard/dropwizard/wiki

We should limit it to documenting the upgrade process

**Comment by McPringle** [comment]
Thanks @carlo-rtf, I started adding hints to the wiki.
