### ISSUE TITLE
Site is not working

### ISSUE THREAD

**Issue by fellz** [dropwizard/dropwizard#955]
What happened ?

**Comment by arteam** [comment]
We host the site through GitHub Pages. They are under DDoS now. 
https://status.github.com/messages

Stay tuned.

**Comment by joschi** [comment]
@fellz The domain dropwizard.io currently has an invalid A resource record. Please use http://www.dropwizard.io or https://dropwizard.github.io/dropwizard/ until we fixed this.

I'm closing this issue because it's not exactly a bug in Dropwizard and we're aware of the problem (and going to fix it). Thanks!
