### ISSUE TITLE
Blended Capacity Metric

### ISSUE THREAD

**Issue by carlo-rtr** [dropwizard/dropwizard#964]
Capacity and utilization metrics. Basically a synthesized metric representing how much more traffic a node can handle before a new one is required. We will need assistance from OS, perhaps we can use
https://support.hyperic.com/display/SIGAR/Home

**Comment by johann8384** [comment]
There are several metricsets for OS and Filesystem metrics. If you incorporated those you might be able to define some rules around what is considered "% utilized".

https://github.com/turn/metrics-system/tree/master/src/main/java/com/turn/metrics/system
https://github.com/tguzik/metrics-os/blob/master/src/main/java/com/tguzik/metrics/os/OperatingSystemGaugeSet.java

It would possibly get complicated though because there would be different variables you'd want to include. Some users may want to take into account "% remaining HEAP" and "% CPU Utilization" but otthers might want to determine their capacity entirely based on disk I/O metrics.
